const std = @import("std");
const InsertHeaderSnippets = @import("InsertHeaderSnippets.zig");

// Importing ZON without specifying a result type might be supported in the future. Then we could
// make the following code less verbose more robust.
const Schema = struct {
    name: []const u8,
    version: []const u8,
    dependencies: struct {
        upstream: struct { url: []const u8, hash: []const u8 },
    },
    paths: []const []const u8,
};
const zon: Schema = @import("build.zig.zon");
const version = zon.version;

pub fn build(b: *std.Build) void {
    const upstream = b.dependency("upstream", .{});

    const include = b.addWriteFiles();
    b.installDirectory(.{
        .source_dir = include.getDirectory(),
        .install_dir = .header,
        .install_subdir = "",
    });

    inline for (headers) |header| {
        const style: std.Build.Step.ConfigHeader.Style = switch (header.style) {
            .autoconf => |p| .{ .autoconf = upstream.path(p) },
            .cmake => |p| .{ .cmake = upstream.path(p) },
            .blank => .blank,
        };
        addConfigHeaderWithSnippets(
            include,
            header.sub_path,
            style,
            header.values,
            header.snippets,
        );
    }

    const check = b.step("check", "Check if GNU M4 compiles");
    check.dependOn(&include.step);
}

fn addConfigHeaderWithSnippets(
    write_file: *std.Build.Step.WriteFile,
    sub_path: []const u8,
    style: std.Build.Step.ConfigHeader.Style,
    comptime value_tags: []const ConfigValueTag,
    snippet_tags: []const SnippetTag,
) void {
    const b = write_file.step.owner;

    const config_header = b.addConfigHeader(
        .{ .style = style, .include_path = sub_path },
        extractValues(value_tags),
    );
    // This should be fixed in ConfigHeader, see:
    // https://github.com/ziglang/zig/issues/16208
    if (style.getPath()) |lp| lp.addStepDependencies(&config_header.step);

    const source = if (snippet_tags.len == 0)
        config_header.getOutput()
    else blk: {
        for (snippet_tags, 0..) |s, i| {
            for (snippet_tags[i + 1 ..]) |t| {
                if (s == t) @panic("Duplicate snippet.");
            }
        }

        const upstream = b.dependency("upstream", .{});
        const max_count_snippets = @typeInfo(SnippetTag).@"enum".fields.len;
        var snippets: [max_count_snippets]InsertHeaderSnippets.Snippet = undefined;

        for (snippet_tags, snippets[0..snippet_tags.len]) |tag, *snippet| {
            snippet.* = switch (tag) {
                ._GL_FUNCDECL_RPL => .{
                    .file = upstream.path("lib/c++defs.h"),
                    .line_pattern = "definitions of _GL_FUNCDECL_RPL",
                },
                ._Noreturn => .{
                    .file = upstream.path("lib/_Noreturn.h"),
                    .line_pattern = "definition of _Noreturn",
                },
                ._GL_ARG_NONNULL => .{
                    .file = upstream.path("lib/arg-nonnull.h"),
                    .line_pattern = "definition of _GL_ARG_NONNULL",
                },
                ._GL_WARN_ON_USE => .{
                    .file = upstream.path("lib/warn-on-use.h"),
                    .line_pattern = "definition of _GL_WARN_ON_USE",
                },
            };
        }

        const header = InsertHeaderSnippets.create(b, .{
            .source_file = config_header.getOutput(),
            .snippets = snippets[0..snippet_tags.len],
        });
        break :blk header.getOutput();
    };

    _ = write_file.addCopyFile(source, sub_path);
}

const SnippetTag = enum {
    _GL_FUNCDECL_RPL,
    _Noreturn,
    _GL_ARG_NONNULL,
    _GL_WARN_ON_USE,
};

const ConfigValueTag = blk: {
    var enum_fields: [config_values_fields.len]std.builtin.Type.EnumField = undefined;
    for (config_values_fields, &enum_fields, 0..) |struct_field, *enum_field, i| {
        enum_field.* = .{ .name = struct_field.name, .value = i };
    }
    break :blk @Type(.{
        .@"enum" = .{
            .tag_type = u32,
            .fields = &enum_fields,
            .decls = &.{},
            .is_exhaustive = true,
        },
    });
};

fn ExtractValues(comptime tags: []const ConfigValueTag) type {
    var fields: [tags.len]std.builtin.Type.StructField = undefined;
    for (tags, &fields) |tag, *field| {
        field.* = config_values_fields[@intFromEnum(tag)];
    }
    return @Type(.{
        .@"struct" = .{
            .layout = .auto,
            .fields = &fields,
            .decls = &.{},
            .is_tuple = false,
        },
    });
}

fn extractValues(comptime tags: []const ConfigValueTag) ExtractValues(tags) {
    @setEvalBranchQuota(10 * config_values_fields.len);
    var result: ExtractValues(tags) = undefined;
    inline for (tags) |tag| {
        const name = @tagName(tag);
        @field(result, name) = @field(config_values, name);
    }
    return result;
}

const Header = struct {
    sub_path: []const u8,
    style: Style,
    values: []const ConfigValueTag,
    snippets: []const SnippetTag,

    pub const Style = union(enum) {
        autoconf: []const u8,
        cmake: []const u8,
        blank,
    };
};

const headers = [_]Header{
    .{
        .sub_path = "config.h",
        .style = .{ .autoconf = "lib/config.hin" },
        .values = config_h_values,
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "alloca.h",
        .style = .{ .cmake = "lib/alloca.in.h" },
        .values = &[_]ConfigValueTag{.HAVE_ALLOCA_H},
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "configmake.h",
        .style = .blank,
        // The macros defined in `configmake.h` are unused since we disable native language support.
        .values = &[_]ConfigValueTag{},
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "dirent.h",
        .style = .{ .cmake = "lib/dirent.in.h" },
        .values = dirent_h_values,
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "fcntl.h",
        .style = .{ .cmake = "lib/fcntl.in.h" },
        .values = fcntl_h_values,
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "iconv.h",
        .style = .{ .cmake = "lib/iconv.in.h" },
        .values = iconv_h_values,
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
};

const config_values_fields = @typeInfo(@TypeOf(config_values)).@"struct".fields;

const config_values = .{
    .@"inline" = null,
    .AC_APPLE_UNIVERSAL_BUILD = null,
    .BITSIZEOF_PTRDIFF_T = null,
    .BITSIZEOF_SIG_ATOMIC_T = null,
    .BITSIZEOF_SIZE_T = null,
    .BITSIZEOF_WCHAR_T = null,
    .BITSIZEOF_WINT_T = null,
    .CHECK_PRINTF_SAFE = 1,
    .C_ALLOCA = null,
    .DBL_EXPBIT0_BIT = 20,
    .DBL_EXPBIT0_WORD = 1,
    .DBL_SIGNBIT_BIT = null,
    .DBL_SIGNBIT_WORD = null,
    .DIR_FD_MEMBER_NAME = null,
    .DOUBLE_SLASH_IS_DISTINCT_ROOT = null,
    .D_INO_IN_DIRENT = 1,
    .ENABLE_CHANGEWORD = null,
    .ENABLE_NLS = null,
    .FCNTL_DUPFD_BUGGY = null,
    .FLEXIBLE_ARRAY_MEMBER = {},
    .FLT_EXPBIT0_BIT = 23,
    .FLT_EXPBIT0_WORD = 0,
    .FLT_SIGNBIT_BIT = null,
    .FLT_SIGNBIT_WORD = null,
    .FOPEN_TRAILING_SLASH_BUG = null,
    .FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE = null,
    .FTELLO_BROKEN_AFTER_UNGETC = null,
    .FUNC_FFLUSH_STDIN = 0,
    .FUNC_MKDIR_DOT_BUG = null,
    .FUNC_NL_LANGINFO_YESEXPR_WORKS = 1,
    .FUNC_REALPATH_NEARLY_WORKS = null,
    .FUNC_REALPATH_WORKS = 1,
    .FUNC_UNGETC_BROKEN = null,
    .GETTIMEOFDAY_TIMEZONE = .void,
    .GNULIB_ALPHASORT = 0,
    .GNULIB_CANONICALIZE = 1,
    .GNULIB_CANONICALIZE_LGPL = 1,
    .GNULIB_CLOSEDIR = 1,
    .GNULIB_CLOSE_STREAM = 1,
    .GNULIB_CREAT = .IN_M4_GNULIB_TESTS,
    .GNULIB_DIRFD = 1,
    .GNULIB_DIRNAME = 1,
    .GNULIB_FCNTL = 1,
    .GNULIB_FDOPENDIR = 1,
    .GNULIB_FD_SAFER_FLAG = 1,
    .GNULIB_FFLUSH = 1,
    .GNULIB_FILENAMECAT = 1,
    .GNULIB_FOPEN_GNU = 1,
    .GNULIB_FOPEN_SAFER = 1,
    .GNULIB_FSCANF = 1,
    .GNULIB_GETCWD = 1,
    .GNULIB_ICONV = 1,
    .GNULIB_ISBLANK = .IN_M4_GNULIB_TESTS,
    .GNULIB_LOCK = 1,
    .GNULIB_MBRTOWC_SINGLE_THREAD = 1,
    .GNULIB_MDA_CREAT = 1,
    .GNULIB_MDA_OPEN = 1,
    .GNULIB_MSVC_NOTHROW = 1,
    .GNULIB_NONBLOCKING = 0,
    .GNULIB_OPEN = 1,
    .GNULIB_OPENAT = 1,
    .GNULIB_OPENDIR = 1,
    .GNULIB_PIPE2_SAFER = 1,
    .GNULIB_PRINTF_ATTRIBUTE_FLAVOR_GNU = null,
    .GNULIB_READDIR = 1,
    .GNULIB_REALLOCARRAY = 1,
    .GNULIB_REGEX_SINGLE_THREAD = 1,
    .GNULIB_REWINDDIR = 1,
    .GNULIB_SCANDIR = 0,
    .GNULIB_SCANF = 1,
    .GNULIB_SIGPIPE = 1,
    .GNULIB_SNPRINTF = 1,
    .GNULIB_STDIO_SINGLE_THREAD = 1,
    .GNULIB_STRERROR = 1,
    .GNULIB_STRERROR_R_POSIX = .IN_M4_GNULIB_TESTS,
    .GNULIB_TEMPNAME = 1,
    .GNULIB_TEST_ACCEPT = 1,
    .GNULIB_TEST_ACCESS = 1,
    .GNULIB_TEST_BIND = 1,
    .GNULIB_TEST_BTOWC = 1,
    .GNULIB_TEST_CALLOC_POSIX = 1,
    .GNULIB_TEST_CANONICALIZE = 1,
    .GNULIB_TEST_CANONICALIZE_FILE_NAME = 1,
    .GNULIB_TEST_CHDIR = 1,
    .GNULIB_TEST_CLOEXEC = 1,
    .GNULIB_TEST_CLOSE = 1,
    .GNULIB_TEST_CLOSEDIR = 1,
    .GNULIB_TEST_CONNECT = 1,
    .GNULIB_TEST_CREAT = 1,
    .GNULIB_TEST_DIRFD = 1,
    .GNULIB_TEST_DUP = 1,
    .GNULIB_TEST_DUP2 = 1,
    .GNULIB_TEST_ENVIRON = 1,
    .GNULIB_TEST_EXPLICIT_BZERO = 1,
    .GNULIB_TEST_FCHDIR = 1,
    .GNULIB_TEST_FCLOSE = 1,
    .GNULIB_TEST_FCNTL = 1,
    .GNULIB_TEST_FDOPEN = 1,
    .GNULIB_TEST_FDOPENDIR = 1,
    .GNULIB_TEST_FFLUSH = 1,
    .GNULIB_TEST_FGETC = 1,
    .GNULIB_TEST_FGETS = 1,
    .GNULIB_TEST_FOPEN = 1,
    .GNULIB_TEST_FPRINTF = 1,
    .GNULIB_TEST_FPURGE = 1,
    .GNULIB_TEST_FPUTC = 1,
    .GNULIB_TEST_FPUTS = 1,
    .GNULIB_TEST_FREAD = 1,
    .GNULIB_TEST_FREE_POSIX = 1,
    .GNULIB_TEST_FREOPEN = 1,
    .GNULIB_TEST_FREXP = 1,
    .GNULIB_TEST_FREXPL = 1,
    .GNULIB_TEST_FSCANF = 1,
    .GNULIB_TEST_FSEEK = 1,
    .GNULIB_TEST_FSEEKO = 1,
    .GNULIB_TEST_FSTAT = 1,
    .GNULIB_TEST_FSTATAT = 1,
    .GNULIB_TEST_FTELL = 1,
    .GNULIB_TEST_FTELLO = 1,
    .GNULIB_TEST_FTRUNCATE = 1,
    .GNULIB_TEST_FWRITE = 1,
    .GNULIB_TEST_GETC = 1,
    .GNULIB_TEST_GETCHAR = 1,
    .GNULIB_TEST_GETCWD = 1,
    .GNULIB_TEST_GETDTABLESIZE = 1,
    .GNULIB_TEST_GETOPT_POSIX = 1,
    .GNULIB_TEST_GETPAGESIZE = 1,
    .GNULIB_TEST_GETRANDOM = 1,
    .GNULIB_TEST_GETTIMEOFDAY = 1,
    .GNULIB_TEST_IOCTL = 1,
    .GNULIB_TEST_ISWBLANK = 1,
    .GNULIB_TEST_ISWDIGIT = 1,
    .GNULIB_TEST_ISWXDIGIT = 1,
    .GNULIB_TEST_LINK = 1,
    .GNULIB_TEST_LISTEN = 1,
    .GNULIB_TEST_LOCALECONV = 1,
    .GNULIB_TEST_LOCALENAME = 1,
    .GNULIB_TEST_LSEEK = 1,
    .GNULIB_TEST_LSTAT = 1,
    .GNULIB_TEST_MALLOC_POSIX = 1,
    .GNULIB_TEST_MBRTOWC = 1,
    .GNULIB_TEST_MBSINIT = 1,
    .GNULIB_TEST_MBSLEN = 1,
    .GNULIB_TEST_MBSSTR = 1,
    .GNULIB_TEST_MBTOWC = 1,
    .GNULIB_TEST_MEMCHR = 1,
    .GNULIB_TEST_MEMPCPY = 1,
    .GNULIB_TEST_MEMRCHR = 1,
    .GNULIB_TEST_MKDIR = 1,
    .GNULIB_TEST_MKDTEMP = 1,
    .GNULIB_TEST_MKSTEMP = 1,
    .GNULIB_TEST_NANOSLEEP = 1,
    .GNULIB_TEST_NL_LANGINFO = 1,
    .GNULIB_TEST_OPEN = 1,
    .GNULIB_TEST_OPENAT = 1,
    .GNULIB_TEST_OPENDIR = 1,
    .GNULIB_TEST_PERROR = 1,
    .GNULIB_TEST_PIPE = 1,
    .GNULIB_TEST_PIPE2 = 1,
    .GNULIB_TEST_POSIX_SPAWN = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_DESTROY = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_INIT = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETFLAGS = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETPGROUP = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETSIGMASK = 1,
    .GNULIB_TEST_POSIX_SPAWNP = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2 = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_DESTROY = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_INIT = 1,
    .GNULIB_TEST_PRINTF = 1,
    .GNULIB_TEST_PTHREAD_SIGMASK = 1,
    .GNULIB_TEST_PTHREAD_THREAD = 1,
    .GNULIB_TEST_PUTC = 1,
    .GNULIB_TEST_PUTCHAR = 1,
    .GNULIB_TEST_PUTENV = 1,
    .GNULIB_TEST_PUTS = 1,
    .GNULIB_TEST_RAISE = 1,
    .GNULIB_TEST_RAWMEMCHR = 1,
    .GNULIB_TEST_READDIR = 1,
    .GNULIB_TEST_READLINK = 1,
    .GNULIB_TEST_REALLOCARRAY = 1,
    .GNULIB_TEST_REALLOC_POSIX = 1,
    .GNULIB_TEST_REALPATH = 1,
    .GNULIB_TEST_RENAME = 1,
    .GNULIB_TEST_REWINDDIR = 1,
    .GNULIB_TEST_RMDIR = 1,
    .GNULIB_TEST_SCANF = 1,
    .GNULIB_TEST_SCHED_YIELD = 1,
    .GNULIB_TEST_SECURE_GETENV = 1,
    .GNULIB_TEST_SELECT = 1,
    .GNULIB_TEST_SETENV = 1,
    .GNULIB_TEST_SETLOCALE = 1,
    .GNULIB_TEST_SETLOCALE_NULL = 1,
    .GNULIB_TEST_SETSOCKOPT = 1,
    .GNULIB_TEST_SIGACTION = 1,
    .GNULIB_TEST_SIGNBIT = 1,
    .GNULIB_TEST_SIGPROCMASK = 1,
    .GNULIB_TEST_SLEEP = 1,
    .GNULIB_TEST_SNPRINTF = 1,
    .GNULIB_TEST_SOCKET = 1,
    .GNULIB_TEST_STAT = 1,
    .GNULIB_TEST_STPCPY = 1,
    .GNULIB_TEST_STRCHRNUL = 1,
    .GNULIB_TEST_STRDUP = 1,
    .GNULIB_TEST_STRERROR = 1,
    .GNULIB_TEST_STRERROR_R = 1,
    .GNULIB_TEST_STRNDUP = 1,
    .GNULIB_TEST_STRNLEN = 1,
    .GNULIB_TEST_STRSIGNAL = 1,
    .GNULIB_TEST_STRSTR = 1,
    .GNULIB_TEST_STRTOD = 1,
    .GNULIB_TEST_SYMLINK = 1,
    .GNULIB_TEST_UNSETENV = 1,
    .GNULIB_TEST_VASPRINTF = 1,
    .GNULIB_TEST_VFPRINTF = 1,
    .GNULIB_TEST_VPRINTF = 1,
    .GNULIB_TEST_WAITPID = 1,
    .GNULIB_TEST_WCRTOMB = 1,
    .GNULIB_TEST_WCTOB = 1,
    .GNULIB_TEST_WCTOMB = 1,
    .GNULIB_TEST_WCWIDTH = 1,
    .GNULIB_TEST_WRITE = 1,
    .GNULIB_UNISTR_U8_MBTOUCR = 1,
    .GNULIB_UNISTR_U8_UCTOMB = 1,
    .GNULIB_WCHAR_SINGLE_LOCALE = 1,
    .GNULIB_XALLOC = 1,
    .GNULIB_XALLOC_DIE = 1,
    .GUARD_PREFIX = .GL_M4,
    .HAVE_ALLOCA = 1,
    .HAVE_ALLOCA_H = 1,
    .HAVE_ALPHASORT = 1,
    .HAVE_ARPA_INET_H = 1,
    .HAVE_BCRYPT_H = null,
    .HAVE_BP_SYM_H = null,
    .HAVE_BTOWC = 1,
    .HAVE_BUG_BIG_NANOSLEEP = 1,
    .HAVE_CANONICALIZE_FILE_NAME = 1,
    .HAVE_CATGETS = 1,
    .HAVE_CFLOCALECOPYPREFERREDLANGUAGES = null,
    .HAVE_CFPREFERENCESCOPYAPPVALUE = null,
    .HAVE_CLOCK_GETTIME = 1,
    .HAVE_CLOCK_SETTIME = 1,
    .HAVE_CLOSEDIR = 1,
    .HAVE_CLOSE_RANGE = 1,
    .HAVE_CONFSTR = null,
    .HAVE_COPYSIGNF_IN_LIBC = null,
    .HAVE_COPYSIGNL_IN_LIBC = null,
    .HAVE_COPYSIGN_IN_LIBC = null,
    .HAVE_CRTDEFS_H = null,
    .HAVE_DCGETTEXT = null,
    .HAVE_DECL_ALARM = 1,
    .HAVE_DECL_CLEARERR_UNLOCKED = 1,
    .HAVE_DECL_COPYSIGN = null,
    .HAVE_DECL_COPYSIGNF = null,
    .HAVE_DECL_COPYSIGNL = null,
    .HAVE_DECL_DIRFD = 1,
    .HAVE_DECL_ECVT = 1,
    .HAVE_DECL_EXECVPE = 1,
    .HAVE_DECL_FCHDIR = 1,
    .HAVE_DECL_FCLOSEALL = 1,
    .HAVE_DECL_FCVT = 1,
    .HAVE_DECL_FDOPENDIR = 1,
    .HAVE_DECL_FEOF_UNLOCKED = 1,
    .HAVE_DECL_FERROR_UNLOCKED = 1,
    .HAVE_DECL_FFLUSH_UNLOCKED = 1,
    .HAVE_DECL_FGETS_UNLOCKED = 1,
    .HAVE_DECL_FPURGE = 0,
    .HAVE_DECL_FPUTC_UNLOCKED = 1,
    .HAVE_DECL_FPUTS_UNLOCKED = 1,
    .HAVE_DECL_FREAD_UNLOCKED = 1,
    .HAVE_DECL_FSEEKO = 1,
    .HAVE_DECL_FTELLO = 1,
    .HAVE_DECL_FWRITE_UNLOCKED = 1,
    .HAVE_DECL_GCVT = 1,
    .HAVE_DECL_GETCHAR_UNLOCKED = 1,
    .HAVE_DECL_GETCWD = 1,
    .HAVE_DECL_GETC_UNLOCKED = 1,
    .HAVE_DECL_GETDTABLESIZE = 1,
    .HAVE_DECL_INET_PTON = 1,
    .HAVE_DECL_ISBLANK = 1,
    .HAVE_DECL_ISWBLANK = 1,
    .HAVE_DECL_MBRTOWC = null,
    .HAVE_DECL_MBSINIT = null,
    .HAVE_DECL_MEMRCHR = 1,
    .HAVE_DECL_POSIX_SPAWN = 1,
    .HAVE_DECL_PROGRAM_INVOCATION_NAME = 1,
    .HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME = 1,
    .HAVE_DECL_PUTCHAR_UNLOCKED = 1,
    .HAVE_DECL_PUTC_UNLOCKED = 1,
    .HAVE_DECL_SETENV = 1,
    .HAVE_DECL_SLEEP = 1,
    .HAVE_DECL_SNPRINTF = 1,
    .HAVE_DECL_STRDUP = 1,
    .HAVE_DECL_STRERROR_R = 1,
    .HAVE_DECL_STRNDUP = 1,
    .HAVE_DECL_STRNLEN = 1,
    .HAVE_DECL_STRSIGNAL = 1,
    .HAVE_DECL_SYS_SIGLIST = null,
    .HAVE_DECL_TOWLOWER = null,
    .HAVE_DECL_UNSETENV = 1,
    .HAVE_DECL_WCRTOMB = null,
    .HAVE_DECL_WCSDUP = 1,
    .HAVE_DECL_WCTOB = 1,
    .HAVE_DECL_WCWIDTH = 1,
    .HAVE_DECL__FSEEKI64 = null,
    .HAVE_DECL__PUTENV = null,
    .HAVE_DECL__SNPRINTF = 0,
    .HAVE_DECL__SYS_SIGLIST = null,
    .HAVE_DECL___ARGV = 0,
    .HAVE_DECL___FPENDING = 1,
    .HAVE_DIRENT_H = 1,
    .HAVE_DIRFD = 1,
    .HAVE_DUPLOCALE = 1,
    .HAVE_ENVIRON_DECL = 1,
    .HAVE_EXPLICIT_BZERO = 1,
    .HAVE_EXPLICIT_MEMSET = null,
    .HAVE_FACCESSAT = 1,
    .HAVE_FAKE_LOCALES = null,
    .HAVE_FCHDIR = 1,
    .HAVE_FCNTL = 1,
    .HAVE_FDOPENDIR = 1,
    .HAVE_FEATURES_H = 1,
    .HAVE_FPURGE = null,
    .HAVE_FREELOCALE = 1,
    .HAVE_FREE_POSIX = 1,
    .HAVE_FREXPL_IN_LIBC = 1,
    .HAVE_FREXP_IN_LIBC = 1,
    .HAVE_FSEEKO = 1,
    .HAVE_FSTATAT = 1,
    .HAVE_FTRUNCATE = 1,
    .HAVE_GETCWD = 1,
    .HAVE_GETCWD_SHORTER = null,
    .HAVE_GETDTABLESIZE = 1,
    .HAVE_GETEGID = 1,
    .HAVE_GETEUID = 1,
    .HAVE_GETEXECNAME = null,
    .HAVE_GETGID = 1,
    .HAVE_GETLOCALENAME_L = null,
    .HAVE_GETOPT_H = 1,
    .HAVE_GETOPT_LONG_ONLY = 1,
    .HAVE_GETPAGESIZE = null,
    .HAVE_GETPROGNAME = null,
    .HAVE_GETRANDOM = 1,
    .HAVE_GETRLIMIT = 1,
    .HAVE_GETTEXT = null,
    .HAVE_GETTIMEOFDAY = 1,
    .HAVE_GETUID = 1,
    .HAVE_GOOD_USELOCALE = 1,
    .HAVE_ICONV = 1,
    .HAVE_ICONV_H = 1,
    .HAVE_INET_PTON = null,
    .HAVE_INLINE = 1,
    .HAVE_INTMAX_T = 1,
    .HAVE_INTTYPES_H = 1,
    .HAVE_INTTYPES_H_WITH_UINTMAX = 1,
    .HAVE_IOCTL = 1,
    .HAVE_IPV4 = 1,
    .HAVE_IPV6 = 1,
    .HAVE_ISBLANK = 1,
    .HAVE_ISNAND_IN_LIBC = 1,
    .HAVE_ISNANF_IN_LIBC = 1,
    .HAVE_ISNANL_IN_LIBC = 1,
    .HAVE_ISSETUGID = null,
    .HAVE_ISWBLANK = 1,
    .HAVE_ISWCNTRL = 1,
    .HAVE_ISWCTYPE = 1,
    .HAVE_LANGINFO_CODESET = 1,
    .HAVE_LANGINFO_H = 1,
    .HAVE_LC_MESSAGES = 1,
    .HAVE_LDEXPL_IN_LIBC = 1,
    .HAVE_LDEXP_IN_LIBC = 1,
    .HAVE_LIBINTL_H = 1,
    .HAVE_LIBSIGSEGV = null,
    .HAVE_LIB_BCRYPT = null,
    .HAVE_LIMITS_H = 1,
    .HAVE_LINK = 1,
    .HAVE_LONG_LONG_INT = 1,
    .HAVE_LSTAT = 1,
    .HAVE_MALLOC_H = 1,
    .HAVE_MALLOC_POSIX = 1,
    .HAVE_MAP_ANONYMOUS = 1,
    .HAVE_MATH_H = 1,
    .HAVE_MBRTOWC = 1,
    .HAVE_MBSINIT = 1,
    .HAVE_MBSLEN = null,
    .HAVE_MBSTATE_T = 1,
    .HAVE_MBTOWC = 1,
    .HAVE_MEMPCPY = 1,
    .HAVE_MEMRCHR = 1,
    .HAVE_MEMSET_S = null,
    .HAVE_MINIMALLY_WORKING_GETCWD = 1,
    .HAVE_MINIX_CONFIG_H = null,
    .HAVE_MINMAX_IN_LIMITS_H = null,
    .HAVE_MINMAX_IN_SYS_PARAM_H = 1,
    .HAVE_MKDTEMP = 1,
    .HAVE_MKSTEMP = 1,
    .HAVE_MPROTECT = 1,
    .HAVE_MQUERY = null,
    .HAVE_MSVC_INVALID_PARAMETER_HANDLER = null,
    .HAVE_NAMELESS_LOCALES = null,
    .HAVE_NETDB_H = 1,
    .HAVE_NETINET_IN_H = 1,
    .HAVE_NEWLOCALE = 1,
    .HAVE_NL_LANGINFO = 1,
    .HAVE_OBSTACK = null,
    .HAVE_OPENAT = 1,
    .HAVE_OPENDIR = 1,
    .HAVE_OS_H = null,
    .HAVE_PARTLY_WORKING_GETCWD = null,
    .HAVE_PATHS_H = null,
    .HAVE_PIPE = 1,
    .HAVE_PIPE2 = 1,
    .HAVE_POSIX_SPAWN = 1,
    .HAVE_POSIX_SPAWNATTR_T = 1,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = null,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR_NP = 1,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_T = 1,
    .HAVE_PSTAT_GETPROCVM = null,
    .HAVE_PTHREAD_API = 1,
    .HAVE_PTHREAD_ATFORK = null,
    .HAVE_PTHREAD_H = 1,
    .HAVE_PTHREAD_MUTEX_RECURSIVE = null,
    .HAVE_PTHREAD_RWLOCK = null,
    .HAVE_PTHREAD_RWLOCK_RDLOCK_PREFER_WRITER = null,
    .HAVE_PTHREAD_SIGMASK = 1,
    .HAVE_PTHREAD_SPINLOCK_T = 1,
    .HAVE_PTHREAD_T = 1,
    .HAVE_RAISE = 1,
    .HAVE_RAWMEMCHR = 1,
    .HAVE_READDIR = 1,
    .HAVE_READLINK = 1,
    .HAVE_REALLOCARRAY = 1,
    .HAVE_REALPATH = 1,
    .HAVE_REWINDDIR = 1,
    .HAVE_SAME_LONG_DOUBLE_AS_DOUBLE = null,
    .HAVE_SA_FAMILY_T = 1,
    .HAVE_SCANDIR = 1,
    .HAVE_SCHED_H = 1,
    .HAVE_SCHED_SETPARAM = null,
    .HAVE_SCHED_SETSCHEDULER = null,
    .HAVE_SDKDDKVER_H = null,
    .HAVE_SEARCH_H = 1,
    .HAVE_SECURE_GETENV = 1,
    .HAVE_SEMAPHORE_H = 1,
    .HAVE_SETDTABLESIZE = null,
    .HAVE_SETEGID = null,
    .HAVE_SETENV = 1,
    .HAVE_SETEUID = null,
    .HAVE_SETRLIMIT = 1,
    .HAVE_SHUTDOWN = 1,
    .HAVE_SIGACTION = 1,
    .HAVE_SIGALTSTACK = 1,
    .HAVE_SIGINFO_T = null,
    .HAVE_SIGINTERRUPT = 1,
    .HAVE_SIGNED_SIG_ATOMIC_T = null,
    .HAVE_SIGNED_WCHAR_T = null,
    .HAVE_SIGNED_WINT_T = null,
    .HAVE_SIGSET_T = 1,
    .HAVE_SIG_ATOMIC_T = 1,
    .HAVE_SLEEP = 1,
    .HAVE_SNPRINTF = 1,
    .HAVE_SNPRINTF_RETVAL_C99 = 1,
    .HAVE_SNPRINTF_TRUNCATION_C99 = 1,
    .HAVE_SOLARIS114_LOCALES = null,
    .HAVE_SPAWN_H = 1,
    .HAVE_STDINT_H = 1,
    .HAVE_STDINT_H_WITH_UINTMAX = 1,
    .HAVE_STDIO_EXT_H = 1,
    .HAVE_STDIO_H = 1,
    .HAVE_STDLIB_H = 1,
    .HAVE_STPCPY = 1,
    .HAVE_STRCHRNUL = 1,
    .HAVE_STRERROR_R = 1,
    .HAVE_STRINGS_H = 1,
    .HAVE_STRING_H = 1,
    .HAVE_STRNDUP = 1,
    .HAVE_STRNLEN = 1,
    .HAVE_STRSIGNAL = 1,
    .HAVE_STRUCT_LCONV_DECIMAL_POINT = null,
    .HAVE_STRUCT_SIGACTION_SA_SIGACTION = 1,
    .HAVE_STRUCT_SOCKADDR_STORAGE = 1,
    .HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY = 1,
    .HAVE_STRUCT_STAT_ST_ATIMENSEC = null,
    .HAVE_STRUCT_STAT_ST_ATIMESPEC_TV_NSEC = null,
    .HAVE_STRUCT_STAT_ST_ATIM_ST__TIM_TV_NSEC = null,
    .HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC = 1,
    .HAVE_STRUCT_STAT_ST_BIRTHTIMENSEC = null,
    .HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC = null,
    .HAVE_STRUCT_STAT_ST_BIRTHTIM_TV_NSEC = null,
    .HAVE_SYMLINK = 1,
    .HAVE_SYS_BITYPES_H = null,
    .HAVE_SYS_CDEFS_H = 1,
    .HAVE_SYS_INTTYPES_H = null,
    .HAVE_SYS_IOCTL_H = 1,
    .HAVE_SYS_MMAN_H = 1,
    .HAVE_SYS_PARAM_H = 1,
    .HAVE_SYS_RANDOM_H = 1,
    .HAVE_SYS_SELECT_H = 1,
    .HAVE_SYS_SINGLE_THREADED_H = 1,
    .HAVE_SYS_SOCKET_H = 1,
    .HAVE_SYS_STAT_H = 1,
    .HAVE_SYS_TIME_H = 1,
    .HAVE_SYS_TYPES_H = 1,
    .HAVE_SYS_UIO_H = 1,
    .HAVE_SYS_WAIT_H = 1,
    .HAVE_THRD_CREATE = null,
    .HAVE_THREADS_H = 1,
    .HAVE_TOWLOWER = 1,
    .HAVE_TSEARCH = 1,
    .HAVE_UNISTD_H = 1,
    .HAVE_UNSETENV = 1,
    .HAVE_UNSIGNED_LONG_LONG_INT = 1,
    .HAVE_USELOCALE = 1,
    .HAVE_VAR___PROGNAME = null,
    .HAVE_VASNPRINTF = null,
    .HAVE_VASPRINTF = 1,
    .HAVE_VFORK = null,
    .HAVE_VISIBILITY = null,
    .HAVE_WAITID = 1,
    .HAVE_WCHAR_H = 1,
    .HAVE_WCHAR_T = 1,
    .HAVE_WCRTOMB = 1,
    .HAVE_WCSLEN = 1,
    .HAVE_WCSNLEN = 1,
    .HAVE_WCTOB = 1,
    .HAVE_WCTYPE_H = 1,
    .HAVE_WCWIDTH = 1,
    .HAVE_WEAK_SYMBOLS = null,
    .HAVE_WINSOCK2_H = null,
    .HAVE_WINT_T = 1,
    .HAVE_WORKING_FSTATAT_ZERO_FLAG = null,
    .HAVE_WORKING_O_NOATIME = 1,
    .HAVE_WORKING_O_NOFOLLOW = 1,
    .HAVE_WORKING_SIGALTSTACK = 1,
    .HAVE_WORKING_USELOCALE = 1,
    .HAVE_WS2TCPIP_H = null,
    .HAVE_XLOCALE_H = null,
    .HAVE__BOOL = 1,
    .HAVE__CHSIZE = null,
    .HAVE__FSEEKI64 = null,
    .HAVE__FTELLI64 = null,
    .HAVE__SET_INVALID_PARAMETER_HANDLER = null,
    .HAVE___BUILTIN_EXPECT = 1,
    .HAVE___FPURGE = 1,
    .HAVE___FREADAHEAD = null,
    .HAVE___FREADING = 1,
    .HAVE___INLINE = 1,
    .HAVE___SECURE_GETENV = null,
    .HAVE___XPG_STRERROR_R = 1,
    .ICONV_CONST = {},
    .ICONV_FLAVOR = null,
    .INCLUDE_NEXT = .include_next,
    .LDBL_EXPBIT0_BIT = 0,
    .LDBL_EXPBIT0_WORD = 2,
    .LDBL_SIGNBIT_BIT = null,
    .LDBL_SIGNBIT_WORD = null,
    .LOCALENAME_ENHANCE_LOCALE_FUNCS = null,
    .LSEEK_PIPE_BROKEN = null,
    .LSTAT_FOLLOWS_SLASHED_SYMLINK = 1,
    .MALLOC_0_IS_NONNULL = 1,
    .MAP_ANONYMOUS = null,
    .MBRTOWC_EMPTY_INPUT_BUG = null,
    .MBRTOWC_IN_C_LOCALE_MAYBE_EILSEQ = 1,
    .MBRTOWC_NULL_ARG1_BUG = null,
    .MBRTOWC_NULL_ARG2_BUG = null,
    .MBRTOWC_NUL_RETVAL_BUG = null,
    .MBRTOWC_RETVAL_BUG = null,
    .MBRTOWC_STORES_INCOMPLETE_BUG = null,
    .MUSL_LIBC = null,
    .NDEBUG = null,
    .NEED_PRINTF_DIRECTIVE_A = null,
    .NEED_PRINTF_DIRECTIVE_F = null,
    .NEED_PRINTF_DIRECTIVE_LS = null,
    .NEED_PRINTF_DOUBLE = null,
    .NEED_PRINTF_ENOMEM = null,
    .NEED_PRINTF_FLAG_GROUPING = null,
    .NEED_PRINTF_FLAG_LEFTADJUST = null,
    .NEED_PRINTF_FLAG_ZERO = null,
    .NEED_PRINTF_INFINITE_DOUBLE = null,
    .NEED_PRINTF_INFINITE_LONG_DOUBLE = null,
    .NEED_PRINTF_LONG_DOUBLE = null,
    .NEED_PRINTF_UNBOUNDED_PRECISION = null,
    .NEED_SETLOCALE_IMPROVED = 0,
    .NEED_SETLOCALE_MTSAFE = 0,
    .NEXT_DIRENT_H = .@"<dirent.h>",
    .NEXT_FCNTL_H = .@"<fcntl.h>",
    .NEXT_ICONV_H = .@"<iconv.h>",
    .NL_LANGINFO_MTSAFE = 1,
    .OPEN_TRAILING_SLASH_BUG = null,
    .PACKAGE = "m4",
    .PACKAGE_BUGREPORT = "bug-m4@gnu.org",
    .PACKAGE_NAME = "GNU M4",
    .PACKAGE_PACKAGER = null,
    .PACKAGE_PACKAGER_BUG_REPORTS = null,
    .PACKAGE_PACKAGER_VERSION = null,
    .PACKAGE_STRING = "GNU M4 " ++ version,
    .PACKAGE_TARNAME = "m4",
    .PACKAGE_URL = "https://www.gnu.org/software/m4/",
    .PACKAGE_VERSION = version,
    .PRAGMA_COLUMNS = null,
    .PRAGMA_SYSTEM_HEADER = .@"#pragma GCC system_header",
    .PROMOTED_MODE_T = .mode_t,
    .PTHREAD_CREATE_IS_INLINE = null,
    .PTHREAD_IN_USE_DETECTION_HARD = null,
    .PTHREAD_SIGMASK_FAILS_WITH_ERRNO = null,
    .PTHREAD_SIGMASK_INEFFECTIVE = null,
    .PTHREAD_SIGMASK_UNBLOCK_BUG = null,
    .PTRDIFF_T_SUFFIX = null,
    .READLINK_TRAILING_SLASH_BUG = null,
    .READLINK_TRUNCATE_BUG = null,
    .RENAME_DEST_EXISTS_BUG = null,
    .RENAME_HARD_LINK_BUG = null,
    .RENAME_OPEN_FILE_WORKS = 1,
    .RENAME_TRAILING_SLASH_DEST_BUG = null,
    .RENAME_TRAILING_SLASH_SOURCE_BUG = null,
    .REPLACE_CLOSEDIR = 0,
    .REPLACE_CREAT = 0,
    .REPLACE_DIRFD = 0, // Upstream sometimes sets this null, but it doesn't matter.
    .REPLACE_FCHDIR = null,
    .REPLACE_FCNTL = 1,
    .REPLACE_FDOPENDIR = 0,
    .REPLACE_FUNC_STAT_FILE = null,
    .REPLACE_ICONV = 0,
    .REPLACE_ICONV_OPEN = 0,
    .REPLACE_ICONV_UTF = 0,
    .REPLACE_NL_LANGINFO = null,
    .REPLACE_OPEN = 0,
    .REPLACE_OPENAT = 0,
    .REPLACE_OPENDIR = 0,
    .REPLACE_OPEN_DIRECTORY = null,
    .REPLACE_POSIX_SPAWN = null,
    .REPLACE_STRERROR_0 = null,
    .REPLACE_VASNPRINTF = null,
    .SETLOCALE_NULL_ALL_MTSAFE = 1,
    .SETLOCALE_NULL_ONE_MTSAFE = 1,
    .SIGALTSTACK_SS_REVERSED = null,
    .SIGNAL_SAFE_LIST = 1,
    .SIG_ATOMIC_T_SUFFIX = null,
    .SIZE_MAX = null,
    .SIZE_T_SUFFIX = null,
    .SOLARIS11 = null,
    .STACK_DIRECTION = -1,
    .STAT_MACROS_BROKEN = null,
    .STDC_HEADERS = 1,
    .STRERROR_R_CHAR_P = 1,
    .SYSCMD_SHELL = "/bin/sh",
    .TYPEOF_STRUCT_STAT_ST_ATIM_IS_STRUCT_TIMESPEC = 1,
    .USER_LABEL_PREFIX = {},
    .USE_ISOC_AND_POSIX_THREADS = null,
    .USE_ISOC_THREADS = null,
    .USE_POSIX_THREADS = null,
    .USE_POSIX_THREADS_WEAK = null,
    .USE_UNLOCKED_IO = .GNULIB_STDIO_SINGLE_THREAD,
    .USE_WINDOWS_THREADS = null,
    .VERSION = version,
    .VOID_UNSETENV = null,
    .WCHAR_T_SUFFIX = null,
    .WCRTOMB_C_LOCALE_BUG = null,
    .WCRTOMB_RETVAL_BUG = null,
    .WINDOWS_SOCKETS = null,
    .WINT_T_SUFFIX = null,
    .WITH_DMALLOC = null,
    .WORDS_BIGENDIAN = null,
    ._ALL_SOURCE = 1,
    ._DARWIN_C_SOURCE = 1,
    ._FILE_OFFSET_BITS = null,
    ._GNU_SOURCE = 1,
    ._HPUX_ALT_XOPEN_SOCKET_API = 1,
    ._ISOC11_SOURCE = null,
    ._LARGEFILE_SOURCE = null,
    ._LARGE_FILES = null,
    ._LCONV_C99 = null,
    ._MINIX = null,
    ._NETBSD_SOURCE = 1,
    ._OPENBSD_SOURCE = 1,
    ._POSIX_1_SOURCE = null,
    ._POSIX_PII_SOCKET = null,
    ._POSIX_PTHREAD_SEMANTICS = 1,
    ._POSIX_SOURCE = null,
    ._REGEX_INCLUDE_LIMITS_H = 1,
    ._REGEX_LARGE_OFFSETS = 1,
    ._TANDEM_SOURCE = 1,
    ._USE_STD_STAT = 1,
    ._XOPEN_SOURCE = null,
    .__EXTENSIONS__ = 1,
    .__GETOPT_PREFIX = null,
    .__STDC_CONSTANT_MACROS = null,
    .__STDC_LIMIT_MACROS = null,
    .__STDC_WANT_IEC_60559_ATTRIBS_EXT__ = 1,
    .__STDC_WANT_IEC_60559_BFP_EXT__ = 1,
    .__STDC_WANT_IEC_60559_DFP_EXT__ = 1,
    .__STDC_WANT_IEC_60559_FUNCS_EXT__ = 1,
    .__STDC_WANT_IEC_60559_TYPES_EXT__ = 1,
    .__STDC_WANT_LIB_EXT2__ = 1,
    .__STDC_WANT_MATH_SPEC_FUNCS__ = 1,
    .__USE_MINGW_ANSI_STDIO = 1,
    .__alpha__ = null,
    .__arm64__ = null,
    .__arm64_ilp32__ = null,
    .__arm__ = null,
    .__armhf__ = null,
    .__hppa64__ = null,
    .__hppa__ = null,
    .__i386__ = null,
    .__ia64__ = null,
    .__ia64_ilp32__ = null,
    .__m68k__ = null,
    .__mips64__ = null,
    .__mips__ = null,
    .__mipsn32__ = null,
    .__powerpc64__ = null,
    .__powerpc64_elfv2__ = null,
    .__powerpc__ = null,
    .__riscv32__ = null,
    .__riscv32_ilp32__ = null,
    .__riscv32_ilp32d__ = null,
    .__riscv32_ilp32f__ = null,
    .__riscv64__ = null,
    .__riscv64_ilp32__ = null,
    .__riscv64_ilp32d__ = null,
    .__riscv64_ilp32f__ = null,
    .__riscv64_lp64__ = null,
    .__riscv64_lp64d__ = null,
    .__riscv64_lp64f__ = null,
    .__s390__ = null,
    .__s390x__ = null,
    .__sh__ = null,
    .__sparc64__ = null,
    .__sparc__ = null,
    .__x86_64__ = 1,
    .__x86_64_x32__ = null,
    .eaccess = null,
    .gid_t = null,
    .intmax_t = null,
    .mbstate_t = null,
    .mode_t = null,
    .nlink_t = null,
    .off_t = null,
    .pid_t = null,
    .ptrdiff_t = null,
    .re_comp = .rpl_re_comp,
    .re_compile_fastmap = .rpl_re_compile_fastmap,
    .re_compile_pattern = .rpl_re_compile_pattern,
    .re_exec = .rpl_re_exec,
    .re_match = .rpl_re_match,
    .re_match_2 = .rpl_re_match_2,
    .re_search = .rpl_re_search,
    .re_search_2 = .rpl_re_search_2,
    .re_set_registers = .rpl_re_set_registers,
    .re_set_syntax = .rpl_re_set_syntax,
    .re_syntax_options = .rpl_re_syntax_options,
    .regcomp = .rpl_regcomp,
    .regerror = .rpl_regerror,
    .regexec = .rpl_regexec,
    .regfree = .rpl_regfree,
    .restrict = .__restrict__,
    .sig_atomic_t = null,
    .size_t = null,
    .socklen_t = null,
    .ssize_t = null,
    .stack_t = null,
    .uid_t = null,
    .va_copy = null,
};

const config_h_values = &[_]ConfigValueTag{
    .@"inline",
    .AC_APPLE_UNIVERSAL_BUILD,
    .BITSIZEOF_PTRDIFF_T,
    .BITSIZEOF_SIG_ATOMIC_T,
    .BITSIZEOF_SIZE_T,
    .BITSIZEOF_WCHAR_T,
    .BITSIZEOF_WINT_T,
    .CHECK_PRINTF_SAFE,
    .C_ALLOCA,
    .DBL_EXPBIT0_BIT,
    .DBL_EXPBIT0_WORD,
    .DBL_SIGNBIT_BIT,
    .DBL_SIGNBIT_WORD,
    .DIR_FD_MEMBER_NAME,
    .DOUBLE_SLASH_IS_DISTINCT_ROOT,
    .D_INO_IN_DIRENT,
    .ENABLE_CHANGEWORD,
    .ENABLE_NLS,
    .FCNTL_DUPFD_BUGGY,
    .FLEXIBLE_ARRAY_MEMBER,
    .FLT_EXPBIT0_BIT,
    .FLT_EXPBIT0_WORD,
    .FLT_SIGNBIT_BIT,
    .FLT_SIGNBIT_WORD,
    .FOPEN_TRAILING_SLASH_BUG,
    .FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE,
    .FTELLO_BROKEN_AFTER_UNGETC,
    .FUNC_FFLUSH_STDIN,
    .FUNC_MKDIR_DOT_BUG,
    .FUNC_NL_LANGINFO_YESEXPR_WORKS,
    .FUNC_REALPATH_NEARLY_WORKS,
    .FUNC_REALPATH_WORKS,
    .FUNC_UNGETC_BROKEN,
    .GETTIMEOFDAY_TIMEZONE,
    .GNULIB_CANONICALIZE,
    .GNULIB_CANONICALIZE_LGPL,
    .GNULIB_CLOSE_STREAM,
    .GNULIB_DIRNAME,
    .GNULIB_FDOPENDIR,
    .GNULIB_FD_SAFER_FLAG,
    .GNULIB_FFLUSH,
    .GNULIB_FILENAMECAT,
    .GNULIB_FOPEN_GNU,
    .GNULIB_FOPEN_SAFER,
    .GNULIB_FSCANF,
    .GNULIB_GETCWD,
    .GNULIB_ISBLANK,
    .GNULIB_LOCK,
    .GNULIB_MBRTOWC_SINGLE_THREAD,
    .GNULIB_MSVC_NOTHROW,
    .GNULIB_OPENAT,
    .GNULIB_PIPE2_SAFER,
    .GNULIB_PRINTF_ATTRIBUTE_FLAVOR_GNU,
    .GNULIB_REALLOCARRAY,
    .GNULIB_REGEX_SINGLE_THREAD,
    .GNULIB_SCANF,
    .GNULIB_SIGPIPE,
    .GNULIB_SNPRINTF,
    .GNULIB_STDIO_SINGLE_THREAD,
    .GNULIB_STRERROR,
    .GNULIB_STRERROR_R_POSIX,
    .GNULIB_TEMPNAME,
    .GNULIB_TEST_ACCEPT,
    .GNULIB_TEST_ACCESS,
    .GNULIB_TEST_BIND,
    .GNULIB_TEST_BTOWC,
    .GNULIB_TEST_CALLOC_POSIX,
    .GNULIB_TEST_CANONICALIZE,
    .GNULIB_TEST_CANONICALIZE_FILE_NAME,
    .GNULIB_TEST_CHDIR,
    .GNULIB_TEST_CLOEXEC,
    .GNULIB_TEST_CLOSE,
    .GNULIB_TEST_CLOSEDIR,
    .GNULIB_TEST_CONNECT,
    .GNULIB_TEST_CREAT,
    .GNULIB_TEST_DIRFD,
    .GNULIB_TEST_DUP,
    .GNULIB_TEST_DUP2,
    .GNULIB_TEST_ENVIRON,
    .GNULIB_TEST_EXPLICIT_BZERO,
    .GNULIB_TEST_FCHDIR,
    .GNULIB_TEST_FCLOSE,
    .GNULIB_TEST_FCNTL,
    .GNULIB_TEST_FDOPEN,
    .GNULIB_TEST_FDOPENDIR,
    .GNULIB_TEST_FFLUSH,
    .GNULIB_TEST_FGETC,
    .GNULIB_TEST_FGETS,
    .GNULIB_TEST_FOPEN,
    .GNULIB_TEST_FPRINTF,
    .GNULIB_TEST_FPURGE,
    .GNULIB_TEST_FPUTC,
    .GNULIB_TEST_FPUTS,
    .GNULIB_TEST_FREAD,
    .GNULIB_TEST_FREE_POSIX,
    .GNULIB_TEST_FREOPEN,
    .GNULIB_TEST_FREXP,
    .GNULIB_TEST_FREXPL,
    .GNULIB_TEST_FSCANF,
    .GNULIB_TEST_FSEEK,
    .GNULIB_TEST_FSEEKO,
    .GNULIB_TEST_FSTAT,
    .GNULIB_TEST_FSTATAT,
    .GNULIB_TEST_FTELL,
    .GNULIB_TEST_FTELLO,
    .GNULIB_TEST_FTRUNCATE,
    .GNULIB_TEST_FWRITE,
    .GNULIB_TEST_GETC,
    .GNULIB_TEST_GETCHAR,
    .GNULIB_TEST_GETCWD,
    .GNULIB_TEST_GETDTABLESIZE,
    .GNULIB_TEST_GETOPT_POSIX,
    .GNULIB_TEST_GETPAGESIZE,
    .GNULIB_TEST_GETRANDOM,
    .GNULIB_TEST_GETTIMEOFDAY,
    .GNULIB_TEST_IOCTL,
    .GNULIB_TEST_ISWBLANK,
    .GNULIB_TEST_ISWDIGIT,
    .GNULIB_TEST_ISWXDIGIT,
    .GNULIB_TEST_LINK,
    .GNULIB_TEST_LISTEN,
    .GNULIB_TEST_LOCALECONV,
    .GNULIB_TEST_LOCALENAME,
    .GNULIB_TEST_LSEEK,
    .GNULIB_TEST_LSTAT,
    .GNULIB_TEST_MALLOC_POSIX,
    .GNULIB_TEST_MBRTOWC,
    .GNULIB_TEST_MBSINIT,
    .GNULIB_TEST_MBSLEN,
    .GNULIB_TEST_MBSSTR,
    .GNULIB_TEST_MBTOWC,
    .GNULIB_TEST_MEMCHR,
    .GNULIB_TEST_MEMPCPY,
    .GNULIB_TEST_MEMRCHR,
    .GNULIB_TEST_MKDIR,
    .GNULIB_TEST_MKDTEMP,
    .GNULIB_TEST_MKSTEMP,
    .GNULIB_TEST_NANOSLEEP,
    .GNULIB_TEST_NL_LANGINFO,
    .GNULIB_TEST_OPEN,
    .GNULIB_TEST_OPENAT,
    .GNULIB_TEST_OPENDIR,
    .GNULIB_TEST_PERROR,
    .GNULIB_TEST_PIPE,
    .GNULIB_TEST_PIPE2,
    .GNULIB_TEST_POSIX_SPAWN,
    .GNULIB_TEST_POSIX_SPAWNATTR_DESTROY,
    .GNULIB_TEST_POSIX_SPAWNATTR_INIT,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETFLAGS,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETPGROUP,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETSIGMASK,
    .GNULIB_TEST_POSIX_SPAWNP,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_DESTROY,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_INIT,
    .GNULIB_TEST_PRINTF,
    .GNULIB_TEST_PTHREAD_SIGMASK,
    .GNULIB_TEST_PTHREAD_THREAD,
    .GNULIB_TEST_PUTC,
    .GNULIB_TEST_PUTCHAR,
    .GNULIB_TEST_PUTENV,
    .GNULIB_TEST_PUTS,
    .GNULIB_TEST_RAISE,
    .GNULIB_TEST_RAWMEMCHR,
    .GNULIB_TEST_READDIR,
    .GNULIB_TEST_READLINK,
    .GNULIB_TEST_REALLOCARRAY,
    .GNULIB_TEST_REALLOC_POSIX,
    .GNULIB_TEST_REALPATH,
    .GNULIB_TEST_RENAME,
    .GNULIB_TEST_REWINDDIR,
    .GNULIB_TEST_RMDIR,
    .GNULIB_TEST_SCANF,
    .GNULIB_TEST_SCHED_YIELD,
    .GNULIB_TEST_SECURE_GETENV,
    .GNULIB_TEST_SELECT,
    .GNULIB_TEST_SETENV,
    .GNULIB_TEST_SETLOCALE,
    .GNULIB_TEST_SETLOCALE_NULL,
    .GNULIB_TEST_SETSOCKOPT,
    .GNULIB_TEST_SIGACTION,
    .GNULIB_TEST_SIGNBIT,
    .GNULIB_TEST_SIGPROCMASK,
    .GNULIB_TEST_SLEEP,
    .GNULIB_TEST_SNPRINTF,
    .GNULIB_TEST_SOCKET,
    .GNULIB_TEST_STAT,
    .GNULIB_TEST_STPCPY,
    .GNULIB_TEST_STRCHRNUL,
    .GNULIB_TEST_STRDUP,
    .GNULIB_TEST_STRERROR,
    .GNULIB_TEST_STRERROR_R,
    .GNULIB_TEST_STRNDUP,
    .GNULIB_TEST_STRNLEN,
    .GNULIB_TEST_STRSIGNAL,
    .GNULIB_TEST_STRSTR,
    .GNULIB_TEST_STRTOD,
    .GNULIB_TEST_SYMLINK,
    .GNULIB_TEST_UNSETENV,
    .GNULIB_TEST_VASPRINTF,
    .GNULIB_TEST_VFPRINTF,
    .GNULIB_TEST_VPRINTF,
    .GNULIB_TEST_WAITPID,
    .GNULIB_TEST_WCRTOMB,
    .GNULIB_TEST_WCTOB,
    .GNULIB_TEST_WCTOMB,
    .GNULIB_TEST_WCWIDTH,
    .GNULIB_TEST_WRITE,
    .GNULIB_UNISTR_U8_MBTOUCR,
    .GNULIB_UNISTR_U8_UCTOMB,
    .GNULIB_WCHAR_SINGLE_LOCALE,
    .GNULIB_XALLOC,
    .GNULIB_XALLOC_DIE,
    .HAVE_ALLOCA,
    .HAVE_ALLOCA_H,
    .HAVE_ARPA_INET_H,
    .HAVE_BCRYPT_H,
    .HAVE_BP_SYM_H,
    .HAVE_BTOWC,
    .HAVE_BUG_BIG_NANOSLEEP,
    .HAVE_CANONICALIZE_FILE_NAME,
    .HAVE_CATGETS,
    .HAVE_CFLOCALECOPYPREFERREDLANGUAGES,
    .HAVE_CFPREFERENCESCOPYAPPVALUE,
    .HAVE_CLOCK_GETTIME,
    .HAVE_CLOCK_SETTIME,
    .HAVE_CLOSEDIR,
    .HAVE_CLOSE_RANGE,
    .HAVE_CONFSTR,
    .HAVE_COPYSIGNF_IN_LIBC,
    .HAVE_COPYSIGNL_IN_LIBC,
    .HAVE_COPYSIGN_IN_LIBC,
    .HAVE_CRTDEFS_H,
    .HAVE_DCGETTEXT,
    .HAVE_DECL_ALARM,
    .HAVE_DECL_CLEARERR_UNLOCKED,
    .HAVE_DECL_COPYSIGN,
    .HAVE_DECL_COPYSIGNF,
    .HAVE_DECL_COPYSIGNL,
    .HAVE_DECL_DIRFD,
    .HAVE_DECL_ECVT,
    .HAVE_DECL_EXECVPE,
    .HAVE_DECL_FCHDIR,
    .HAVE_DECL_FCLOSEALL,
    .HAVE_DECL_FCVT,
    .HAVE_DECL_FDOPENDIR,
    .HAVE_DECL_FEOF_UNLOCKED,
    .HAVE_DECL_FERROR_UNLOCKED,
    .HAVE_DECL_FFLUSH_UNLOCKED,
    .HAVE_DECL_FGETS_UNLOCKED,
    .HAVE_DECL_FPURGE,
    .HAVE_DECL_FPUTC_UNLOCKED,
    .HAVE_DECL_FPUTS_UNLOCKED,
    .HAVE_DECL_FREAD_UNLOCKED,
    .HAVE_DECL_FSEEKO,
    .HAVE_DECL_FTELLO,
    .HAVE_DECL_FWRITE_UNLOCKED,
    .HAVE_DECL_GCVT,
    .HAVE_DECL_GETCHAR_UNLOCKED,
    .HAVE_DECL_GETCWD,
    .HAVE_DECL_GETC_UNLOCKED,
    .HAVE_DECL_GETDTABLESIZE,
    .HAVE_DECL_INET_PTON,
    .HAVE_DECL_ISBLANK,
    .HAVE_DECL_ISWBLANK,
    .HAVE_DECL_MBRTOWC,
    .HAVE_DECL_MBSINIT,
    .HAVE_DECL_MEMRCHR,
    .HAVE_DECL_POSIX_SPAWN,
    .HAVE_DECL_PROGRAM_INVOCATION_NAME,
    .HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME,
    .HAVE_DECL_PUTCHAR_UNLOCKED,
    .HAVE_DECL_PUTC_UNLOCKED,
    .HAVE_DECL_SETENV,
    .HAVE_DECL_SLEEP,
    .HAVE_DECL_SNPRINTF,
    .HAVE_DECL_STRDUP,
    .HAVE_DECL_STRERROR_R,
    .HAVE_DECL_STRNDUP,
    .HAVE_DECL_STRNLEN,
    .HAVE_DECL_STRSIGNAL,
    .HAVE_DECL_SYS_SIGLIST,
    .HAVE_DECL_TOWLOWER,
    .HAVE_DECL_UNSETENV,
    .HAVE_DECL_WCRTOMB,
    .HAVE_DECL_WCSDUP,
    .HAVE_DECL_WCTOB,
    .HAVE_DECL_WCWIDTH,
    .HAVE_DECL__FSEEKI64,
    .HAVE_DECL__PUTENV,
    .HAVE_DECL__SNPRINTF,
    .HAVE_DECL__SYS_SIGLIST,
    .HAVE_DECL___ARGV,
    .HAVE_DECL___FPENDING,
    .HAVE_DIRENT_H,
    .HAVE_DIRFD,
    .HAVE_DUPLOCALE,
    .HAVE_ENVIRON_DECL,
    .HAVE_EXPLICIT_BZERO,
    .HAVE_EXPLICIT_MEMSET,
    .HAVE_FACCESSAT,
    .HAVE_FAKE_LOCALES,
    .HAVE_FCHDIR,
    .HAVE_FCNTL,
    .HAVE_FDOPENDIR,
    .HAVE_FEATURES_H,
    .HAVE_FPURGE,
    .HAVE_FREELOCALE,
    .HAVE_FREE_POSIX,
    .HAVE_FREXPL_IN_LIBC,
    .HAVE_FREXP_IN_LIBC,
    .HAVE_FSEEKO,
    .HAVE_FSTATAT,
    .HAVE_FTRUNCATE,
    .HAVE_GETCWD,
    .HAVE_GETCWD_SHORTER,
    .HAVE_GETDTABLESIZE,
    .HAVE_GETEGID,
    .HAVE_GETEUID,
    .HAVE_GETEXECNAME,
    .HAVE_GETGID,
    .HAVE_GETLOCALENAME_L,
    .HAVE_GETOPT_H,
    .HAVE_GETOPT_LONG_ONLY,
    .HAVE_GETPAGESIZE,
    .HAVE_GETPROGNAME,
    .HAVE_GETRANDOM,
    .HAVE_GETRLIMIT,
    .HAVE_GETTEXT,
    .HAVE_GETTIMEOFDAY,
    .HAVE_GETUID,
    .HAVE_GOOD_USELOCALE,
    .HAVE_ICONV,
    .HAVE_ICONV_H,
    .HAVE_INET_PTON,
    .HAVE_INLINE,
    .HAVE_INTMAX_T,
    .HAVE_INTTYPES_H,
    .HAVE_INTTYPES_H_WITH_UINTMAX,
    .HAVE_IOCTL,
    .HAVE_IPV4,
    .HAVE_IPV6,
    .HAVE_ISBLANK,
    .HAVE_ISNAND_IN_LIBC,
    .HAVE_ISNANF_IN_LIBC,
    .HAVE_ISNANL_IN_LIBC,
    .HAVE_ISSETUGID,
    .HAVE_ISWBLANK,
    .HAVE_ISWCNTRL,
    .HAVE_ISWCTYPE,
    .HAVE_LANGINFO_CODESET,
    .HAVE_LANGINFO_H,
    .HAVE_LC_MESSAGES,
    .HAVE_LDEXPL_IN_LIBC,
    .HAVE_LDEXP_IN_LIBC,
    .HAVE_LIBINTL_H,
    .HAVE_LIBSIGSEGV,
    .HAVE_LIB_BCRYPT,
    .HAVE_LIMITS_H,
    .HAVE_LINK,
    .HAVE_LONG_LONG_INT,
    .HAVE_LSTAT,
    .HAVE_MALLOC_H,
    .HAVE_MALLOC_POSIX,
    .HAVE_MAP_ANONYMOUS,
    .HAVE_MATH_H,
    .HAVE_MBRTOWC,
    .HAVE_MBSINIT,
    .HAVE_MBSLEN,
    .HAVE_MBSTATE_T,
    .HAVE_MBTOWC,
    .HAVE_MEMPCPY,
    .HAVE_MEMRCHR,
    .HAVE_MEMSET_S,
    .HAVE_MINIMALLY_WORKING_GETCWD,
    .HAVE_MINIX_CONFIG_H,
    .HAVE_MINMAX_IN_LIMITS_H,
    .HAVE_MINMAX_IN_SYS_PARAM_H,
    .HAVE_MKDTEMP,
    .HAVE_MKSTEMP,
    .HAVE_MPROTECT,
    .HAVE_MQUERY,
    .HAVE_MSVC_INVALID_PARAMETER_HANDLER,
    .HAVE_NAMELESS_LOCALES,
    .HAVE_NETDB_H,
    .HAVE_NETINET_IN_H,
    .HAVE_NEWLOCALE,
    .HAVE_NL_LANGINFO,
    .HAVE_OBSTACK,
    .HAVE_OPENAT,
    .HAVE_OPENDIR,
    .HAVE_OS_H,
    .HAVE_PARTLY_WORKING_GETCWD,
    .HAVE_PATHS_H,
    .HAVE_PIPE,
    .HAVE_PIPE2,
    .HAVE_POSIX_SPAWN,
    .HAVE_POSIX_SPAWNATTR_T,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR_NP,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_T,
    .HAVE_PSTAT_GETPROCVM,
    .HAVE_PTHREAD_API,
    .HAVE_PTHREAD_ATFORK,
    .HAVE_PTHREAD_H,
    .HAVE_PTHREAD_MUTEX_RECURSIVE,
    .HAVE_PTHREAD_RWLOCK,
    .HAVE_PTHREAD_RWLOCK_RDLOCK_PREFER_WRITER,
    .HAVE_PTHREAD_SIGMASK,
    .HAVE_PTHREAD_SPINLOCK_T,
    .HAVE_PTHREAD_T,
    .HAVE_RAISE,
    .HAVE_RAWMEMCHR,
    .HAVE_READDIR,
    .HAVE_READLINK,
    .HAVE_REALLOCARRAY,
    .HAVE_REALPATH,
    .HAVE_REWINDDIR,
    .HAVE_SAME_LONG_DOUBLE_AS_DOUBLE,
    .HAVE_SA_FAMILY_T,
    .HAVE_SCHED_H,
    .HAVE_SCHED_SETPARAM,
    .HAVE_SCHED_SETSCHEDULER,
    .HAVE_SDKDDKVER_H,
    .HAVE_SEARCH_H,
    .HAVE_SECURE_GETENV,
    .HAVE_SEMAPHORE_H,
    .HAVE_SETDTABLESIZE,
    .HAVE_SETEGID,
    .HAVE_SETENV,
    .HAVE_SETEUID,
    .HAVE_SETRLIMIT,
    .HAVE_SHUTDOWN,
    .HAVE_SIGACTION,
    .HAVE_SIGALTSTACK,
    .HAVE_SIGINFO_T,
    .HAVE_SIGINTERRUPT,
    .HAVE_SIGNED_SIG_ATOMIC_T,
    .HAVE_SIGNED_WCHAR_T,
    .HAVE_SIGNED_WINT_T,
    .HAVE_SIGSET_T,
    .HAVE_SIG_ATOMIC_T,
    .HAVE_SLEEP,
    .HAVE_SNPRINTF,
    .HAVE_SNPRINTF_RETVAL_C99,
    .HAVE_SNPRINTF_TRUNCATION_C99,
    .HAVE_SOLARIS114_LOCALES,
    .HAVE_SPAWN_H,
    .HAVE_STDINT_H,
    .HAVE_STDINT_H_WITH_UINTMAX,
    .HAVE_STDIO_EXT_H,
    .HAVE_STDIO_H,
    .HAVE_STDLIB_H,
    .HAVE_STPCPY,
    .HAVE_STRCHRNUL,
    .HAVE_STRERROR_R,
    .HAVE_STRINGS_H,
    .HAVE_STRING_H,
    .HAVE_STRNDUP,
    .HAVE_STRNLEN,
    .HAVE_STRSIGNAL,
    .HAVE_STRUCT_LCONV_DECIMAL_POINT,
    .HAVE_STRUCT_SIGACTION_SA_SIGACTION,
    .HAVE_STRUCT_SOCKADDR_STORAGE,
    .HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY,
    .HAVE_STRUCT_STAT_ST_ATIMENSEC,
    .HAVE_STRUCT_STAT_ST_ATIMESPEC_TV_NSEC,
    .HAVE_STRUCT_STAT_ST_ATIM_ST__TIM_TV_NSEC,
    .HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC,
    .HAVE_STRUCT_STAT_ST_BIRTHTIMENSEC,
    .HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC,
    .HAVE_STRUCT_STAT_ST_BIRTHTIM_TV_NSEC,
    .HAVE_SYMLINK,
    .HAVE_SYS_BITYPES_H,
    .HAVE_SYS_CDEFS_H,
    .HAVE_SYS_INTTYPES_H,
    .HAVE_SYS_IOCTL_H,
    .HAVE_SYS_MMAN_H,
    .HAVE_SYS_PARAM_H,
    .HAVE_SYS_RANDOM_H,
    .HAVE_SYS_SELECT_H,
    .HAVE_SYS_SINGLE_THREADED_H,
    .HAVE_SYS_SOCKET_H,
    .HAVE_SYS_STAT_H,
    .HAVE_SYS_TIME_H,
    .HAVE_SYS_TYPES_H,
    .HAVE_SYS_UIO_H,
    .HAVE_SYS_WAIT_H,
    .HAVE_THRD_CREATE,
    .HAVE_THREADS_H,
    .HAVE_TOWLOWER,
    .HAVE_TSEARCH,
    .HAVE_UNISTD_H,
    .HAVE_UNSETENV,
    .HAVE_UNSIGNED_LONG_LONG_INT,
    .HAVE_USELOCALE,
    .HAVE_VAR___PROGNAME,
    .HAVE_VASNPRINTF,
    .HAVE_VASPRINTF,
    .HAVE_VFORK,
    .HAVE_VISIBILITY,
    .HAVE_WAITID,
    .HAVE_WCHAR_H,
    .HAVE_WCHAR_T,
    .HAVE_WCRTOMB,
    .HAVE_WCSLEN,
    .HAVE_WCSNLEN,
    .HAVE_WCTOB,
    .HAVE_WCTYPE_H,
    .HAVE_WCWIDTH,
    .HAVE_WEAK_SYMBOLS,
    .HAVE_WINSOCK2_H,
    .HAVE_WINT_T,
    .HAVE_WORKING_FSTATAT_ZERO_FLAG,
    .HAVE_WORKING_O_NOATIME,
    .HAVE_WORKING_O_NOFOLLOW,
    .HAVE_WORKING_SIGALTSTACK,
    .HAVE_WORKING_USELOCALE,
    .HAVE_WS2TCPIP_H,
    .HAVE_XLOCALE_H,
    .HAVE__BOOL,
    .HAVE__CHSIZE,
    .HAVE__FSEEKI64,
    .HAVE__FTELLI64,
    .HAVE__SET_INVALID_PARAMETER_HANDLER,
    .HAVE___BUILTIN_EXPECT,
    .HAVE___FPURGE,
    .HAVE___FREADAHEAD,
    .HAVE___FREADING,
    .HAVE___INLINE,
    .HAVE___SECURE_GETENV,
    .HAVE___XPG_STRERROR_R,
    .ICONV_CONST,
    .ICONV_FLAVOR,
    .LDBL_EXPBIT0_BIT,
    .LDBL_EXPBIT0_WORD,
    .LDBL_SIGNBIT_BIT,
    .LDBL_SIGNBIT_WORD,
    .LOCALENAME_ENHANCE_LOCALE_FUNCS,
    .LSEEK_PIPE_BROKEN,
    .LSTAT_FOLLOWS_SLASHED_SYMLINK,
    .MALLOC_0_IS_NONNULL,
    .MAP_ANONYMOUS,
    .MBRTOWC_EMPTY_INPUT_BUG,
    .MBRTOWC_IN_C_LOCALE_MAYBE_EILSEQ,
    .MBRTOWC_NULL_ARG1_BUG,
    .MBRTOWC_NULL_ARG2_BUG,
    .MBRTOWC_NUL_RETVAL_BUG,
    .MBRTOWC_RETVAL_BUG,
    .MBRTOWC_STORES_INCOMPLETE_BUG,
    .MUSL_LIBC,
    .NDEBUG,
    .NEED_PRINTF_DIRECTIVE_A,
    .NEED_PRINTF_DIRECTIVE_F,
    .NEED_PRINTF_DIRECTIVE_LS,
    .NEED_PRINTF_DOUBLE,
    .NEED_PRINTF_ENOMEM,
    .NEED_PRINTF_FLAG_GROUPING,
    .NEED_PRINTF_FLAG_LEFTADJUST,
    .NEED_PRINTF_FLAG_ZERO,
    .NEED_PRINTF_INFINITE_DOUBLE,
    .NEED_PRINTF_INFINITE_LONG_DOUBLE,
    .NEED_PRINTF_LONG_DOUBLE,
    .NEED_PRINTF_UNBOUNDED_PRECISION,
    .NEED_SETLOCALE_IMPROVED,
    .NEED_SETLOCALE_MTSAFE,
    .NL_LANGINFO_MTSAFE,
    .OPEN_TRAILING_SLASH_BUG,
    .PACKAGE,
    .PACKAGE_BUGREPORT,
    .PACKAGE_NAME,
    .PACKAGE_PACKAGER,
    .PACKAGE_PACKAGER_BUG_REPORTS,
    .PACKAGE_PACKAGER_VERSION,
    .PACKAGE_STRING,
    .PACKAGE_TARNAME,
    .PACKAGE_URL,
    .PACKAGE_VERSION,
    .PROMOTED_MODE_T,
    .PTHREAD_CREATE_IS_INLINE,
    .PTHREAD_IN_USE_DETECTION_HARD,
    .PTHREAD_SIGMASK_FAILS_WITH_ERRNO,
    .PTHREAD_SIGMASK_INEFFECTIVE,
    .PTHREAD_SIGMASK_UNBLOCK_BUG,
    .PTRDIFF_T_SUFFIX,
    .READLINK_TRAILING_SLASH_BUG,
    .READLINK_TRUNCATE_BUG,
    .RENAME_DEST_EXISTS_BUG,
    .RENAME_HARD_LINK_BUG,
    .RENAME_OPEN_FILE_WORKS,
    .RENAME_TRAILING_SLASH_DEST_BUG,
    .RENAME_TRAILING_SLASH_SOURCE_BUG,
    .REPLACE_DIRFD,
    .REPLACE_FCHDIR,
    .REPLACE_FUNC_STAT_FILE,
    .REPLACE_NL_LANGINFO,
    .REPLACE_OPEN_DIRECTORY,
    .REPLACE_POSIX_SPAWN,
    .REPLACE_STRERROR_0,
    .REPLACE_VASNPRINTF,
    .SETLOCALE_NULL_ALL_MTSAFE,
    .SETLOCALE_NULL_ONE_MTSAFE,
    .SIGALTSTACK_SS_REVERSED,
    .SIGNAL_SAFE_LIST,
    .SIG_ATOMIC_T_SUFFIX,
    .SIZE_MAX,
    .SIZE_T_SUFFIX,
    .SOLARIS11,
    .STACK_DIRECTION,
    .STAT_MACROS_BROKEN,
    .STDC_HEADERS,
    .STRERROR_R_CHAR_P,
    .SYSCMD_SHELL,
    .TYPEOF_STRUCT_STAT_ST_ATIM_IS_STRUCT_TIMESPEC,
    .USER_LABEL_PREFIX,
    .USE_ISOC_AND_POSIX_THREADS,
    .USE_ISOC_THREADS,
    .USE_POSIX_THREADS,
    .USE_POSIX_THREADS_WEAK,
    .USE_UNLOCKED_IO,
    .USE_WINDOWS_THREADS,
    .VERSION,
    .VOID_UNSETENV,
    .WCHAR_T_SUFFIX,
    .WCRTOMB_C_LOCALE_BUG,
    .WCRTOMB_RETVAL_BUG,
    .WINDOWS_SOCKETS,
    .WINT_T_SUFFIX,
    .WITH_DMALLOC,
    .WORDS_BIGENDIAN,
    ._ALL_SOURCE,
    ._DARWIN_C_SOURCE,
    ._FILE_OFFSET_BITS,
    ._GNU_SOURCE,
    ._HPUX_ALT_XOPEN_SOCKET_API,
    ._ISOC11_SOURCE,
    ._LARGEFILE_SOURCE,
    ._LARGE_FILES,
    ._LCONV_C99,
    ._MINIX,
    ._NETBSD_SOURCE,
    ._OPENBSD_SOURCE,
    ._POSIX_1_SOURCE,
    ._POSIX_PII_SOCKET,
    ._POSIX_PTHREAD_SEMANTICS,
    ._POSIX_SOURCE,
    ._REGEX_INCLUDE_LIMITS_H,
    ._REGEX_LARGE_OFFSETS,
    ._TANDEM_SOURCE,
    ._USE_STD_STAT,
    ._XOPEN_SOURCE,
    .__EXTENSIONS__,
    .__GETOPT_PREFIX,
    .__STDC_CONSTANT_MACROS,
    .__STDC_LIMIT_MACROS,
    .__STDC_WANT_IEC_60559_ATTRIBS_EXT__,
    .__STDC_WANT_IEC_60559_BFP_EXT__,
    .__STDC_WANT_IEC_60559_DFP_EXT__,
    .__STDC_WANT_IEC_60559_FUNCS_EXT__,
    .__STDC_WANT_IEC_60559_TYPES_EXT__,
    .__STDC_WANT_LIB_EXT2__,
    .__STDC_WANT_MATH_SPEC_FUNCS__,
    .__USE_MINGW_ANSI_STDIO,
    .__alpha__,
    .__arm64__,
    .__arm64_ilp32__,
    .__arm__,
    .__armhf__,
    .__hppa64__,
    .__hppa__,
    .__i386__,
    .__ia64__,
    .__ia64_ilp32__,
    .__m68k__,
    .__mips64__,
    .__mips__,
    .__mipsn32__,
    .__powerpc64__,
    .__powerpc64_elfv2__,
    .__powerpc__,
    .__riscv32__,
    .__riscv32_ilp32__,
    .__riscv32_ilp32d__,
    .__riscv32_ilp32f__,
    .__riscv64__,
    .__riscv64_ilp32__,
    .__riscv64_ilp32d__,
    .__riscv64_ilp32f__,
    .__riscv64_lp64__,
    .__riscv64_lp64d__,
    .__riscv64_lp64f__,
    .__s390__,
    .__s390x__,
    .__sh__,
    .__sparc64__,
    .__sparc__,
    .__x86_64__,
    .__x86_64_x32__,
    .eaccess,
    .gid_t,
    .intmax_t,
    .mbstate_t,
    .mode_t,
    .nlink_t,
    .off_t,
    .pid_t,
    .ptrdiff_t,
    .re_comp,
    .re_compile_fastmap,
    .re_compile_pattern,
    .re_exec,
    .re_match,
    .re_match_2,
    .re_search,
    .re_search_2,
    .re_set_registers,
    .re_set_syntax,
    .re_syntax_options,
    .regcomp,
    .regerror,
    .regexec,
    .regfree,
    .restrict,
    .sig_atomic_t,
    .size_t,
    .socklen_t,
    .ssize_t,
    .stack_t,
    .uid_t,
    .va_copy,
};

const dirent_h_values = &[_]ConfigValueTag{
    .GNULIB_ALPHASORT,
    .GNULIB_CLOSEDIR,
    .GNULIB_DIRFD,
    .GNULIB_FDOPENDIR,
    .GNULIB_OPENDIR,
    .GNULIB_READDIR,
    .GNULIB_REWINDDIR,
    .GNULIB_SCANDIR,
    .GUARD_PREFIX,
    .HAVE_ALPHASORT,
    .HAVE_CLOSEDIR,
    .HAVE_DECL_DIRFD,
    .HAVE_DECL_FDOPENDIR,
    .HAVE_DIRENT_H,
    .HAVE_FDOPENDIR,
    .HAVE_OPENDIR,
    .HAVE_READDIR,
    .HAVE_REWINDDIR,
    .HAVE_SCANDIR,
    .INCLUDE_NEXT,
    .NEXT_DIRENT_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_CLOSEDIR,
    .REPLACE_DIRFD,
    .REPLACE_FDOPENDIR,
    .REPLACE_OPENDIR,
};

const fcntl_h_values = &[_]ConfigValueTag{
    .GNULIB_CREAT,
    .GNULIB_FCNTL,
    .GNULIB_MDA_CREAT,
    .GNULIB_MDA_OPEN,
    .GNULIB_NONBLOCKING,
    .GNULIB_OPEN,
    .GNULIB_OPENAT,
    .GUARD_PREFIX,
    .HAVE_FCNTL,
    .HAVE_OPENAT,
    .INCLUDE_NEXT,
    .NEXT_FCNTL_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_CREAT,
    .REPLACE_FCNTL,
    .REPLACE_OPEN,
    .REPLACE_OPENAT,
};

const iconv_h_values = &[_]ConfigValueTag{
    .GNULIB_ICONV,
    .GUARD_PREFIX,
    .ICONV_CONST,
    .INCLUDE_NEXT,
    .NEXT_ICONV_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_ICONV,
    .REPLACE_ICONV_OPEN,
    .REPLACE_ICONV_UTF,
};
