const std = @import("std");
const ConfigHeaderCustom = @import("ConfigHeaderCustom.zig");
const InsertHeaderSnippets = @import("InsertHeaderSnippets.zig");

// Importing ZON without specifying a result type might be supported in the future. Then we could
// make the following code less verbose more robust.
const Schema = struct {
    name: []const u8,
    version: []const u8,
    dependencies: struct {
        upstream: struct { url: []const u8, hash: []const u8 },
    },
    paths: []const []const u8,
};
const zon: Schema = @import("build.zig.zon");
const version = zon.version;

pub fn build(b: *std.Build) void {
    const check = b.step("check", "Check if GNU M4 compiles");

    const include = b.addWriteFiles();
    check.dependOn(&include.step);
    b.installDirectory(.{
        .source_dir = include.getDirectory(),
        .install_dir = .header,
        .install_subdir = "",
    });

    const upstream = b.dependency("upstream", .{});

    for (config_headers) |config_header| {
        const style: ConfigHeaderCustom.Style = switch (config_header.style) {
            .autoconf_undef => |p| .{ .autoconf_undef = upstream.path(p) },
            .autoconf_at => |p| .{ .autoconf_at = upstream.path(p) },
            .blank => .blank,
        };
        configureHeader(
            upstream,
            include,
            config_header.sub_path,
            style,
            config_header.values,
            config_header.snippets,
        );
    }
}

fn configureHeader(
    dependency: *std.Build.Dependency,
    write_file: *std.Build.Step.WriteFile,
    sub_path: []const u8,
    style: ConfigHeaderCustom.Style,
    values: Values,
    snippet_tags: []const SnippetTag,
) void {
    const b = write_file.step.owner;

    const config_header = addConfigHeaderCustom(
        b,
        .{ .style = style, .include_path = sub_path },
        values,
    );
    // This should be fixed in ConfigHeader, see:
    // https://github.com/ziglang/zig/issues/16208
    if (style.getPath()) |lp| lp.addStepDependencies(&config_header.step);

    const source = if (snippet_tags.len == 0)
        config_header.getOutput()
    else blk: {
        for (snippet_tags, 0..) |s, i| {
            for (snippet_tags[i + 1 ..]) |t| {
                if (s == t) @panic("Duplicate snippet.");
            }
        }

        const max_count_snippets = @typeInfo(SnippetTag).@"enum".fields.len;
        var snippets: [max_count_snippets]InsertHeaderSnippets.Snippet = undefined;

        for (snippet_tags, snippets[0..snippet_tags.len]) |tag, *snippet| {
            snippet.* = switch (tag) {
                ._GL_FUNCDECL_RPL => .{
                    .file = dependency.path("lib/c++defs.h"),
                    .line_pattern = "definitions of _GL_FUNCDECL_RPL",
                },
                ._Noreturn => .{
                    .file = dependency.path("lib/_Noreturn.h"),
                    .line_pattern = "definition of _Noreturn",
                },
                ._GL_ARG_NONNULL => .{
                    .file = dependency.path("lib/arg-nonnull.h"),
                    .line_pattern = "definition of _GL_ARG_NONNULL",
                },
                ._GL_WARN_ON_USE => .{
                    .file = dependency.path("lib/warn-on-use.h"),
                    .line_pattern = "definition of _GL_WARN_ON_USE",
                },
            };
        }

        const header = InsertHeaderSnippets.create(b, .{
            .source_file = config_header.getOutput(),
            .snippets = snippets[0..snippet_tags.len],
        });
        break :blk header.getOutput();
    };

    _ = write_file.addCopyFile(source, sub_path);
}

const SnippetTag = enum {
    _GL_FUNCDECL_RPL,
    _Noreturn,
    _GL_ARG_NONNULL,
    _GL_WARN_ON_USE,
};

fn addConfigHeaderCustom(
    b: *std.Build,
    options: ConfigHeaderCustom.Options,
    values: Values,
) *ConfigHeaderCustom {
    var options_copy = options;
    if (options_copy.first_ret_addr == null)
        options_copy.first_ret_addr = @returnAddress();

    const config_header = ConfigHeaderCustom.create(b, options_copy);
    switch (values) {
        .config => config_header.addValues(config_h_values),
        .gnulib => |tags| {
            var used = [_]bool{false} ** gnulib_values_fields.len;
            for (tags) |tag| {
                used[@intFromEnum(tag)] = true;
            }
            @setEvalBranchQuota(gnulib_values_fields.len);
            inline for (gnulib_values_fields, used) |field, u| {
                if (u) config_header.addValue(
                    field.name,
                    field.type,
                    @field(gnulib_values, field.name),
                );
            }
        },
    }
    return config_header;
}

const Values = union(enum) {
    config,
    gnulib: []const GnulibValueTag,
};

const GnulibValueTag = blk: {
    var enum_fields: [gnulib_values_fields.len]std.builtin.Type.EnumField = undefined;
    @setEvalBranchQuota(gnulib_values_fields.len);
    for (gnulib_values_fields, &enum_fields, 0..) |struct_field, *enum_field, i| {
        enum_field.* = .{ .name = struct_field.name, .value = i };
    }
    break :blk @Type(.{
        .@"enum" = .{
            .tag_type = u32,
            .fields = &enum_fields,
            .decls = &.{},
            .is_exhaustive = true,
        },
    });
};

const Header = struct {
    sub_path: []const u8,
    style: Style,
    values: Values,
    snippets: []const SnippetTag,

    pub const Style = union(enum) {
        autoconf_undef: []const u8,
        autoconf_at: []const u8,
        blank,
    };
};

const config_headers = [_]Header{
    .{
        .sub_path = "config.h",
        .style = .{ .autoconf_undef = "lib/config.hin" },
        .values = .config,
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "alloca.h",
        .style = .{ .autoconf_at = "lib/alloca.in.h" },
        .values = .{ .gnulib = &[_]GnulibValueTag{.HAVE_ALLOCA_H} },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "configmake.h",
        .style = .blank,
        // The macros defined in `configmake.h` are unused since we disable native language support.
        .values = .{ .gnulib = &[_]GnulibValueTag{} },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "dirent.h",
        .style = .{ .autoconf_at = "lib/dirent.in.h" },
        .values = .{ .gnulib = dirent_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "fcntl.h",
        .style = .{ .autoconf_at = "lib/fcntl.in.h" },
        .values = .{ .gnulib = fcntl_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "iconv.h",
        .style = .{ .autoconf_at = "lib/iconv.in.h" },
        .values = .{ .gnulib = iconv_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "inttypes.h",
        .style = .{ .autoconf_at = "lib/inttypes.in.h" },
        .values = .{ .gnulib = inttypes_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "langinfo.h",
        .style = .{ .autoconf_at = "lib/langinfo.in.h" },
        .values = .{ .gnulib = langinfo_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "limits.h",
        .style = .{ .autoconf_at = "lib/limits.in.h" },
        .values = .{ .gnulib = limits_h_values },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "locale.h",
        .style = .{ .autoconf_at = "lib/locale.in.h" },
        .values = .{ .gnulib = locale_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "math.h",
        .style = .{ .autoconf_at = "lib/math.in.h" },
        .values = .{ .gnulib = math_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "sched.h",
        .style = .{ .autoconf_at = "lib/sched.in.h" },
        .values = .{ .gnulib = sched_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "signal.h",
        .style = .{ .autoconf_at = "lib/signal.in.h" },
        .values = .{ .gnulib = signal_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "sigsegv.h",
        .style = .{ .autoconf_at = "lib/sigsegv.in.h" },
        .values = .{ .gnulib = &[_]GnulibValueTag{} },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "spawn.h",
        .style = .{ .autoconf_at = "lib/spawn.in.h" },
        .values = .{ .gnulib = spawn_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "stdio.h",
        .style = .{ .autoconf_at = "lib/stdio.in.h" },
        .values = .{ .gnulib = stdio_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "stdlib.h",
        .style = .{ .autoconf_at = "lib/stdlib.in.h" },
        .values = .{ .gnulib = stdlib_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._Noreturn, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "string.h",
        .style = .{ .autoconf_at = "lib/string.in.h" },
        .values = .{ .gnulib = string_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "sys/random.h",
        .style = .{ .autoconf_at = "lib/sys_random.in.h" },
        .values = .{ .gnulib = sys_random_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "sys/stat.h",
        .style = .{ .autoconf_at = "lib/sys_stat.in.h" },
        .values = .{ .gnulib = sys_stat_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "sys/types.h",
        .style = .{ .autoconf_at = "lib/sys_types.in.h" },
        .values = .{ .gnulib = sys_types_h_values },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "sys/wait.h",
        .style = .{ .autoconf_at = "lib/sys_wait.in.h" },
        .values = .{ .gnulib = sys_wait_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "time.h",
        .style = .{ .autoconf_at = "lib/time.in.h" },
        .values = .{ .gnulib = time_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "unistd.h",
        .style = .{ .autoconf_at = "lib/unistd.in.h" },
        .values = .{ .gnulib = unistd_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "unistr.h",
        .style = .{ .autoconf_at = "lib/unistr.in.h" },
        .values = .{ .gnulib = &[_]GnulibValueTag{} },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "unitypes.h",
        .style = .{ .autoconf_at = "lib/unitypes.in.h" },
        .values = .{ .gnulib = &[_]GnulibValueTag{} },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "uniwidth.h",
        .style = .{ .autoconf_at = "lib/uniwidth.in.h" },
        .values = .{ .gnulib = &[_]GnulibValueTag{} },
        .snippets = &[_]SnippetTag{},
    },
    .{
        .sub_path = "wchar.h",
        .style = .{ .autoconf_at = "lib/wchar.in.h" },
        .values = .{ .gnulib = wchar_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_ARG_NONNULL, ._GL_WARN_ON_USE },
    },
    .{
        .sub_path = "wctype.h",
        .style = .{ .autoconf_at = "lib/wctype.in.h" },
        .values = .{ .gnulib = wctype_h_values },
        .snippets = &[_]SnippetTag{ ._GL_FUNCDECL_RPL, ._GL_WARN_ON_USE },
    },
};

const config_h_values = .{
    .@"inline" = null,
    .AC_APPLE_UNIVERSAL_BUILD = null,
    .BITSIZEOF_PTRDIFF_T = null,
    .BITSIZEOF_SIG_ATOMIC_T = null,
    .BITSIZEOF_SIZE_T = null,
    .BITSIZEOF_WCHAR_T = null,
    .BITSIZEOF_WINT_T = null,
    .CHECK_PRINTF_SAFE = 1,
    .C_ALLOCA = null,
    .DBL_EXPBIT0_BIT = 20,
    .DBL_EXPBIT0_WORD = 1,
    .DBL_SIGNBIT_BIT = null,
    .DBL_SIGNBIT_WORD = null,
    .DIR_FD_MEMBER_NAME = null,
    .DOUBLE_SLASH_IS_DISTINCT_ROOT = null,
    .D_INO_IN_DIRENT = 1,
    .ENABLE_CHANGEWORD = null,
    .ENABLE_NLS = null,
    .FCNTL_DUPFD_BUGGY = null,
    .FLEXIBLE_ARRAY_MEMBER = {},
    .FLT_EXPBIT0_BIT = 23,
    .FLT_EXPBIT0_WORD = 0,
    .FLT_SIGNBIT_BIT = null,
    .FLT_SIGNBIT_WORD = null,
    .FOPEN_TRAILING_SLASH_BUG = null,
    .FTELLO_BROKEN_AFTER_SWITCHING_FROM_READ_TO_WRITE = null,
    .FTELLO_BROKEN_AFTER_UNGETC = null,
    .FUNC_FFLUSH_STDIN = 0,
    .FUNC_MKDIR_DOT_BUG = null,
    .FUNC_NL_LANGINFO_YESEXPR_WORKS = 1,
    .FUNC_REALPATH_NEARLY_WORKS = null,
    .FUNC_REALPATH_WORKS = 1,
    .FUNC_UNGETC_BROKEN = null,
    .GETTIMEOFDAY_TIMEZONE = .void,
    .GNULIB_CANONICALIZE = 1,
    .GNULIB_CANONICALIZE_LGPL = 1,
    .GNULIB_CLOSE_STREAM = 1,
    .GNULIB_DIRNAME = 1,
    .GNULIB_FDOPENDIR = 1,
    .GNULIB_FD_SAFER_FLAG = 1,
    .GNULIB_FFLUSH = 1,
    .GNULIB_FILENAMECAT = 1,
    .GNULIB_FOPEN_GNU = 1,
    .GNULIB_FOPEN_SAFER = 1,
    .GNULIB_FSCANF = 1,
    .GNULIB_GETCWD = 1,
    .GNULIB_ISBLANK = .IN_M4_GNULIB_TESTS,
    .GNULIB_LOCK = 1,
    .GNULIB_MBRTOWC_SINGLE_THREAD = 1,
    .GNULIB_MSVC_NOTHROW = 1,
    .GNULIB_OPENAT = 1,
    .GNULIB_PIPE2_SAFER = 1,
    .GNULIB_PRINTF_ATTRIBUTE_FLAVOR_GNU = null,
    .GNULIB_REALLOCARRAY = 1,
    .GNULIB_REGEX_SINGLE_THREAD = 1,
    .GNULIB_SCANF = 1,
    .GNULIB_SIGPIPE = 1,
    .GNULIB_SNPRINTF = 1,
    .GNULIB_STDIO_SINGLE_THREAD = 1,
    .GNULIB_STRERROR = 1,
    .GNULIB_STRERROR_R_POSIX = .IN_M4_GNULIB_TESTS,
    .GNULIB_TEMPNAME = 1,
    .GNULIB_TEST_ACCEPT = 1,
    .GNULIB_TEST_ACCESS = 1,
    .GNULIB_TEST_BIND = 1,
    .GNULIB_TEST_BTOWC = 1,
    .GNULIB_TEST_CALLOC_POSIX = 1,
    .GNULIB_TEST_CANONICALIZE = 1,
    .GNULIB_TEST_CANONICALIZE_FILE_NAME = 1,
    .GNULIB_TEST_CHDIR = 1,
    .GNULIB_TEST_CLOEXEC = 1,
    .GNULIB_TEST_CLOSE = 1,
    .GNULIB_TEST_CLOSEDIR = 1,
    .GNULIB_TEST_CONNECT = 1,
    .GNULIB_TEST_CREAT = 1,
    .GNULIB_TEST_DIRFD = 1,
    .GNULIB_TEST_DUP = 1,
    .GNULIB_TEST_DUP2 = 1,
    .GNULIB_TEST_ENVIRON = 1,
    .GNULIB_TEST_EXPLICIT_BZERO = 1,
    .GNULIB_TEST_FCHDIR = 1,
    .GNULIB_TEST_FCLOSE = 1,
    .GNULIB_TEST_FCNTL = 1,
    .GNULIB_TEST_FDOPEN = 1,
    .GNULIB_TEST_FDOPENDIR = 1,
    .GNULIB_TEST_FFLUSH = 1,
    .GNULIB_TEST_FGETC = 1,
    .GNULIB_TEST_FGETS = 1,
    .GNULIB_TEST_FOPEN = 1,
    .GNULIB_TEST_FPRINTF = 1,
    .GNULIB_TEST_FPURGE = 1,
    .GNULIB_TEST_FPUTC = 1,
    .GNULIB_TEST_FPUTS = 1,
    .GNULIB_TEST_FREAD = 1,
    .GNULIB_TEST_FREE_POSIX = 1,
    .GNULIB_TEST_FREOPEN = 1,
    .GNULIB_TEST_FREXP = 1,
    .GNULIB_TEST_FREXPL = 1,
    .GNULIB_TEST_FSCANF = 1,
    .GNULIB_TEST_FSEEK = 1,
    .GNULIB_TEST_FSEEKO = 1,
    .GNULIB_TEST_FSTAT = 1,
    .GNULIB_TEST_FSTATAT = 1,
    .GNULIB_TEST_FTELL = 1,
    .GNULIB_TEST_FTELLO = 1,
    .GNULIB_TEST_FTRUNCATE = 1,
    .GNULIB_TEST_FWRITE = 1,
    .GNULIB_TEST_GETC = 1,
    .GNULIB_TEST_GETCHAR = 1,
    .GNULIB_TEST_GETCWD = 1,
    .GNULIB_TEST_GETDTABLESIZE = 1,
    .GNULIB_TEST_GETOPT_POSIX = 1,
    .GNULIB_TEST_GETPAGESIZE = 1,
    .GNULIB_TEST_GETRANDOM = 1,
    .GNULIB_TEST_GETTIMEOFDAY = 1,
    .GNULIB_TEST_IOCTL = 1,
    .GNULIB_TEST_ISWBLANK = 1,
    .GNULIB_TEST_ISWDIGIT = 1,
    .GNULIB_TEST_ISWXDIGIT = 1,
    .GNULIB_TEST_LINK = 1,
    .GNULIB_TEST_LISTEN = 1,
    .GNULIB_TEST_LOCALECONV = 1,
    .GNULIB_TEST_LOCALENAME = 1,
    .GNULIB_TEST_LSEEK = 1,
    .GNULIB_TEST_LSTAT = 1,
    .GNULIB_TEST_MALLOC_POSIX = 1,
    .GNULIB_TEST_MBRTOWC = 1,
    .GNULIB_TEST_MBSINIT = 1,
    .GNULIB_TEST_MBSLEN = 1,
    .GNULIB_TEST_MBSSTR = 1,
    .GNULIB_TEST_MBTOWC = 1,
    .GNULIB_TEST_MEMCHR = 1,
    .GNULIB_TEST_MEMPCPY = 1,
    .GNULIB_TEST_MEMRCHR = 1,
    .GNULIB_TEST_MKDIR = 1,
    .GNULIB_TEST_MKDTEMP = 1,
    .GNULIB_TEST_MKSTEMP = 1,
    .GNULIB_TEST_NANOSLEEP = 1,
    .GNULIB_TEST_NL_LANGINFO = 1,
    .GNULIB_TEST_OPEN = 1,
    .GNULIB_TEST_OPENAT = 1,
    .GNULIB_TEST_OPENDIR = 1,
    .GNULIB_TEST_PERROR = 1,
    .GNULIB_TEST_PIPE = 1,
    .GNULIB_TEST_PIPE2 = 1,
    .GNULIB_TEST_POSIX_SPAWN = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_DESTROY = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_INIT = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETFLAGS = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETPGROUP = 1,
    .GNULIB_TEST_POSIX_SPAWNATTR_SETSIGMASK = 1,
    .GNULIB_TEST_POSIX_SPAWNP = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2 = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_DESTROY = 1,
    .GNULIB_TEST_POSIX_SPAWN_FILE_ACTIONS_INIT = 1,
    .GNULIB_TEST_PRINTF = 1,
    .GNULIB_TEST_PTHREAD_SIGMASK = 1,
    .GNULIB_TEST_PTHREAD_THREAD = 1,
    .GNULIB_TEST_PUTC = 1,
    .GNULIB_TEST_PUTCHAR = 1,
    .GNULIB_TEST_PUTENV = 1,
    .GNULIB_TEST_PUTS = 1,
    .GNULIB_TEST_RAISE = 1,
    .GNULIB_TEST_RAWMEMCHR = 1,
    .GNULIB_TEST_READDIR = 1,
    .GNULIB_TEST_READLINK = 1,
    .GNULIB_TEST_REALLOCARRAY = 1,
    .GNULIB_TEST_REALLOC_POSIX = 1,
    .GNULIB_TEST_REALPATH = 1,
    .GNULIB_TEST_RENAME = 1,
    .GNULIB_TEST_REWINDDIR = 1,
    .GNULIB_TEST_RMDIR = 1,
    .GNULIB_TEST_SCANF = 1,
    .GNULIB_TEST_SCHED_YIELD = 1,
    .GNULIB_TEST_SECURE_GETENV = 1,
    .GNULIB_TEST_SELECT = 1,
    .GNULIB_TEST_SETENV = 1,
    .GNULIB_TEST_SETLOCALE = 1,
    .GNULIB_TEST_SETLOCALE_NULL = 1,
    .GNULIB_TEST_SETSOCKOPT = 1,
    .GNULIB_TEST_SIGACTION = 1,
    .GNULIB_TEST_SIGNBIT = 1,
    .GNULIB_TEST_SIGPROCMASK = 1,
    .GNULIB_TEST_SLEEP = 1,
    .GNULIB_TEST_SNPRINTF = 1,
    .GNULIB_TEST_SOCKET = 1,
    .GNULIB_TEST_STAT = 1,
    .GNULIB_TEST_STPCPY = 1,
    .GNULIB_TEST_STRCHRNUL = 1,
    .GNULIB_TEST_STRDUP = 1,
    .GNULIB_TEST_STRERROR = 1,
    .GNULIB_TEST_STRERROR_R = 1,
    .GNULIB_TEST_STRNDUP = 1,
    .GNULIB_TEST_STRNLEN = 1,
    .GNULIB_TEST_STRSIGNAL = 1,
    .GNULIB_TEST_STRSTR = 1,
    .GNULIB_TEST_STRTOD = 1,
    .GNULIB_TEST_SYMLINK = 1,
    .GNULIB_TEST_UNSETENV = 1,
    .GNULIB_TEST_VASPRINTF = 1,
    .GNULIB_TEST_VFPRINTF = 1,
    .GNULIB_TEST_VPRINTF = 1,
    .GNULIB_TEST_WAITPID = 1,
    .GNULIB_TEST_WCRTOMB = 1,
    .GNULIB_TEST_WCTOB = 1,
    .GNULIB_TEST_WCTOMB = 1,
    .GNULIB_TEST_WCWIDTH = 1,
    .GNULIB_TEST_WRITE = 1,
    .GNULIB_UNISTR_U8_MBTOUCR = 1,
    .GNULIB_UNISTR_U8_UCTOMB = 1,
    .GNULIB_WCHAR_SINGLE_LOCALE = 1,
    .GNULIB_XALLOC = 1,
    .GNULIB_XALLOC_DIE = 1,
    .HAVE_ALLOCA = 1,
    .HAVE_ALLOCA_H = 1,
    .HAVE_ARPA_INET_H = 1,
    .HAVE_BCRYPT_H = null,
    .HAVE_BP_SYM_H = null,
    .HAVE_BTOWC = 1,
    .HAVE_BUG_BIG_NANOSLEEP = 1,
    .HAVE_CANONICALIZE_FILE_NAME = 1,
    .HAVE_CATGETS = 1,
    .HAVE_CFLOCALECOPYPREFERREDLANGUAGES = null,
    .HAVE_CFPREFERENCESCOPYAPPVALUE = null,
    .HAVE_CLOCK_GETTIME = 1,
    .HAVE_CLOCK_SETTIME = 1,
    .HAVE_CLOSEDIR = 1,
    .HAVE_CLOSE_RANGE = 1,
    .HAVE_CONFSTR = null,
    .HAVE_COPYSIGNF_IN_LIBC = null,
    .HAVE_COPYSIGNL_IN_LIBC = null,
    .HAVE_COPYSIGN_IN_LIBC = null,
    .HAVE_CRTDEFS_H = null,
    .HAVE_DCGETTEXT = null,
    .HAVE_DECL_ALARM = 1,
    .HAVE_DECL_CLEARERR_UNLOCKED = 1,
    .HAVE_DECL_COPYSIGN = null,
    .HAVE_DECL_COPYSIGNF = null,
    .HAVE_DECL_COPYSIGNL = null,
    .HAVE_DECL_DIRFD = 1,
    .HAVE_DECL_ECVT = 1,
    .HAVE_DECL_EXECVPE = 1,
    .HAVE_DECL_FCHDIR = 1,
    .HAVE_DECL_FCLOSEALL = 1,
    .HAVE_DECL_FCVT = 1,
    .HAVE_DECL_FDOPENDIR = 1,
    .HAVE_DECL_FEOF_UNLOCKED = 1,
    .HAVE_DECL_FERROR_UNLOCKED = 1,
    .HAVE_DECL_FFLUSH_UNLOCKED = 1,
    .HAVE_DECL_FGETS_UNLOCKED = 1,
    .HAVE_DECL_FPURGE = 0,
    .HAVE_DECL_FPUTC_UNLOCKED = 1,
    .HAVE_DECL_FPUTS_UNLOCKED = 1,
    .HAVE_DECL_FREAD_UNLOCKED = 1,
    .HAVE_DECL_FSEEKO = 1,
    .HAVE_DECL_FTELLO = 1,
    .HAVE_DECL_FWRITE_UNLOCKED = 1,
    .HAVE_DECL_GCVT = 1,
    .HAVE_DECL_GETCHAR_UNLOCKED = 1,
    .HAVE_DECL_GETCWD = 1,
    .HAVE_DECL_GETC_UNLOCKED = 1,
    .HAVE_DECL_GETDTABLESIZE = 1,
    .HAVE_DECL_INET_PTON = 1,
    .HAVE_DECL_ISBLANK = 1,
    .HAVE_DECL_ISWBLANK = 1,
    .HAVE_DECL_MBRTOWC = null,
    .HAVE_DECL_MBSINIT = null,
    .HAVE_DECL_MEMRCHR = 1,
    .HAVE_DECL_POSIX_SPAWN = 1,
    .HAVE_DECL_PROGRAM_INVOCATION_NAME = 1,
    .HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME = 1,
    .HAVE_DECL_PUTCHAR_UNLOCKED = 1,
    .HAVE_DECL_PUTC_UNLOCKED = 1,
    .HAVE_DECL_SETENV = 1,
    .HAVE_DECL_SLEEP = 1,
    .HAVE_DECL_SNPRINTF = 1,
    .HAVE_DECL_STRDUP = 1,
    .HAVE_DECL_STRERROR_R = 1,
    .HAVE_DECL_STRNDUP = 1,
    .HAVE_DECL_STRNLEN = 1,
    .HAVE_DECL_STRSIGNAL = 1,
    .HAVE_DECL_SYS_SIGLIST = null,
    .HAVE_DECL_TOWLOWER = null,
    .HAVE_DECL_UNSETENV = 1,
    .HAVE_DECL_WCRTOMB = null,
    .HAVE_DECL_WCSDUP = 1,
    .HAVE_DECL_WCTOB = 1,
    .HAVE_DECL_WCWIDTH = 1,
    .HAVE_DECL__FSEEKI64 = null,
    .HAVE_DECL__PUTENV = null,
    .HAVE_DECL__SNPRINTF = 0,
    .HAVE_DECL__SYS_SIGLIST = null,
    .HAVE_DECL___ARGV = 0,
    .HAVE_DECL___FPENDING = 1,
    .HAVE_DIRENT_H = 1,
    .HAVE_DIRFD = 1,
    .HAVE_DUPLOCALE = 1,
    .HAVE_ENVIRON_DECL = 1,
    .HAVE_EXPLICIT_BZERO = 1,
    .HAVE_EXPLICIT_MEMSET = null,
    .HAVE_FACCESSAT = 1,
    .HAVE_FAKE_LOCALES = null,
    .HAVE_FCHDIR = 1,
    .HAVE_FCNTL = 1,
    .HAVE_FDOPENDIR = 1,
    .HAVE_FEATURES_H = 1,
    .HAVE_FPURGE = null,
    .HAVE_FREELOCALE = 1,
    .HAVE_FREE_POSIX = 1,
    .HAVE_FREXPL_IN_LIBC = 1,
    .HAVE_FREXP_IN_LIBC = 1,
    .HAVE_FSEEKO = 1,
    .HAVE_FSTATAT = 1,
    .HAVE_FTRUNCATE = 1,
    .HAVE_GETCWD = 1,
    .HAVE_GETCWD_SHORTER = null,
    .HAVE_GETDTABLESIZE = 1,
    .HAVE_GETEGID = 1,
    .HAVE_GETEUID = 1,
    .HAVE_GETEXECNAME = null,
    .HAVE_GETGID = 1,
    .HAVE_GETLOCALENAME_L = null,
    .HAVE_GETOPT_H = 1,
    .HAVE_GETOPT_LONG_ONLY = 1,
    .HAVE_GETPAGESIZE = null,
    .HAVE_GETPROGNAME = null,
    .HAVE_GETRANDOM = 1,
    .HAVE_GETRLIMIT = 1,
    .HAVE_GETTEXT = null,
    .HAVE_GETTIMEOFDAY = 1,
    .HAVE_GETUID = 1,
    .HAVE_GOOD_USELOCALE = 1,
    .HAVE_ICONV = 1,
    .HAVE_ICONV_H = 1,
    .HAVE_INET_PTON = null,
    .HAVE_INLINE = 1,
    .HAVE_INTMAX_T = 1,
    .HAVE_INTTYPES_H = 1,
    .HAVE_INTTYPES_H_WITH_UINTMAX = 1,
    .HAVE_IOCTL = 1,
    .HAVE_IPV4 = 1,
    .HAVE_IPV6 = 1,
    .HAVE_ISBLANK = 1,
    .HAVE_ISNAND_IN_LIBC = 1,
    .HAVE_ISNANF_IN_LIBC = 1,
    .HAVE_ISNANL_IN_LIBC = 1,
    .HAVE_ISSETUGID = null,
    .HAVE_ISWBLANK = 1,
    .HAVE_ISWCNTRL = 1,
    .HAVE_ISWCTYPE = 1,
    .HAVE_LANGINFO_CODESET = 1,
    .HAVE_LANGINFO_H = 1,
    .HAVE_LC_MESSAGES = 1,
    .HAVE_LDEXPL_IN_LIBC = 1,
    .HAVE_LDEXP_IN_LIBC = 1,
    .HAVE_LIBINTL_H = 1,
    .HAVE_LIBSIGSEGV = null,
    .HAVE_LIB_BCRYPT = null,
    .HAVE_LIMITS_H = 1,
    .HAVE_LINK = 1,
    .HAVE_LONG_LONG_INT = 1,
    .HAVE_LSTAT = 1,
    .HAVE_MALLOC_H = 1,
    .HAVE_MALLOC_POSIX = 1,
    .HAVE_MAP_ANONYMOUS = 1,
    .HAVE_MATH_H = 1,
    .HAVE_MBRTOWC = 1,
    .HAVE_MBSINIT = 1,
    .HAVE_MBSLEN = null,
    .HAVE_MBSTATE_T = 1,
    .HAVE_MBTOWC = 1,
    .HAVE_MEMPCPY = 1,
    .HAVE_MEMRCHR = 1,
    .HAVE_MEMSET_S = null,
    .HAVE_MINIMALLY_WORKING_GETCWD = 1,
    .HAVE_MINIX_CONFIG_H = null,
    .HAVE_MINMAX_IN_LIMITS_H = null,
    .HAVE_MINMAX_IN_SYS_PARAM_H = 1,
    .HAVE_MKDTEMP = 1,
    .HAVE_MKSTEMP = 1,
    .HAVE_MPROTECT = 1,
    .HAVE_MQUERY = null,
    .HAVE_MSVC_INVALID_PARAMETER_HANDLER = null,
    .HAVE_NAMELESS_LOCALES = null,
    .HAVE_NETDB_H = 1,
    .HAVE_NETINET_IN_H = 1,
    .HAVE_NEWLOCALE = 1,
    .HAVE_NL_LANGINFO = 1,
    .HAVE_OBSTACK = null,
    .HAVE_OPENAT = 1,
    .HAVE_OPENDIR = 1,
    .HAVE_OS_H = null,
    .HAVE_PARTLY_WORKING_GETCWD = null,
    .HAVE_PATHS_H = null,
    .HAVE_PIPE = 1,
    .HAVE_PIPE2 = 1,
    .HAVE_POSIX_SPAWN = 1,
    .HAVE_POSIX_SPAWNATTR_T = 1,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = null,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR_NP = 1,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_T = 1,
    .HAVE_PSTAT_GETPROCVM = null,
    .HAVE_PTHREAD_API = 1,
    .HAVE_PTHREAD_ATFORK = null,
    .HAVE_PTHREAD_H = 1,
    .HAVE_PTHREAD_MUTEX_RECURSIVE = null,
    .HAVE_PTHREAD_RWLOCK = null,
    .HAVE_PTHREAD_RWLOCK_RDLOCK_PREFER_WRITER = null,
    .HAVE_PTHREAD_SIGMASK = 1,
    .HAVE_PTHREAD_SPINLOCK_T = 1,
    .HAVE_PTHREAD_T = 1,
    .HAVE_RAISE = 1,
    .HAVE_RAWMEMCHR = 1,
    .HAVE_READDIR = 1,
    .HAVE_READLINK = 1,
    .HAVE_REALLOCARRAY = 1,
    .HAVE_REALPATH = 1,
    .HAVE_REWINDDIR = 1,
    .HAVE_SAME_LONG_DOUBLE_AS_DOUBLE = null,
    .HAVE_SA_FAMILY_T = 1,
    .HAVE_SCHED_H = 1,
    .HAVE_SCHED_SETPARAM = null,
    .HAVE_SCHED_SETSCHEDULER = null,
    .HAVE_SDKDDKVER_H = null,
    .HAVE_SEARCH_H = 1,
    .HAVE_SECURE_GETENV = 1,
    .HAVE_SEMAPHORE_H = 1,
    .HAVE_SETDTABLESIZE = null,
    .HAVE_SETEGID = null,
    .HAVE_SETENV = 1,
    .HAVE_SETEUID = null,
    .HAVE_SETRLIMIT = 1,
    .HAVE_SHUTDOWN = 1,
    .HAVE_SIGACTION = 1,
    .HAVE_SIGALTSTACK = 1,
    .HAVE_SIGINFO_T = null,
    .HAVE_SIGINTERRUPT = 1,
    .HAVE_SIGNED_SIG_ATOMIC_T = null,
    .HAVE_SIGNED_WCHAR_T = null,
    .HAVE_SIGNED_WINT_T = null,
    .HAVE_SIGSET_T = 1,
    .HAVE_SIG_ATOMIC_T = 1,
    .HAVE_SLEEP = 1,
    .HAVE_SNPRINTF = 1,
    .HAVE_SNPRINTF_RETVAL_C99 = 1,
    .HAVE_SNPRINTF_TRUNCATION_C99 = 1,
    .HAVE_SOLARIS114_LOCALES = null,
    .HAVE_SPAWN_H = 1,
    .HAVE_STDINT_H = 1,
    .HAVE_STDINT_H_WITH_UINTMAX = 1,
    .HAVE_STDIO_EXT_H = 1,
    .HAVE_STDIO_H = 1,
    .HAVE_STDLIB_H = 1,
    .HAVE_STPCPY = 1,
    .HAVE_STRCHRNUL = 1,
    .HAVE_STRERROR_R = 1,
    .HAVE_STRINGS_H = 1,
    .HAVE_STRING_H = 1,
    .HAVE_STRNDUP = 1,
    .HAVE_STRNLEN = 1,
    .HAVE_STRSIGNAL = 1,
    .HAVE_STRUCT_LCONV_DECIMAL_POINT = null,
    .HAVE_STRUCT_SIGACTION_SA_SIGACTION = 1,
    .HAVE_STRUCT_SOCKADDR_STORAGE = 1,
    .HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY = 1,
    .HAVE_STRUCT_STAT_ST_ATIMENSEC = null,
    .HAVE_STRUCT_STAT_ST_ATIMESPEC_TV_NSEC = null,
    .HAVE_STRUCT_STAT_ST_ATIM_ST__TIM_TV_NSEC = null,
    .HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC = 1,
    .HAVE_STRUCT_STAT_ST_BIRTHTIMENSEC = null,
    .HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC = null,
    .HAVE_STRUCT_STAT_ST_BIRTHTIM_TV_NSEC = null,
    .HAVE_SYMLINK = 1,
    .HAVE_SYS_BITYPES_H = null,
    .HAVE_SYS_CDEFS_H = 1,
    .HAVE_SYS_INTTYPES_H = null,
    .HAVE_SYS_IOCTL_H = 1,
    .HAVE_SYS_MMAN_H = 1,
    .HAVE_SYS_PARAM_H = 1,
    .HAVE_SYS_RANDOM_H = 1,
    .HAVE_SYS_SELECT_H = 1,
    .HAVE_SYS_SINGLE_THREADED_H = 1,
    .HAVE_SYS_SOCKET_H = 1,
    .HAVE_SYS_STAT_H = 1,
    .HAVE_SYS_TIME_H = 1,
    .HAVE_SYS_TYPES_H = 1,
    .HAVE_SYS_UIO_H = 1,
    .HAVE_SYS_WAIT_H = 1,
    .HAVE_THRD_CREATE = null,
    .HAVE_THREADS_H = 1,
    .HAVE_TOWLOWER = 1,
    .HAVE_TSEARCH = 1,
    .HAVE_UNISTD_H = 1,
    .HAVE_UNSETENV = 1,
    .HAVE_UNSIGNED_LONG_LONG_INT = 1,
    .HAVE_USELOCALE = 1,
    .HAVE_VAR___PROGNAME = null,
    .HAVE_VASNPRINTF = null,
    .HAVE_VASPRINTF = 1,
    .HAVE_VFORK = null,
    .HAVE_VISIBILITY = null,
    .HAVE_WAITID = 1,
    .HAVE_WCHAR_H = 1,
    .HAVE_WCHAR_T = 1,
    .HAVE_WCRTOMB = 1,
    .HAVE_WCSLEN = 1,
    .HAVE_WCSNLEN = 1,
    .HAVE_WCTOB = 1,
    .HAVE_WCTYPE_H = 1,
    .HAVE_WCWIDTH = 1,
    .HAVE_WEAK_SYMBOLS = null,
    .HAVE_WINSOCK2_H = null,
    .HAVE_WINT_T = 1,
    .HAVE_WORKING_FSTATAT_ZERO_FLAG = null,
    .HAVE_WORKING_O_NOATIME = 1,
    .HAVE_WORKING_O_NOFOLLOW = 1,
    .HAVE_WORKING_SIGALTSTACK = 1,
    .HAVE_WORKING_USELOCALE = 1,
    .HAVE_WS2TCPIP_H = null,
    .HAVE_XLOCALE_H = null,
    .HAVE__BOOL = 1,
    .HAVE__CHSIZE = null,
    .HAVE__FSEEKI64 = null,
    .HAVE__FTELLI64 = null,
    .HAVE__SET_INVALID_PARAMETER_HANDLER = null,
    .HAVE___BUILTIN_EXPECT = 1,
    .HAVE___FPURGE = 1,
    .HAVE___FREADAHEAD = null,
    .HAVE___FREADING = 1,
    .HAVE___INLINE = 1,
    .HAVE___SECURE_GETENV = null,
    .HAVE___XPG_STRERROR_R = 1,
    .ICONV_CONST = {},
    .ICONV_FLAVOR = null,
    .LDBL_EXPBIT0_BIT = 0,
    .LDBL_EXPBIT0_WORD = 2,
    .LDBL_SIGNBIT_BIT = null,
    .LDBL_SIGNBIT_WORD = null,
    .LOCALENAME_ENHANCE_LOCALE_FUNCS = null,
    .LSEEK_PIPE_BROKEN = null,
    .LSTAT_FOLLOWS_SLASHED_SYMLINK = 1,
    .MALLOC_0_IS_NONNULL = 1,
    .MAP_ANONYMOUS = null,
    .MBRTOWC_EMPTY_INPUT_BUG = null,
    .MBRTOWC_IN_C_LOCALE_MAYBE_EILSEQ = 1,
    .MBRTOWC_NULL_ARG1_BUG = null,
    .MBRTOWC_NULL_ARG2_BUG = null,
    .MBRTOWC_NUL_RETVAL_BUG = null,
    .MBRTOWC_RETVAL_BUG = null,
    .MBRTOWC_STORES_INCOMPLETE_BUG = null,
    .MUSL_LIBC = null,
    .NDEBUG = null,
    .NEED_PRINTF_DIRECTIVE_A = null,
    .NEED_PRINTF_DIRECTIVE_F = null,
    .NEED_PRINTF_DIRECTIVE_LS = null,
    .NEED_PRINTF_DOUBLE = null,
    .NEED_PRINTF_ENOMEM = null,
    .NEED_PRINTF_FLAG_GROUPING = null,
    .NEED_PRINTF_FLAG_LEFTADJUST = null,
    .NEED_PRINTF_FLAG_ZERO = null,
    .NEED_PRINTF_INFINITE_DOUBLE = null,
    .NEED_PRINTF_INFINITE_LONG_DOUBLE = null,
    .NEED_PRINTF_LONG_DOUBLE = null,
    .NEED_PRINTF_UNBOUNDED_PRECISION = null,
    .NEED_SETLOCALE_IMPROVED = 0,
    .NEED_SETLOCALE_MTSAFE = 0,
    .NL_LANGINFO_MTSAFE = 1,
    .OPEN_TRAILING_SLASH_BUG = null,
    .PACKAGE = "m4",
    .PACKAGE_BUGREPORT = "bug-m4@gnu.org",
    .PACKAGE_NAME = "GNU M4",
    .PACKAGE_PACKAGER = null,
    .PACKAGE_PACKAGER_BUG_REPORTS = null,
    .PACKAGE_PACKAGER_VERSION = null,
    .PACKAGE_STRING = "GNU M4 " ++ version,
    .PACKAGE_TARNAME = "m4",
    .PACKAGE_URL = "https://www.gnu.org/software/m4/",
    .PACKAGE_VERSION = version,
    .PROMOTED_MODE_T = .mode_t,
    .PTHREAD_CREATE_IS_INLINE = null,
    .PTHREAD_IN_USE_DETECTION_HARD = null,
    .PTHREAD_SIGMASK_FAILS_WITH_ERRNO = null,
    .PTHREAD_SIGMASK_INEFFECTIVE = null,
    .PTHREAD_SIGMASK_UNBLOCK_BUG = null,
    .PTRDIFF_T_SUFFIX = null,
    .READLINK_TRAILING_SLASH_BUG = null,
    .READLINK_TRUNCATE_BUG = null,
    .RENAME_DEST_EXISTS_BUG = null,
    .RENAME_HARD_LINK_BUG = null,
    .RENAME_OPEN_FILE_WORKS = 1,
    .RENAME_TRAILING_SLASH_DEST_BUG = null,
    .RENAME_TRAILING_SLASH_SOURCE_BUG = null,
    .REPLACE_DIRFD = null,
    .REPLACE_FCHDIR = null,
    .REPLACE_FUNC_STAT_FILE = null,
    .REPLACE_NL_LANGINFO = null,
    .REPLACE_OPEN_DIRECTORY = null,
    .REPLACE_POSIX_SPAWN = null,
    .REPLACE_STRERROR_0 = null,
    .REPLACE_VASNPRINTF = null,
    .SETLOCALE_NULL_ALL_MTSAFE = 1,
    .SETLOCALE_NULL_ONE_MTSAFE = 1,
    .SIGALTSTACK_SS_REVERSED = null,
    .SIGNAL_SAFE_LIST = 1,
    .SIG_ATOMIC_T_SUFFIX = null,
    .SIZE_MAX = null,
    .SIZE_T_SUFFIX = null,
    .SOLARIS11 = null,
    .STACK_DIRECTION = -1,
    .STAT_MACROS_BROKEN = null,
    .STDC_HEADERS = 1,
    .STRERROR_R_CHAR_P = 1,
    .SYSCMD_SHELL = "/bin/sh",
    .TYPEOF_STRUCT_STAT_ST_ATIM_IS_STRUCT_TIMESPEC = 1,
    .USER_LABEL_PREFIX = {},
    .USE_ISOC_AND_POSIX_THREADS = null,
    .USE_ISOC_THREADS = null,
    .USE_POSIX_THREADS = null,
    .USE_POSIX_THREADS_WEAK = null,
    .USE_UNLOCKED_IO = .GNULIB_STDIO_SINGLE_THREAD,
    .USE_WINDOWS_THREADS = null,
    .VERSION = version,
    .VOID_UNSETENV = null,
    .WCHAR_T_SUFFIX = null,
    .WCRTOMB_C_LOCALE_BUG = null,
    .WCRTOMB_RETVAL_BUG = null,
    .WINDOWS_SOCKETS = null,
    .WINT_T_SUFFIX = null,
    .WITH_DMALLOC = null,
    .WORDS_BIGENDIAN = null,
    ._ALL_SOURCE = 1,
    ._DARWIN_C_SOURCE = 1,
    ._FILE_OFFSET_BITS = null,
    ._GNU_SOURCE = 1,
    ._HPUX_ALT_XOPEN_SOCKET_API = 1,
    ._ISOC11_SOURCE = null,
    ._LARGEFILE_SOURCE = null,
    ._LARGE_FILES = null,
    ._LCONV_C99 = null,
    ._MINIX = null,
    ._NETBSD_SOURCE = 1,
    ._OPENBSD_SOURCE = 1,
    ._POSIX_1_SOURCE = null,
    ._POSIX_PII_SOCKET = null,
    ._POSIX_PTHREAD_SEMANTICS = 1,
    ._POSIX_SOURCE = null,
    ._REGEX_INCLUDE_LIMITS_H = 1,
    ._REGEX_LARGE_OFFSETS = 1,
    ._TANDEM_SOURCE = 1,
    ._USE_STD_STAT = 1,
    ._XOPEN_SOURCE = null,
    .__EXTENSIONS__ = 1,
    .__GETOPT_PREFIX = null,
    .__STDC_CONSTANT_MACROS = null,
    .__STDC_LIMIT_MACROS = null,
    .__STDC_WANT_IEC_60559_ATTRIBS_EXT__ = 1,
    .__STDC_WANT_IEC_60559_BFP_EXT__ = 1,
    .__STDC_WANT_IEC_60559_DFP_EXT__ = 1,
    .__STDC_WANT_IEC_60559_FUNCS_EXT__ = 1,
    .__STDC_WANT_IEC_60559_TYPES_EXT__ = 1,
    .__STDC_WANT_LIB_EXT2__ = 1,
    .__STDC_WANT_MATH_SPEC_FUNCS__ = 1,
    .__USE_MINGW_ANSI_STDIO = 1,
    .__alpha__ = null,
    .__arm64__ = null,
    .__arm64_ilp32__ = null,
    .__arm__ = null,
    .__armhf__ = null,
    .__hppa64__ = null,
    .__hppa__ = null,
    .__i386__ = null,
    .__ia64__ = null,
    .__ia64_ilp32__ = null,
    .__m68k__ = null,
    .__mips64__ = null,
    .__mips__ = null,
    .__mipsn32__ = null,
    .__powerpc64__ = null,
    .__powerpc64_elfv2__ = null,
    .__powerpc__ = null,
    .__riscv32__ = null,
    .__riscv32_ilp32__ = null,
    .__riscv32_ilp32d__ = null,
    .__riscv32_ilp32f__ = null,
    .__riscv64__ = null,
    .__riscv64_ilp32__ = null,
    .__riscv64_ilp32d__ = null,
    .__riscv64_ilp32f__ = null,
    .__riscv64_lp64__ = null,
    .__riscv64_lp64d__ = null,
    .__riscv64_lp64f__ = null,
    .__s390__ = null,
    .__s390x__ = null,
    .__sh__ = null,
    .__sparc64__ = null,
    .__sparc__ = null,
    .__x86_64__ = 1,
    .__x86_64_x32__ = null,
    .eaccess = null,
    .gid_t = null,
    .intmax_t = null,
    .mbstate_t = null,
    .mode_t = null,
    .nlink_t = null,
    .off_t = null,
    .pid_t = null,
    .ptrdiff_t = null,
    .re_comp = .rpl_re_comp,
    .re_compile_fastmap = .rpl_re_compile_fastmap,
    .re_compile_pattern = .rpl_re_compile_pattern,
    .re_exec = .rpl_re_exec,
    .re_match = .rpl_re_match,
    .re_match_2 = .rpl_re_match_2,
    .re_search = .rpl_re_search,
    .re_search_2 = .rpl_re_search_2,
    .re_set_registers = .rpl_re_set_registers,
    .re_set_syntax = .rpl_re_set_syntax,
    .re_syntax_options = .rpl_re_syntax_options,
    .regcomp = .rpl_regcomp,
    .regerror = .rpl_regerror,
    .regexec = .rpl_regexec,
    .regfree = .rpl_regfree,
    .restrict = .__restrict__,
    .sig_atomic_t = null,
    .size_t = null,
    .socklen_t = null,
    .ssize_t = null,
    .stack_t = null,
    .uid_t = null,
    .va_copy = null,
};

// This checks that all values in gnulib_values are in use.
comptime {
    @setEvalBranchQuota((config_headers.len + 1) * gnulib_values_fields.len);
    var value_used = [_]bool{false} ** gnulib_values_fields.len;
    for (config_headers) |header| {
        switch (header.values) {
            .config => {},
            .gnulib => |tags| {
                for (tags) |tag| value_used[@intFromEnum(tag)] = true;
            },
        }
    }
    for (value_used, 0..) |used, i| {
        if (!used) @compileLog("Value " ++ gnulib_values_fields[i].name ++ " is unused.");
    }
}

const gnulib_values_fields = @typeInfo(@TypeOf(gnulib_values)).@"struct".fields;

const gnulib_values = .{
    .APPLE_UNIVERSAL_BUILD = 0,
    .ASM_SYMBOL_PREFIX = "\"\"",
    .GNULIBHEADERS_OVERRIDE_WINT_T = 0,
    .GNULIB_ACCESS = 1,
    .GNULIB_ACOSF = 0,
    .GNULIB_ACOSL = 0,
    .GNULIB_ALIGNED_ALLOC = 0,
    .GNULIB_ALPHASORT = 0,
    .GNULIB_ASINF = 0,
    .GNULIB_ASINL = 0,
    .GNULIB_ATAN2F = 0,
    .GNULIB_ATANF = 0,
    .GNULIB_ATANL = 0,
    .GNULIB_ATOLL = 0,
    .GNULIB_BTOWC = 1,
    .GNULIB_CALLOC_POSIX = 1,
    .GNULIB_CANONICALIZE_FILE_NAME = 1,
    .GNULIB_CBRT = 0,
    .GNULIB_CBRTF = 0,
    .GNULIB_CBRTL = 0,
    .GNULIB_CEIL = 0,
    .GNULIB_CEILF = 0,
    .GNULIB_CEILL = 0,
    .GNULIB_CHDIR = 1,
    .GNULIB_CHOWN = 0,
    .GNULIB_CLOSE = 1,
    .GNULIB_CLOSEDIR = 1,
    .GNULIB_COPYSIGN = 0,
    .GNULIB_COPYSIGNF = 0,
    .GNULIB_COPYSIGNL = 0,
    .GNULIB_COPY_FILE_RANGE = 0,
    .GNULIB_COSF = 0,
    .GNULIB_COSHF = 0,
    .GNULIB_COSL = 0,
    .GNULIB_CREAT = .IN_M4_GNULIB_TESTS,
    .GNULIB_CTIME = 0,
    .GNULIB_DIRFD = 1,
    .GNULIB_DPRINTF = 0,
    .GNULIB_DUP = 1,
    .GNULIB_DUP2 = 1,
    .GNULIB_DUP3 = 0,
    .GNULIB_DUPLOCALE = 0,
    .GNULIB_ENVIRON = 1,
    .GNULIB_EUIDACCESS = 0,
    .GNULIB_EXECL = 0,
    .GNULIB_EXECLE = 0,
    .GNULIB_EXECLP = 0,
    .GNULIB_EXECV = 0,
    .GNULIB_EXECVE = 0,
    .GNULIB_EXECVP = 0,
    .GNULIB_EXECVPE = 0,
    .GNULIB_EXP2 = 0,
    .GNULIB_EXP2F = 0,
    .GNULIB_EXP2L = 0,
    .GNULIB_EXPF = 0,
    .GNULIB_EXPL = 0,
    .GNULIB_EXPLICIT_BZERO = .IN_M4_GNULIB_TESTS,
    .GNULIB_EXPM1 = 0,
    .GNULIB_EXPM1F = 0,
    .GNULIB_EXPM1L = 0,
    .GNULIB_FABSF = 0,
    .GNULIB_FABSL = 0,
    .GNULIB_FACCESSAT = 0,
    .GNULIB_FCHDIR = 1,
    .GNULIB_FCHMODAT = 0,
    .GNULIB_FCHOWNAT = 0,
    .GNULIB_FCLOSE = 1,
    .GNULIB_FCNTL = 1,
    .GNULIB_FDATASYNC = 0,
    .GNULIB_FDOPEN = .IN_M4_GNULIB_TESTS,
    .GNULIB_FDOPENDIR = 1,
    .GNULIB_FFLUSH = 1,
    .GNULIB_FFSL = 0,
    .GNULIB_FFSLL = 0,
    .GNULIB_FGETC = 1,
    .GNULIB_FGETS = 1,
    .GNULIB_FLOOR = 0,
    .GNULIB_FLOORF = 0,
    .GNULIB_FLOORL = 0,
    .GNULIB_FMA = 0,
    .GNULIB_FMAF = 0,
    .GNULIB_FMAL = 0,
    .GNULIB_FMOD = 0,
    .GNULIB_FMODF = 0,
    .GNULIB_FMODL = 0,
    .GNULIB_FOPEN = 1,
    .GNULIB_FPRINTF = 1,
    .GNULIB_FPRINTF_POSIX = 0,
    .GNULIB_FPURGE = 1,
    .GNULIB_FPUTC = 1,
    .GNULIB_FPUTS = 1,
    .GNULIB_FREAD = 1,
    .GNULIB_FREELOCALE = "@GNULIB_FREELOCALE@", // Commented out in locale.h
    .GNULIB_FREE_POSIX = 1,
    .GNULIB_FREOPEN = .IN_M4_GNULIB_TESTS,
    .GNULIB_FREXP = 1,
    .GNULIB_FREXPF = 0,
    .GNULIB_FREXPL = 1,
    .GNULIB_FSCANF = 1,
    .GNULIB_FSEEK = 1,
    .GNULIB_FSEEKO = 1,
    .GNULIB_FSTAT = 1,
    .GNULIB_FSTATAT = 1,
    .GNULIB_FSYNC = 0,
    .GNULIB_FTELL = 1,
    .GNULIB_FTELLO = 1,
    .GNULIB_FTRUNCATE = .IN_M4_GNULIB_TESTS,
    .GNULIB_FUTIMENS = 0,
    .GNULIB_FWRITE = 1,
    .GNULIB_GETC = 1,
    .GNULIB_GETCHAR = 1,
    .GNULIB_GETCWD = 1,
    .GNULIB_GETDELIM = 0,
    .GNULIB_GETDOMAINNAME = 0,
    .GNULIB_GETDTABLESIZE = 1,
    .GNULIB_GETENTROPY = 0,
    .GNULIB_GETGROUPS = 0,
    .GNULIB_GETHOSTNAME = 0,
    .GNULIB_GETLINE = 0,
    .GNULIB_GETLOADAVG = 0,
    .GNULIB_GETLOGIN = 0,
    .GNULIB_GETLOGIN_R = 0,
    .GNULIB_GETOPT_POSIX = 1,
    .GNULIB_GETPAGESIZE = 1,
    .GNULIB_GETPASS = 0,
    .GNULIB_GETRANDOM = 1,
    .GNULIB_GETSUBOPT = 0,
    .GNULIB_GETUMASK = 0,
    .GNULIB_GETUSERSHELL = 0,
    .GNULIB_GRANTPT = 0,
    .GNULIB_GROUP_MEMBER = 0,
    .GNULIB_HYPOT = 0,
    .GNULIB_HYPOTF = 0,
    .GNULIB_HYPOTL = 0,
    .GNULIB_ICONV = 1,
    .GNULIB_ILOGB = 0,
    .GNULIB_ILOGBF = 0,
    .GNULIB_ILOGBL = 0,
    .GNULIB_IMAXABS = 0,
    .GNULIB_IMAXDIV = 0,
    .GNULIB_ISATTY = 0,
    .GNULIB_ISFINITE = 0,
    .GNULIB_ISINF = 0,
    .GNULIB_ISNAN = 0,
    .GNULIB_ISNAND = 0,
    .GNULIB_ISNANF = 0,
    .GNULIB_ISNANL = 0,
    .GNULIB_ISWBLANK = 1,
    .GNULIB_ISWCTYPE = 0,
    .GNULIB_ISWDIGIT = 1,
    .GNULIB_ISWXDIGIT = 1,
    .GNULIB_LCHMOD = 0,
    .GNULIB_LCHOWN = 0,
    .GNULIB_LDEXPF = 0,
    .GNULIB_LDEXPL = 0,
    .GNULIB_LINK = .IN_M4_GNULIB_TESTS,
    .GNULIB_LINKAT = 0,
    .GNULIB_LOCALECONV = 1,
    .GNULIB_LOCALENAME = 1,
    .GNULIB_LOCALTIME = 0,
    .GNULIB_LOG = 0,
    .GNULIB_LOG10 = 0,
    .GNULIB_LOG10F = 0,
    .GNULIB_LOG10L = 0,
    .GNULIB_LOG1P = 0,
    .GNULIB_LOG1PF = 0,
    .GNULIB_LOG1PL = 0,
    .GNULIB_LOG2 = 0,
    .GNULIB_LOG2F = 0,
    .GNULIB_LOG2L = 0,
    .GNULIB_LOGB = 0,
    .GNULIB_LOGBF = 0,
    .GNULIB_LOGBL = 0,
    .GNULIB_LOGF = 0,
    .GNULIB_LOGL = 0,
    .GNULIB_LSEEK = 1,
    .GNULIB_LSTAT = 1,
    .GNULIB_MALLOC_POSIX = 1,
    .GNULIB_MBRLEN = 0,
    .GNULIB_MBRTOWC = 1,
    .GNULIB_MBSCASECMP = 0,
    .GNULIB_MBSCASESTR = 0,
    .GNULIB_MBSCHR = 0,
    .GNULIB_MBSCSPN = 0,
    .GNULIB_MBSINIT = 1,
    .GNULIB_MBSLEN = 1,
    .GNULIB_MBSNCASECMP = 0,
    .GNULIB_MBSNLEN = 0,
    .GNULIB_MBSNRTOWCS = 0,
    .GNULIB_MBSPBRK = 0,
    .GNULIB_MBSPCASECMP = 0,
    .GNULIB_MBSRCHR = 0,
    .GNULIB_MBSRTOWCS = 0,
    .GNULIB_MBSSEP = 0,
    .GNULIB_MBSSPN = 0,
    .GNULIB_MBSSTR = 1,
    .GNULIB_MBSTOK_R = 0,
    .GNULIB_MBTOWC = 1,
    .GNULIB_MDA_ACCESS = 1,
    .GNULIB_MDA_CHDIR = 1,
    .GNULIB_MDA_CHMOD = 1,
    .GNULIB_MDA_CLOSE = 1,
    .GNULIB_MDA_CREAT = 1,
    .GNULIB_MDA_DUP = 1,
    .GNULIB_MDA_DUP2 = 1,
    .GNULIB_MDA_ECVT = 1,
    .GNULIB_MDA_EXECL = 1,
    .GNULIB_MDA_EXECLE = 1,
    .GNULIB_MDA_EXECLP = 1,
    .GNULIB_MDA_EXECV = 1,
    .GNULIB_MDA_EXECVE = 1,
    .GNULIB_MDA_EXECVP = 1,
    .GNULIB_MDA_EXECVPE = 1,
    .GNULIB_MDA_FCLOSEALL = 1,
    .GNULIB_MDA_FCVT = 1,
    .GNULIB_MDA_FDOPEN = 1,
    .GNULIB_MDA_FILENO = 1,
    .GNULIB_MDA_GCVT = 1,
    .GNULIB_MDA_GETCWD = 1,
    .GNULIB_MDA_GETPID = 1,
    .GNULIB_MDA_GETW = 1,
    .GNULIB_MDA_ISATTY = 1,
    .GNULIB_MDA_J0 = 1,
    .GNULIB_MDA_J1 = 1,
    .GNULIB_MDA_JN = 1,
    .GNULIB_MDA_LSEEK = 1,
    .GNULIB_MDA_MEMCCPY = 1,
    .GNULIB_MDA_MKDIR = 1,
    .GNULIB_MDA_MKTEMP = 1,
    .GNULIB_MDA_OPEN = 1,
    .GNULIB_MDA_PUTENV = 1,
    .GNULIB_MDA_PUTW = 1,
    .GNULIB_MDA_READ = 1,
    .GNULIB_MDA_RMDIR = 1,
    .GNULIB_MDA_STRDUP = 1,
    .GNULIB_MDA_SWAB = 1,
    .GNULIB_MDA_TEMPNAM = 1,
    .GNULIB_MDA_TZSET = 1,
    .GNULIB_MDA_UMASK = 1,
    .GNULIB_MDA_UNLINK = 1,
    .GNULIB_MDA_WCSDUP = 1,
    .GNULIB_MDA_WRITE = 1,
    .GNULIB_MDA_Y0 = 1,
    .GNULIB_MDA_Y1 = 1,
    .GNULIB_MDA_YN = 1,
    .GNULIB_MEMCHR = 1,
    .GNULIB_MEMMEM = 0,
    .GNULIB_MEMPCPY = 1,
    .GNULIB_MEMRCHR = 1,
    .GNULIB_MKDIR = 1,
    .GNULIB_MKDIRAT = 0,
    .GNULIB_MKDTEMP = 1,
    .GNULIB_MKFIFO = 0,
    .GNULIB_MKFIFOAT = 0,
    .GNULIB_MKNOD = 0,
    .GNULIB_MKNODAT = 0,
    .GNULIB_MKOSTEMP = 0,
    .GNULIB_MKOSTEMPS = 0,
    .GNULIB_MKSTEMP = 1,
    .GNULIB_MKSTEMPS = 0,
    .GNULIB_MKTIME = 0,
    .GNULIB_MODF = 0,
    .GNULIB_MODFF = 0,
    .GNULIB_MODFL = 0,
    .GNULIB_NANOSLEEP = .IN_M4_GNULIB_TESTS,
    .GNULIB_NEWLOCALE = "@GNULIB_NEWLOCALE@", // Commented out in locale.h
    .GNULIB_NL_LANGINFO = 1,
    .GNULIB_NONBLOCKING = 0,
    .GNULIB_OBSTACK_PRINTF = 0,
    .GNULIB_OBSTACK_PRINTF_POSIX = 0,
    .GNULIB_OPEN = 1,
    .GNULIB_OPENAT = 1,
    .GNULIB_OPENDIR = 1,
    .GNULIB_OVERRIDES_STRUCT_STAT = 0,
    .GNULIB_PCLOSE = 0,
    .GNULIB_PERROR = .IN_M4_GNULIB_TESTS,
    .GNULIB_PIPE = 1,
    .GNULIB_PIPE2 = 1,
    .GNULIB_POPEN = 0,
    .GNULIB_POSIX_MEMALIGN = 0,
    .GNULIB_POSIX_OPENPT = 0,
    .GNULIB_POSIX_SPAWN = 1,
    .GNULIB_POSIX_SPAWNATTR_DESTROY = 1,
    .GNULIB_POSIX_SPAWNATTR_GETFLAGS = 0,
    .GNULIB_POSIX_SPAWNATTR_GETPGROUP = 0,
    .GNULIB_POSIX_SPAWNATTR_GETSCHEDPARAM = 0,
    .GNULIB_POSIX_SPAWNATTR_GETSCHEDPOLICY = 0,
    .GNULIB_POSIX_SPAWNATTR_GETSIGDEFAULT = 0,
    .GNULIB_POSIX_SPAWNATTR_GETSIGMASK = 0,
    .GNULIB_POSIX_SPAWNATTR_INIT = 1,
    .GNULIB_POSIX_SPAWNATTR_SETFLAGS = 1,
    .GNULIB_POSIX_SPAWNATTR_SETPGROUP = 1,
    .GNULIB_POSIX_SPAWNATTR_SETSCHEDPARAM = 0,
    .GNULIB_POSIX_SPAWNATTR_SETSCHEDPOLICY = 0,
    .GNULIB_POSIX_SPAWNATTR_SETSIGDEFAULT = 0,
    .GNULIB_POSIX_SPAWNATTR_SETSIGMASK = 1,
    .GNULIB_POSIX_SPAWNP = 1,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = 1,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE = 1,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2 = 1,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR = 0,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN = 1,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_DESTROY = 1,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_INIT = 1,
    .GNULIB_POWF = 0,
    .GNULIB_PREAD = 0,
    .GNULIB_PRINTF = 1,
    .GNULIB_PRINTF_POSIX = 0,
    .GNULIB_PTHREAD_SIGMASK = .IN_M4_GNULIB_TESTS,
    .GNULIB_PTSNAME = 0,
    .GNULIB_PTSNAME_R = 0,
    .GNULIB_PUTC = 1,
    .GNULIB_PUTCHAR = 1,
    .GNULIB_PUTENV = .IN_M4_GNULIB_TESTS,
    .GNULIB_PUTS = 1,
    .GNULIB_PWRITE = 0,
    .GNULIB_QSORT_R = 0,
    .GNULIB_RAISE = 1,
    .GNULIB_RANDOM = 0,
    .GNULIB_RANDOM_R = 0,
    .GNULIB_RAWMEMCHR = 1,
    .GNULIB_READ = 0,
    .GNULIB_READDIR = 1,
    .GNULIB_READLINK = 1,
    .GNULIB_READLINKAT = 0,
    .GNULIB_REALLOCARRAY = 1,
    .GNULIB_REALLOC_POSIX = 1,
    .GNULIB_REALPATH = 1,
    .GNULIB_REMAINDER = 0,
    .GNULIB_REMAINDERF = 0,
    .GNULIB_REMAINDERL = 0,
    .GNULIB_REMOVE = 0,
    .GNULIB_RENAME = 1,
    .GNULIB_RENAMEAT = 0,
    .GNULIB_REWINDDIR = 1,
    .GNULIB_RINT = 0,
    .GNULIB_RINTF = 0,
    .GNULIB_RINTL = 0,
    .GNULIB_RMDIR = 1,
    .GNULIB_ROUND = 0,
    .GNULIB_ROUNDF = 0,
    .GNULIB_ROUNDL = 0,
    .GNULIB_RPMATCH = 0,
    .GNULIB_SCANDIR = 0,
    .GNULIB_SCANF = 1,
    .GNULIB_SCHED_YIELD = .IN_M4_GNULIB_TESTS,
    .GNULIB_SECURE_GETENV = 1,
    .GNULIB_SETENV = .IN_M4_GNULIB_TESTS,
    .GNULIB_SETHOSTNAME = 0,
    .GNULIB_SETLOCALE = 1,
    .GNULIB_SETLOCALE_NULL = 1,
    .GNULIB_SIGABBREV_NP = 0,
    .GNULIB_SIGACTION = 1,
    .GNULIB_SIGDESCR_NP = 0,
    .GNULIB_SIGNAL_H_SIGPIPE = 1,
    .GNULIB_SIGNBIT = 1,
    .GNULIB_SIGPROCMASK = 1,
    .GNULIB_SINF = 0,
    .GNULIB_SINHF = 0,
    .GNULIB_SINL = 0,
    .GNULIB_SLEEP = .IN_M4_GNULIB_TESTS,
    .GNULIB_SNPRINTF = 1,
    .GNULIB_SPRINTF_POSIX = 0,
    .GNULIB_SQRTF = 0,
    .GNULIB_SQRTL = 0,
    .GNULIB_STAT = 1,
    .GNULIB_STDIO_H_NONBLOCKING = 0,
    .GNULIB_STDIO_H_SIGPIPE = 1,
    .GNULIB_STPCPY = 1,
    .GNULIB_STPNCPY = 0,
    .GNULIB_STRCASESTR = 0,
    .GNULIB_STRCHRNUL = 1,
    .GNULIB_STRDUP = 1,
    .GNULIB_STRERROR = 1,
    .GNULIB_STRERRORNAME_NP = 0,
    .GNULIB_STRERROR_R = .IN_M4_GNULIB_TESTS,
    .GNULIB_STRFTIME = 0,
    .GNULIB_STRNCAT = 0,
    .GNULIB_STRNDUP = 1,
    .GNULIB_STRNLEN = 1,
    .GNULIB_STRPBRK = 0,
    .GNULIB_STRPTIME = 0,
    .GNULIB_STRSEP = 0,
    .GNULIB_STRSIGNAL = 1,
    .GNULIB_STRSTR = 1,
    .GNULIB_STRTOD = 1,
    .GNULIB_STRTOIMAX = 0,
    .GNULIB_STRTOK_R = 0,
    .GNULIB_STRTOL = 0,
    .GNULIB_STRTOLD = 0,
    .GNULIB_STRTOLL = 0,
    .GNULIB_STRTOUL = 0,
    .GNULIB_STRTOULL = 0,
    .GNULIB_STRTOUMAX = 0,
    .GNULIB_STRVERSCMP = 0,
    .GNULIB_SYMLINK = .IN_M4_GNULIB_TESTS,
    .GNULIB_SYMLINKAT = 0,
    .GNULIB_SYSTEM_POSIX = 0,
    .GNULIB_TANF = 0,
    .GNULIB_TANHF = 0,
    .GNULIB_TANL = 0,
    .GNULIB_TIMEGM = 0,
    .GNULIB_TIMESPEC_GET = 0,
    .GNULIB_TIME_R = 0,
    .GNULIB_TIME_RZ = 0,
    .GNULIB_TMPFILE = 0,
    .GNULIB_TOWCTRANS = 0,
    .GNULIB_TRUNC = 0,
    .GNULIB_TRUNCATE = 0,
    .GNULIB_TRUNCF = 0,
    .GNULIB_TRUNCL = 0,
    .GNULIB_TTYNAME_R = 0,
    .GNULIB_TZSET = 0,
    .GNULIB_UNISTD_H_GETOPT = 0,
    .GNULIB_UNLINK = 0,
    .GNULIB_UNLINKAT = 0,
    .GNULIB_UNLOCKPT = 0,
    .GNULIB_UNSETENV = .IN_M4_GNULIB_TESTS,
    .GNULIB_USLEEP = 0,
    .GNULIB_UTIMENSAT = 0,
    .GNULIB_VASPRINTF = 1,
    .GNULIB_VDPRINTF = 0,
    .GNULIB_VFPRINTF = 1,
    .GNULIB_VFPRINTF_POSIX = 0,
    .GNULIB_VFSCANF = 0,
    .GNULIB_VPRINTF = 1,
    .GNULIB_VPRINTF_POSIX = 0,
    .GNULIB_VSCANF = 0,
    .GNULIB_VSNPRINTF = 0,
    .GNULIB_VSPRINTF_POSIX = 0,
    .GNULIB_WAITPID = 1,
    .GNULIB_WCPCPY = 0,
    .GNULIB_WCPNCPY = 0,
    .GNULIB_WCRTOMB = 1,
    .GNULIB_WCSCASECMP = 0,
    .GNULIB_WCSCAT = 0,
    .GNULIB_WCSCHR = 0,
    .GNULIB_WCSCMP = 0,
    .GNULIB_WCSCOLL = 0,
    .GNULIB_WCSCPY = 0,
    .GNULIB_WCSCSPN = 0,
    .GNULIB_WCSDUP = 0,
    .GNULIB_WCSFTIME = 0,
    .GNULIB_WCSLEN = 0,
    .GNULIB_WCSNCASECMP = 0,
    .GNULIB_WCSNCAT = 0,
    .GNULIB_WCSNCMP = 0,
    .GNULIB_WCSNCPY = 0,
    .GNULIB_WCSNLEN = 0,
    .GNULIB_WCSNRTOMBS = 0,
    .GNULIB_WCSPBRK = 0,
    .GNULIB_WCSRCHR = 0,
    .GNULIB_WCSRTOMBS = 0,
    .GNULIB_WCSSPN = 0,
    .GNULIB_WCSSTR = 0,
    .GNULIB_WCSTOK = 0,
    .GNULIB_WCSWIDTH = 0,
    .GNULIB_WCSXFRM = 0,
    .GNULIB_WCTOB = .IN_M4_GNULIB_TESTS,
    .GNULIB_WCTOMB = .IN_M4_GNULIB_TESTS,
    .GNULIB_WCTRANS = 0,
    .GNULIB_WCTYPE = 0,
    .GNULIB_WCWIDTH = 1,
    .GNULIB_WMEMCHR = 0,
    .GNULIB_WMEMCMP = 0,
    .GNULIB_WMEMCPY = 0,
    .GNULIB_WMEMMOVE = 0,
    .GNULIB_WMEMPCPY = 0,
    .GNULIB_WMEMSET = 0,
    .GNULIB_WRITE = .IN_M4_GNULIB_TESTS,
    .GNULIB__EXIT = 0,
    .GUARD_PREFIX = .GL_M4,
    .HAVE_ACOSF = 1,
    .HAVE_ACOSL = 1,
    .HAVE_ALIGNED_ALLOC = 1,
    .HAVE_ALLOCA_H = 1,
    .HAVE_ALPHASORT = 1,
    .HAVE_ASINF = 1,
    .HAVE_ASINL = 1,
    .HAVE_ATAN2F = 1,
    .HAVE_ATANF = 1,
    .HAVE_ATANL = 1,
    .HAVE_ATOLL = 1,
    .HAVE_BTOWC = 1,
    .HAVE_CANONICALIZE_FILE_NAME = 1,
    .HAVE_CBRT = 1,
    .HAVE_CHOWN = 1,
    .HAVE_CLOSEDIR = 1,
    .HAVE_COPYSIGN = 1,
    .HAVE_COPYSIGNL = 1,
    .HAVE_COPY_FILE_RANGE = 1,
    .HAVE_COSF = 1,
    .HAVE_COSHF = 1,
    .HAVE_COSL = 1,
    .HAVE_CRTDEFS_H = 0,
    .HAVE_DECL_ACOSL = 1,
    .HAVE_DECL_ASINL = 1,
    .HAVE_DECL_ATANL = 1,
    .HAVE_DECL_CBRTF = 1,
    .HAVE_DECL_CBRTL = 1,
    .HAVE_DECL_CEILF = 1,
    .HAVE_DECL_CEILL = 1,
    .HAVE_DECL_COPYSIGNF = 1,
    .HAVE_DECL_COSL = 1,
    .HAVE_DECL_DIRFD = 1,
    .HAVE_DECL_ECVT = 1,
    .HAVE_DECL_ENVIRON = 1,
    .HAVE_DECL_EXECVPE = 1,
    .HAVE_DECL_EXP2 = 1,
    .HAVE_DECL_EXP2F = 1,
    .HAVE_DECL_EXP2L = 1,
    .HAVE_DECL_EXPL = 1,
    .HAVE_DECL_EXPM1L = 1,
    .HAVE_DECL_FCHDIR = 1,
    .HAVE_DECL_FCLOSEALL = 1,
    .HAVE_DECL_FCVT = 1,
    .HAVE_DECL_FDATASYNC = 1,
    .HAVE_DECL_FDOPENDIR = 1,
    .HAVE_DECL_FLOORF = 1,
    .HAVE_DECL_FLOORL = 1,
    .HAVE_DECL_FPURGE = 0,
    .HAVE_DECL_FREXPL = 1,
    .HAVE_DECL_FSEEKO = 1,
    .HAVE_DECL_FTELLO = 1,
    .HAVE_DECL_GCVT = 1,
    .HAVE_DECL_GETDELIM = 1,
    .HAVE_DECL_GETDOMAINNAME = 1,
    .HAVE_DECL_GETLINE = 1,
    .HAVE_DECL_GETLOADAVG = 1,
    .HAVE_DECL_GETLOGIN = 1,
    .HAVE_DECL_GETLOGIN_R = 1,
    .HAVE_DECL_GETPAGESIZE = 1,
    .HAVE_DECL_GETUSERSHELL = 1,
    .HAVE_DECL_IMAXABS = 1,
    .HAVE_DECL_IMAXDIV = 1,
    .HAVE_DECL_INITSTATE = 1,
    .HAVE_DECL_LDEXPL = 1,
    .HAVE_DECL_LOCALTIME_R = 1,
    .HAVE_DECL_LOG10L = 1,
    .HAVE_DECL_LOG2 = 1,
    .HAVE_DECL_LOG2F = 1,
    .HAVE_DECL_LOG2L = 1,
    .HAVE_DECL_LOGB = 1,
    .HAVE_DECL_LOGL = 1,
    .HAVE_DECL_MEMMEM = 1,
    .HAVE_DECL_MEMRCHR = 1,
    .HAVE_DECL_OBSTACK_PRINTF = 1,
    .HAVE_DECL_REMAINDER = 1,
    .HAVE_DECL_REMAINDERL = 1,
    .HAVE_DECL_RINTF = 1,
    .HAVE_DECL_ROUND = 1,
    .HAVE_DECL_ROUNDF = 1,
    .HAVE_DECL_ROUNDL = 1,
    .HAVE_DECL_SETENV = 1,
    .HAVE_DECL_SETHOSTNAME = 1,
    .HAVE_DECL_SETSTATE = 1,
    .HAVE_DECL_SINL = 1,
    .HAVE_DECL_SNPRINTF = 1,
    .HAVE_DECL_SQRTL = 1,
    .HAVE_DECL_STRDUP = 1,
    .HAVE_DECL_STRERROR_R = 1,
    .HAVE_DECL_STRNDUP = 1,
    .HAVE_DECL_STRNLEN = 1,
    .HAVE_DECL_STRSIGNAL = 1,
    .HAVE_DECL_STRTOIMAX = 1,
    .HAVE_DECL_STRTOK_R = 1,
    .HAVE_DECL_STRTOUMAX = 1,
    .HAVE_DECL_TANL = 1,
    .HAVE_DECL_TRUNC = 1,
    .HAVE_DECL_TRUNCATE = 1,
    .HAVE_DECL_TRUNCF = 1,
    .HAVE_DECL_TRUNCL = 1,
    .HAVE_DECL_TTYNAME_R = 1,
    .HAVE_DECL_UNSETENV = 1,
    .HAVE_DECL_VSNPRINTF = 1,
    .HAVE_DECL_WCSDUP = 1,
    .HAVE_DECL_WCTOB = 1,
    .HAVE_DECL_WCWIDTH = 1,
    .HAVE_DIRENT_H = 1,
    .HAVE_DPRINTF = 1,
    .HAVE_DUP3 = 1,
    .HAVE_DUPLOCALE = 1,
    .HAVE_EUIDACCESS = 1,
    .HAVE_EXECVPE = 1,
    .HAVE_EXPF = 1,
    .HAVE_EXPL = 1,
    .HAVE_EXPLICIT_BZERO = 1,
    .HAVE_EXPM1 = 1,
    .HAVE_EXPM1F = 1,
    .HAVE_FABSF = 1,
    .HAVE_FABSL = 1,
    .HAVE_FACCESSAT = 1,
    .HAVE_FCHDIR = 1,
    .HAVE_FCHMODAT = 1,
    .HAVE_FCHOWNAT = 1,
    .HAVE_FCNTL = 1,
    .HAVE_FDATASYNC = 1,
    .HAVE_FDOPENDIR = 1,
    .HAVE_FEATURES_H = 1,
    .HAVE_FFSL = 1,
    .HAVE_FFSLL = 1,
    .HAVE_FMA = 1,
    .HAVE_FMAF = 1,
    .HAVE_FMAL = 1,
    .HAVE_FMODF = 1,
    .HAVE_FMODL = 1,
    .HAVE_FREELOCALE = 1,
    .HAVE_FREXPF = 1,
    .HAVE_FSTATAT = 1,
    .HAVE_FSYNC = 1,
    .HAVE_FTRUNCATE = 1,
    .HAVE_FUTIMENS = 1,
    .HAVE_GETDTABLESIZE = 1,
    .HAVE_GETENTROPY = 1,
    .HAVE_GETGROUPS = 1,
    .HAVE_GETHOSTNAME = 1,
    .HAVE_GETPAGESIZE = 1,
    .HAVE_GETPASS = 1,
    .HAVE_GETRANDOM = 1,
    .HAVE_GETSUBOPT = 1,
    .HAVE_GETUMASK = 1,
    .HAVE_GRANTPT = 1,
    .HAVE_GROUP_MEMBER = 1,
    .HAVE_HYPOTF = 1,
    .HAVE_HYPOTL = 1,
    .HAVE_ILOGB = 1,
    .HAVE_ILOGBF = 1,
    .HAVE_ILOGBL = 1,
    .HAVE_IMAXDIV_T = 1,
    .HAVE_INITSTATE = 1,
    .HAVE_INTTYPES_H = 1,
    .HAVE_ISNAND = 1,
    .HAVE_ISNANF = 1,
    .HAVE_ISNANL = 1,
    .HAVE_ISWBLANK = 1,
    .HAVE_ISWCNTRL = 1,
    .HAVE_LANGINFO_ALTMON = 1,
    .HAVE_LANGINFO_CODESET = 1,
    .HAVE_LANGINFO_ERA = 1,
    .HAVE_LANGINFO_H = 1,
    .HAVE_LANGINFO_T_FMT_AMPM = 1,
    .HAVE_LANGINFO_YESEXPR = 1,
    .HAVE_LCHMOD = 1,
    .HAVE_LCHOWN = 1,
    .HAVE_LDEXPF = 1,
    .HAVE_LINK = 1,
    .HAVE_LINKAT = 1,
    .HAVE_LOG10F = 1,
    .HAVE_LOG10L = 1,
    .HAVE_LOG1P = 1,
    .HAVE_LOG1PF = 1,
    .HAVE_LOG1PL = 1,
    .HAVE_LOGBF = 1,
    .HAVE_LOGBL = 1,
    .HAVE_LOGF = 1,
    .HAVE_LOGL = 1,
    .HAVE_LSTAT = 1,
    .HAVE_MBRLEN = 1,
    .HAVE_MBRTOWC = 1,
    .HAVE_MBSINIT = 1,
    .HAVE_MBSLEN = 0,
    .HAVE_MBSNRTOWCS = 1,
    .HAVE_MBSRTOWCS = 1,
    .HAVE_MBTOWC = 1,
    .HAVE_MEMPCPY = 1,
    .HAVE_MKDIRAT = 1,
    .HAVE_MKDTEMP = 1,
    .HAVE_MKFIFO = 1,
    .HAVE_MKFIFOAT = 1,
    .HAVE_MKNOD = 1,
    .HAVE_MKNODAT = 1,
    .HAVE_MKOSTEMP = 1,
    .HAVE_MKOSTEMPS = 1,
    .HAVE_MKSTEMP = 1,
    .HAVE_MKSTEMPS = 1,
    .HAVE_MODFF = 1,
    .HAVE_MODFL = 1,
    .HAVE_NANOSLEEP = 1,
    .HAVE_NEWLOCALE = 1,
    .HAVE_NL_LANGINFO = 1,
    .HAVE_OPENAT = 1,
    .HAVE_OPENDIR = 1,
    .HAVE_OS_H = 0,
    .HAVE_PCLOSE = 1,
    .HAVE_PIPE = 1,
    .HAVE_PIPE2 = 1,
    .HAVE_POPEN = 1,
    .HAVE_POSIX_MEMALIGN = 1,
    .HAVE_POSIX_OPENPT = 1,
    .HAVE_POSIX_SIGNALBLOCKING = 1,
    .HAVE_POSIX_SPAWN = 1,
    .HAVE_POSIX_SPAWNATTR_T = 1,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = 0,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR = 1,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_T = 1,
    .HAVE_POWF = 1,
    .HAVE_PREAD = 1,
    .HAVE_PTHREAD_SIGMASK = 1,
    .HAVE_PTSNAME = 1,
    .HAVE_PTSNAME_R = 1,
    .HAVE_PWRITE = 1,
    .HAVE_QSORT_R = 1,
    .HAVE_RAISE = 1,
    .HAVE_RANDOM = 1,
    .HAVE_RANDOM_H = 1,
    .HAVE_RANDOM_R = 1,
    .HAVE_RAWMEMCHR = 1,
    .HAVE_READDIR = 1,
    .HAVE_READLINK = 1,
    .HAVE_READLINKAT = 1,
    .HAVE_REALLOCARRAY = 1,
    .HAVE_REALPATH = 1,
    .HAVE_REMAINDER = 1,
    .HAVE_REMAINDERF = 1,
    .HAVE_RENAMEAT = 1,
    .HAVE_REWINDDIR = 1,
    .HAVE_RINT = 1,
    .HAVE_RINTL = 1,
    .HAVE_RPMATCH = 1,
    .HAVE_SCANDIR = 1,
    .HAVE_SCHED_H = 1,
    .HAVE_SCHED_YIELD = 1,
    .HAVE_SECURE_GETENV = 1,
    .HAVE_SETHOSTNAME = 1,
    .HAVE_SETSTATE = 1,
    .HAVE_SIGABBREV_NP = 1,
    .HAVE_SIGACTION = 1,
    .HAVE_SIGDESCR_NP = 1,
    .HAVE_SIGHANDLER_T = 1,
    .HAVE_SIGINFO_T = 1,
    .HAVE_SIGSET_T = 1,
    .HAVE_SINF = 1,
    .HAVE_SINHF = 1,
    .HAVE_SINL = 1,
    .HAVE_SLEEP = 1,
    .HAVE_SPAWN_H = 1,
    .HAVE_SQRTF = 1,
    .HAVE_SQRTL = 1,
    .HAVE_STPCPY = 1,
    .HAVE_STPNCPY = 1,
    .HAVE_STRCASESTR = 1,
    .HAVE_STRCHRNUL = 1,
    .HAVE_STRERRORNAME_NP = 1,
    .HAVE_STRPBRK = 1,
    .HAVE_STRPTIME = 1,
    .HAVE_STRSEP = 1,
    .HAVE_STRTOD = 1,
    .HAVE_STRTOL = 1,
    .HAVE_STRTOLD = 1,
    .HAVE_STRTOLL = 1,
    .HAVE_STRTOUL = 1,
    .HAVE_STRTOULL = 1,
    .HAVE_STRUCT_RANDOM_DATA = 1,
    .HAVE_STRUCT_SCHED_PARAM = 1,
    .HAVE_STRUCT_SIGACTION_SA_SIGACTION = 1,
    .HAVE_STRVERSCMP = 1,
    .HAVE_SYMLINK = 1,
    .HAVE_SYMLINKAT = 1,
    .HAVE_SYS_CDEFS_H = 1,
    .HAVE_SYS_LOADAVG_H = 0,
    .HAVE_SYS_PARAM_H = 0,
    .HAVE_SYS_RANDOM_H = 1,
    .HAVE_TANF = 1,
    .HAVE_TANHF = 1,
    .HAVE_TANL = 1,
    .HAVE_TIMEGM = 1,
    .HAVE_TIMESPEC_GET = 1,
    .HAVE_TIMEZONE_T = 0,
    .HAVE_TYPE_VOLATILE_SIG_ATOMIC_T = 1,
    .HAVE_UNISTD_H = 1,
    .HAVE_UNLINKAT = 1,
    .HAVE_UNLOCKPT = 1,
    .HAVE_USLEEP = 1,
    .HAVE_UTIMENSAT = 1,
    .HAVE_VASPRINTF = 1,
    .HAVE_VDPRINTF = 1,
    .HAVE_WCHAR_H = 1,
    .HAVE_WCPCPY = 1,
    .HAVE_WCPNCPY = 1,
    .HAVE_WCRTOMB = 1,
    .HAVE_WCSCASECMP = 1,
    .HAVE_WCSCAT = 1,
    .HAVE_WCSCHR = 1,
    .HAVE_WCSCMP = 1,
    .HAVE_WCSCOLL = 1,
    .HAVE_WCSCPY = 1,
    .HAVE_WCSCSPN = 1,
    .HAVE_WCSDUP = 1,
    .HAVE_WCSFTIME = 1,
    .HAVE_WCSLEN = 1,
    .HAVE_WCSNCASECMP = 1,
    .HAVE_WCSNCAT = 1,
    .HAVE_WCSNCMP = 1,
    .HAVE_WCSNCPY = 1,
    .HAVE_WCSNLEN = 1,
    .HAVE_WCSNRTOMBS = 1,
    .HAVE_WCSPBRK = 1,
    .HAVE_WCSRCHR = 1,
    .HAVE_WCSRTOMBS = 1,
    .HAVE_WCSSPN = 1,
    .HAVE_WCSSTR = 1,
    .HAVE_WCSTOK = 1,
    .HAVE_WCSWIDTH = 1,
    .HAVE_WCSXFRM = 1,
    .HAVE_WCTRANS_T = 1,
    .HAVE_WCTYPE_H = 1,
    .HAVE_WCTYPE_T = 1,
    .HAVE_WINT_T = 1,
    .HAVE_WMEMCHR = 1,
    .HAVE_WMEMCMP = 1,
    .HAVE_WMEMCPY = 1,
    .HAVE_WMEMMOVE = 1,
    .HAVE_WMEMPCPY = 1,
    .HAVE_WMEMSET = 1,
    .HAVE_XLOCALE_H = 0,
    .HAVE__EXIT = 1,
    .ICONV_CONST = {},
    .INCLUDE_NEXT = .include_next,
    .INCLUDE_NEXT_AS_FIRST_DIRECTIVE = .include_next,
    .INT32_MAX_LT_INTMAX_MAX = 1,
    .INT64_MAX_EQ_LONG_MAX = 1,
    .LOCALENAME_ENHANCE_LOCALE_FUNCS = 0,
    .NEXT_AS_FIRST_DIRECTIVE_MATH_H = .@"<math.h>",
    .NEXT_DIRENT_H = .@"<dirent.h>",
    .NEXT_FCNTL_H = .@"<fcntl.h>",
    .NEXT_ICONV_H = .@"<iconv.h>",
    .NEXT_INTTYPES_H = .@"<inttypes.h>",
    .NEXT_LANGINFO_H = .@"<langinfo.h>",
    .NEXT_LIMITS_H = .@"<limits.h>",
    .NEXT_LOCALE_H = .@"<locale.h>",
    .NEXT_SCHED_H = .@"<sched.h>",
    .NEXT_SIGNAL_H = .@"<signal.h>",
    .NEXT_SPAWN_H = .@"<spawn.h>",
    .NEXT_STDIO_H = .@"<stdio.h>",
    .NEXT_STDLIB_H = .@"<stdlib.h>",
    .NEXT_STRING_H = .@"<string.h>",
    .NEXT_SYS_RANDOM_H = .@"<sys/random.h>",
    .NEXT_SYS_STAT_H = .@"<sys/stat.h>",
    .NEXT_SYS_TYPES_H = .@"<sys/types.h>",
    .NEXT_SYS_WAIT_H = .@"<sys/wait.h>",
    .NEXT_TIME_H = .@"<time.h>",
    .NEXT_UNISTD_H = .@"<unistd.h>",
    .NEXT_WCHAR_H = .@"<wchar.h>",
    .NEXT_WCTYPE_H = .@"<wctype.h>",
    .PRAGMA_COLUMNS = null,
    .PRAGMA_SYSTEM_HEADER = .@"#pragma GCC system_header",
    .PRIPTR_PREFIX = "\"l\"",
    .PTHREAD_H_DEFINES_STRUCT_TIMESPEC = 0,
    .REPLACE_ACCESS = 0,
    .REPLACE_ACOSF = 0,
    .REPLACE_ALIGNED_ALLOC = 0,
    .REPLACE_ASINF = 0,
    .REPLACE_ATAN2F = 0,
    .REPLACE_ATANF = 0,
    .REPLACE_BTOWC = 0,
    .REPLACE_CALLOC = 0,
    .REPLACE_CANONICALIZE_FILE_NAME = 0,
    .REPLACE_CBRTF = 0,
    .REPLACE_CBRTL = 0,
    .REPLACE_CEIL = 0,
    .REPLACE_CEILF = 0,
    .REPLACE_CEILL = 0,
    .REPLACE_CHOWN = 0,
    .REPLACE_CLOSE = 0,
    .REPLACE_CLOSEDIR = 0,
    .REPLACE_COSF = 0,
    .REPLACE_COSHF = 0,
    .REPLACE_CREAT = 0,
    .REPLACE_CTIME = .GNULIB_PORTCHECK,
    .REPLACE_DIRFD = 0,
    .REPLACE_DPRINTF = 0,
    .REPLACE_DUP = 0,
    .REPLACE_DUP2 = 0,
    .REPLACE_DUPLOCALE = 0,
    .REPLACE_EXECL = 0,
    .REPLACE_EXECLE = 0,
    .REPLACE_EXECLP = 0,
    .REPLACE_EXECV = 0,
    .REPLACE_EXECVE = 0,
    .REPLACE_EXECVP = 0,
    .REPLACE_EXECVPE = 0,
    .REPLACE_EXP2 = 0,
    .REPLACE_EXP2L = 0,
    .REPLACE_EXPF = 0,
    .REPLACE_EXPL = 0,
    .REPLACE_EXPM1 = 0,
    .REPLACE_EXPM1F = 0,
    .REPLACE_EXPM1L = 0,
    .REPLACE_FABSL = 0,
    .REPLACE_FACCESSAT = 0,
    .REPLACE_FCHMODAT = 0,
    .REPLACE_FCHOWNAT = 0,
    .REPLACE_FCLOSE = 1,
    .REPLACE_FCNTL = 1,
    .REPLACE_FDOPEN = 0,
    .REPLACE_FDOPENDIR = 0,
    .REPLACE_FFLUSH = 1,
    .REPLACE_FFSLL = 0,
    .REPLACE_FLOOR = 0,
    .REPLACE_FLOORF = 0,
    .REPLACE_FLOORL = 0,
    .REPLACE_FMA = 0,
    .REPLACE_FMAF = 0,
    .REPLACE_FMAL = 0,
    .REPLACE_FMOD = 0,
    .REPLACE_FMODF = 0,
    .REPLACE_FMODL = 0,
    .REPLACE_FOPEN = 0,
    .REPLACE_FPRINTF = 0,
    .REPLACE_FPURGE = 0,
    .REPLACE_FREE = 0,
    .REPLACE_FREELOCALE = 0,
    .REPLACE_FREOPEN = 0,
    .REPLACE_FREXP = 0,
    .REPLACE_FREXPF = 0,
    .REPLACE_FREXPL = 0,
    .REPLACE_FSEEK = 1,
    .REPLACE_FSEEKO = 1,
    .REPLACE_FSTAT = 0,
    .REPLACE_FSTATAT = 0,
    .REPLACE_FTELL = 0,
    .REPLACE_FTELLO = 0,
    .REPLACE_FTRUNCATE = 0,
    .REPLACE_FUTIMENS = 0,
    .REPLACE_GETCWD = 1,
    .REPLACE_GETDELIM = 0,
    .REPLACE_GETDOMAINNAME = 0,
    .REPLACE_GETDTABLESIZE = 0,
    .REPLACE_GETGROUPS = 0,
    .REPLACE_GETLINE = 0,
    .REPLACE_GETLOGIN_R = 0,
    .REPLACE_GETPAGESIZE = 0,
    .REPLACE_GETPASS = 0,
    .REPLACE_GETRANDOM = 0,
    .REPLACE_GMTIME = 0,
    .REPLACE_HUGE_VAL = 0,
    .REPLACE_HYPOT = 0,
    .REPLACE_HYPOTF = 0,
    .REPLACE_HYPOTL = 0,
    .REPLACE_ICONV = 0,
    .REPLACE_ICONV_OPEN = 0,
    .REPLACE_ICONV_UTF = 0,
    .REPLACE_ILOGB = 0,
    .REPLACE_ILOGBF = 0,
    .REPLACE_ILOGBL = 0,
    .REPLACE_INITSTATE = 0,
    .REPLACE_ISATTY = 0,
    .REPLACE_ISFINITE = 0,
    .REPLACE_ISINF = 0,
    .REPLACE_ISNAN = 0,
    .REPLACE_ISWBLANK = 0,
    .REPLACE_ISWCNTRL = 0,
    .REPLACE_ISWDIGIT = 0,
    .REPLACE_ISWXDIGIT = 0,
    .REPLACE_ITOLD = 0,
    .REPLACE_LCHOWN = 0,
    .REPLACE_LDEXPL = 0,
    .REPLACE_LINK = 0,
    .REPLACE_LINKAT = 0,
    .REPLACE_LOCALECONV = 0,
    .REPLACE_LOCALTIME = 0,
    .REPLACE_LOCALTIME_R = .GNULIB_PORTCHECK,
    .REPLACE_LOG = 0,
    .REPLACE_LOG10 = 0,
    .REPLACE_LOG10F = 0,
    .REPLACE_LOG10L = 0,
    .REPLACE_LOG1P = 0,
    .REPLACE_LOG1PF = 0,
    .REPLACE_LOG1PL = 0,
    .REPLACE_LOG2 = 0,
    .REPLACE_LOG2F = 0,
    .REPLACE_LOG2L = 0,
    .REPLACE_LOGB = 0,
    .REPLACE_LOGBF = 0,
    .REPLACE_LOGBL = 0,
    .REPLACE_LOGF = 0,
    .REPLACE_LOGL = 0,
    .REPLACE_LSEEK = 0,
    .REPLACE_LSTAT = 0,
    .REPLACE_MALLOC = 0,
    .REPLACE_MBRLEN = 0,
    .REPLACE_MBRTOWC = 1,
    .REPLACE_MBSINIT = 0,
    .REPLACE_MBSNRTOWCS = 0,
    .REPLACE_MBSRTOWCS = 0,
    .REPLACE_MBSTATE_T = 0,
    .REPLACE_MBTOWC = 0,
    .REPLACE_MEMCHR = 0,
    .REPLACE_MEMMEM = 0,
    .REPLACE_MKDIR = 0,
    .REPLACE_MKFIFO = 0,
    .REPLACE_MKFIFOAT = 0,
    .REPLACE_MKNOD = 0,
    .REPLACE_MKNODAT = 0,
    .REPLACE_MKSTEMP = 0,
    .REPLACE_MKTIME = .GNULIB_PORTCHECK,
    .REPLACE_MODF = 0,
    .REPLACE_MODFF = 0,
    .REPLACE_MODFL = 0,
    .REPLACE_NAN = 0,
    .REPLACE_NANOSLEEP = 1,
    .REPLACE_NEWLOCALE = 0,
    .REPLACE_NL_LANGINFO = 0,
    .REPLACE_OBSTACK_PRINTF = 0,
    .REPLACE_OPEN = 0,
    .REPLACE_OPENAT = 0,
    .REPLACE_OPENDIR = 0,
    .REPLACE_PERROR = 0,
    .REPLACE_POPEN = 0,
    .REPLACE_POSIX_MEMALIGN = 0,
    .REPLACE_POSIX_SPAWN = 0,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = 0,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE = 0,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2 = 0,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR = 0,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN = 0,
    .REPLACE_PREAD = 0,
    .REPLACE_PRINTF = 0,
    .REPLACE_PTHREAD_SIGMASK = 1,
    .REPLACE_PTSNAME = 0,
    .REPLACE_PTSNAME_R = 0,
    .REPLACE_PUTENV = 0,
    .REPLACE_PWRITE = 0,
    .REPLACE_QSORT_R = 0,
    .REPLACE_RAISE = 0,
    .REPLACE_RANDOM = 0,
    .REPLACE_RANDOM_R = 0,
    .REPLACE_READ = 0,
    .REPLACE_READLINK = 0,
    .REPLACE_READLINKAT = 0,
    .REPLACE_REALLOC = 0,
    .REPLACE_REALLOCARRAY = 0,
    .REPLACE_REALPATH = 0,
    .REPLACE_REMAINDER = 0,
    .REPLACE_REMAINDERF = 0,
    .REPLACE_REMAINDERL = 0,
    .REPLACE_REMOVE = 0,
    .REPLACE_RENAME = 0,
    .REPLACE_RENAMEAT = 0,
    .REPLACE_RINTL = 0,
    .REPLACE_RMDIR = 0,
    .REPLACE_ROUND = 0,
    .REPLACE_ROUNDF = 0,
    .REPLACE_ROUNDL = 0,
    .REPLACE_SCHED_YIELD = 0,
    .REPLACE_SETENV = 0,
    .REPLACE_SETLOCALE = 0,
    .REPLACE_SETSTATE = 0,
    .REPLACE_SIGNBIT = 0,
    .REPLACE_SIGNBIT_USING_BUILTINS = 1,
    .REPLACE_SINF = 0,
    .REPLACE_SINHF = 0,
    .REPLACE_SLEEP = 0,
    .REPLACE_SNPRINTF = 0,
    .REPLACE_SPRINTF = 0,
    .REPLACE_SQRTF = 0,
    .REPLACE_SQRTL = 0,
    .REPLACE_STAT = 0,
    .REPLACE_STDIO_READ_FUNCS = 0,
    .REPLACE_STDIO_WRITE_FUNCS = 0,
    .REPLACE_STPNCPY = 0,
    .REPLACE_STRCASESTR = 0,
    .REPLACE_STRCHRNUL = 0,
    .REPLACE_STRDUP = 0,
    .REPLACE_STRERROR = 0,
    .REPLACE_STRERRORNAME_NP = 0,
    .REPLACE_STRERROR_R = 1,
    .REPLACE_STRFTIME = .GNULIB_PORTCHECK,
    .REPLACE_STRNCAT = 0,
    .REPLACE_STRNDUP = 0,
    .REPLACE_STRNLEN = 0,
    .REPLACE_STRSIGNAL = 0,
    .REPLACE_STRSTR = 0,
    .REPLACE_STRTOD = 0,
    .REPLACE_STRTOIMAX = 0,
    .REPLACE_STRTOK_R = 0,
    .REPLACE_STRTOL = 0,
    .REPLACE_STRTOLD = 0,
    .REPLACE_STRTOLL = 0,
    .REPLACE_STRTOUL = 0,
    .REPLACE_STRTOULL = 0,
    .REPLACE_STRTOUMAX = 0,
    .REPLACE_STRUCT_LCONV = 0,
    .REPLACE_SYMLINK = 0,
    .REPLACE_SYMLINKAT = 0,
    .REPLACE_TANF = 0,
    .REPLACE_TANHF = 0,
    .REPLACE_TIMEGM = .GNULIB_PORTCHECK,
    .REPLACE_TMPFILE = 0,
    .REPLACE_TOWLOWER = 0,
    .REPLACE_TRUNC = 0,
    .REPLACE_TRUNCATE = 0,
    .REPLACE_TRUNCF = 0,
    .REPLACE_TRUNCL = 0,
    .REPLACE_TTYNAME_R = 0,
    .REPLACE_TZSET = .GNULIB_PORTCHECK,
    .REPLACE_UNLINK = 0,
    .REPLACE_UNLINKAT = 0,
    .REPLACE_UNSETENV = 0,
    .REPLACE_USLEEP = 0,
    .REPLACE_UTIMENSAT = 0,
    .REPLACE_VASPRINTF = 1,
    .REPLACE_VDPRINTF = 0,
    .REPLACE_VFPRINTF = 0,
    .REPLACE_VPRINTF = 0,
    .REPLACE_VSNPRINTF = 0,
    .REPLACE_VSPRINTF = 0,
    .REPLACE_WCRTOMB = 0,
    .REPLACE_WCSFTIME = 0,
    .REPLACE_WCSNRTOMBS = 0,
    .REPLACE_WCSRTOMBS = 0,
    .REPLACE_WCSTOK = 0,
    .REPLACE_WCSWIDTH = 0,
    .REPLACE_WCTOB = 0,
    .REPLACE_WCTOMB = 0,
    .REPLACE_WCWIDTH = 0,
    .REPLACE_WRITE = 0,
    .SYS_TIME_H_DEFINES_STRUCT_TIMESPEC = 0,
    .TIME_H_DEFINES_STRUCT_TIMESPEC = 1,
    .TIME_H_DEFINES_TIME_UTC = 1,
    .UINT32_MAX_LT_UINTMAX_MAX = 1,
    .UINT64_MAX_EQ_ULONG_MAX = 1,
    .UNDEFINE_STRTOK_R = 0,
    .UNISTD_H_DEFINES_STRUCT_TIMESPEC = 0,
    .UNISTD_H_HAVE_SYS_RANDOM_H = 1,
    .UNISTD_H_HAVE_WINSOCK2_H = 0,
    .UNISTD_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS = 0,
    .WINDOWS_64_BIT_OFF_T = 0,
    .WINDOWS_64_BIT_ST_SIZE = 0,
    .WINDOWS_STAT_INODES = 0,
    .WINDOWS_STAT_TIMESPEC = 0,
};

const dirent_h_values = &[_]GnulibValueTag{
    .GNULIB_ALPHASORT,
    .GNULIB_CLOSEDIR,
    .GNULIB_DIRFD,
    .GNULIB_FDOPENDIR,
    .GNULIB_OPENDIR,
    .GNULIB_READDIR,
    .GNULIB_REWINDDIR,
    .GNULIB_SCANDIR,
    .GUARD_PREFIX,
    .HAVE_ALPHASORT,
    .HAVE_CLOSEDIR,
    .HAVE_DECL_DIRFD,
    .HAVE_DECL_FDOPENDIR,
    .HAVE_DIRENT_H,
    .HAVE_FDOPENDIR,
    .HAVE_OPENDIR,
    .HAVE_READDIR,
    .HAVE_REWINDDIR,
    .HAVE_SCANDIR,
    .INCLUDE_NEXT,
    .NEXT_DIRENT_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_CLOSEDIR,
    .REPLACE_DIRFD,
    .REPLACE_FDOPENDIR,
    .REPLACE_OPENDIR,
};

const fcntl_h_values = &[_]GnulibValueTag{
    .GNULIB_CREAT,
    .GNULIB_FCNTL,
    .GNULIB_MDA_CREAT,
    .GNULIB_MDA_OPEN,
    .GNULIB_NONBLOCKING,
    .GNULIB_OPEN,
    .GNULIB_OPENAT,
    .GUARD_PREFIX,
    .HAVE_FCNTL,
    .HAVE_OPENAT,
    .INCLUDE_NEXT,
    .NEXT_FCNTL_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_CREAT,
    .REPLACE_FCNTL,
    .REPLACE_OPEN,
    .REPLACE_OPENAT,
};

const iconv_h_values = &[_]GnulibValueTag{
    .GNULIB_ICONV,
    .GUARD_PREFIX,
    .ICONV_CONST,
    .INCLUDE_NEXT,
    .NEXT_ICONV_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_ICONV,
    .REPLACE_ICONV_OPEN,
    .REPLACE_ICONV_UTF,
};

const inttypes_h_values = &[_]GnulibValueTag{
    .APPLE_UNIVERSAL_BUILD,
    .GNULIB_IMAXABS,
    .GNULIB_IMAXDIV,
    .GNULIB_STRTOIMAX,
    .GNULIB_STRTOUMAX,
    .HAVE_DECL_IMAXABS,
    .HAVE_DECL_IMAXDIV,
    .HAVE_DECL_STRTOIMAX,
    .HAVE_DECL_STRTOUMAX,
    .HAVE_IMAXDIV_T,
    .HAVE_INTTYPES_H,
    .INCLUDE_NEXT,
    .INT32_MAX_LT_INTMAX_MAX,
    .INT64_MAX_EQ_LONG_MAX,
    .NEXT_INTTYPES_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .PRIPTR_PREFIX,
    .REPLACE_STRTOIMAX,
    .REPLACE_STRTOUMAX,
    .UINT32_MAX_LT_UINTMAX_MAX,
    .UINT64_MAX_EQ_ULONG_MAX,
};

const langinfo_h_values = &[_]GnulibValueTag{
    .GNULIB_NL_LANGINFO,
    .GUARD_PREFIX,
    .HAVE_LANGINFO_ALTMON,
    .HAVE_LANGINFO_CODESET,
    .HAVE_LANGINFO_ERA,
    .HAVE_LANGINFO_H,
    .HAVE_LANGINFO_T_FMT_AMPM,
    .HAVE_LANGINFO_YESEXPR,
    .HAVE_NL_LANGINFO,
    .INCLUDE_NEXT,
    .NEXT_LANGINFO_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_NL_LANGINFO,
};

const limits_h_values = &[_]GnulibValueTag{
    .GUARD_PREFIX,
    .INCLUDE_NEXT,
    .NEXT_LIMITS_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
};

const locale_h_values = &[_]GnulibValueTag{
    .GNULIB_DUPLOCALE,
    .GNULIB_FREELOCALE,
    .GNULIB_LOCALECONV,
    .GNULIB_LOCALENAME,
    .GNULIB_NEWLOCALE,
    .GNULIB_SETLOCALE,
    .GNULIB_SETLOCALE_NULL,
    .GUARD_PREFIX,
    .HAVE_DUPLOCALE,
    .HAVE_FREELOCALE,
    .HAVE_NEWLOCALE,
    .HAVE_XLOCALE_H,
    .INCLUDE_NEXT,
    .LOCALENAME_ENHANCE_LOCALE_FUNCS,
    .NEXT_LOCALE_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_DUPLOCALE,
    .REPLACE_FREELOCALE,
    .REPLACE_LOCALECONV,
    .REPLACE_NEWLOCALE,
    .REPLACE_SETLOCALE,
    .REPLACE_STRUCT_LCONV,
};

const math_h_values = &[_]GnulibValueTag{
    .GNULIB_ACOSF,
    .GNULIB_ACOSL,
    .GNULIB_ASINF,
    .GNULIB_ASINL,
    .GNULIB_ATAN2F,
    .GNULIB_ATANF,
    .GNULIB_ATANL,
    .GNULIB_CBRT,
    .GNULIB_CBRTF,
    .GNULIB_CBRTL,
    .GNULIB_CEIL,
    .GNULIB_CEILF,
    .GNULIB_CEILL,
    .GNULIB_COPYSIGN,
    .GNULIB_COPYSIGNF,
    .GNULIB_COPYSIGNL,
    .GNULIB_COSF,
    .GNULIB_COSHF,
    .GNULIB_COSL,
    .GNULIB_EXP2,
    .GNULIB_EXP2F,
    .GNULIB_EXP2L,
    .GNULIB_EXPF,
    .GNULIB_EXPL,
    .GNULIB_EXPM1,
    .GNULIB_EXPM1F,
    .GNULIB_EXPM1L,
    .GNULIB_FABSF,
    .GNULIB_FABSL,
    .GNULIB_FLOOR,
    .GNULIB_FLOORF,
    .GNULIB_FLOORL,
    .GNULIB_FMA,
    .GNULIB_FMAF,
    .GNULIB_FMAL,
    .GNULIB_FMOD,
    .GNULIB_FMODF,
    .GNULIB_FMODL,
    .GNULIB_FREXP,
    .GNULIB_FREXPF,
    .GNULIB_FREXPL,
    .GNULIB_HYPOT,
    .GNULIB_HYPOTF,
    .GNULIB_HYPOTL,
    .GNULIB_ILOGB,
    .GNULIB_ILOGBF,
    .GNULIB_ILOGBL,
    .GNULIB_ISFINITE,
    .GNULIB_ISINF,
    .GNULIB_ISNAN,
    .GNULIB_ISNAND,
    .GNULIB_ISNANF,
    .GNULIB_ISNANL,
    .GNULIB_LDEXPF,
    .GNULIB_LDEXPL,
    .GNULIB_LOG,
    .GNULIB_LOG10,
    .GNULIB_LOG10F,
    .GNULIB_LOG10L,
    .GNULIB_LOG1P,
    .GNULIB_LOG1PF,
    .GNULIB_LOG1PL,
    .GNULIB_LOG2,
    .GNULIB_LOG2F,
    .GNULIB_LOG2L,
    .GNULIB_LOGB,
    .GNULIB_LOGBF,
    .GNULIB_LOGBL,
    .GNULIB_LOGF,
    .GNULIB_LOGL,
    .GNULIB_MDA_J0,
    .GNULIB_MDA_J1,
    .GNULIB_MDA_JN,
    .GNULIB_MDA_Y0,
    .GNULIB_MDA_Y1,
    .GNULIB_MDA_YN,
    .GNULIB_MODF,
    .GNULIB_MODFF,
    .GNULIB_MODFL,
    .GNULIB_POWF,
    .GNULIB_REMAINDER,
    .GNULIB_REMAINDERF,
    .GNULIB_REMAINDERL,
    .GNULIB_RINT,
    .GNULIB_RINTF,
    .GNULIB_RINTL,
    .GNULIB_ROUND,
    .GNULIB_ROUNDF,
    .GNULIB_ROUNDL,
    .GNULIB_SIGNBIT,
    .GNULIB_SINF,
    .GNULIB_SINHF,
    .GNULIB_SINL,
    .GNULIB_SQRTF,
    .GNULIB_SQRTL,
    .GNULIB_TANF,
    .GNULIB_TANHF,
    .GNULIB_TANL,
    .GNULIB_TRUNC,
    .GNULIB_TRUNCF,
    .GNULIB_TRUNCL,
    .GUARD_PREFIX,
    .HAVE_ACOSF,
    .HAVE_ACOSL,
    .HAVE_ASINF,
    .HAVE_ASINL,
    .HAVE_ATAN2F,
    .HAVE_ATANF,
    .HAVE_ATANL,
    .HAVE_CBRT,
    .HAVE_COPYSIGN,
    .HAVE_COPYSIGNL,
    .HAVE_COSF,
    .HAVE_COSHF,
    .HAVE_COSL,
    .HAVE_DECL_ACOSL,
    .HAVE_DECL_ASINL,
    .HAVE_DECL_ATANL,
    .HAVE_DECL_CBRTF,
    .HAVE_DECL_CBRTL,
    .HAVE_DECL_CEILF,
    .HAVE_DECL_CEILL,
    .HAVE_DECL_COPYSIGNF,
    .HAVE_DECL_COSL,
    .HAVE_DECL_EXP2,
    .HAVE_DECL_EXP2F,
    .HAVE_DECL_EXP2L,
    .HAVE_DECL_EXPL,
    .HAVE_DECL_EXPM1L,
    .HAVE_DECL_FLOORF,
    .HAVE_DECL_FLOORL,
    .HAVE_DECL_FREXPL,
    .HAVE_DECL_LDEXPL,
    .HAVE_DECL_LOG10L,
    .HAVE_DECL_LOG2,
    .HAVE_DECL_LOG2F,
    .HAVE_DECL_LOG2L,
    .HAVE_DECL_LOGB,
    .HAVE_DECL_LOGL,
    .HAVE_DECL_REMAINDER,
    .HAVE_DECL_REMAINDERL,
    .HAVE_DECL_RINTF,
    .HAVE_DECL_ROUND,
    .HAVE_DECL_ROUNDF,
    .HAVE_DECL_ROUNDL,
    .HAVE_DECL_SINL,
    .HAVE_DECL_SQRTL,
    .HAVE_DECL_TANL,
    .HAVE_DECL_TRUNC,
    .HAVE_DECL_TRUNCF,
    .HAVE_DECL_TRUNCL,
    .HAVE_EXPF,
    .HAVE_EXPL,
    .HAVE_EXPM1,
    .HAVE_EXPM1F,
    .HAVE_FABSF,
    .HAVE_FABSL,
    .HAVE_FMA,
    .HAVE_FMAF,
    .HAVE_FMAL,
    .HAVE_FMODF,
    .HAVE_FMODL,
    .HAVE_FREXPF,
    .HAVE_HYPOTF,
    .HAVE_HYPOTL,
    .HAVE_ILOGB,
    .HAVE_ILOGBF,
    .HAVE_ILOGBL,
    .HAVE_ISNAND,
    .HAVE_ISNANF,
    .HAVE_ISNANL,
    .HAVE_LDEXPF,
    .HAVE_LOG10F,
    .HAVE_LOG10L,
    .HAVE_LOG1P,
    .HAVE_LOG1PF,
    .HAVE_LOG1PL,
    .HAVE_LOGBF,
    .HAVE_LOGBL,
    .HAVE_LOGF,
    .HAVE_LOGL,
    .HAVE_MODFF,
    .HAVE_MODFL,
    .HAVE_POWF,
    .HAVE_REMAINDER,
    .HAVE_REMAINDERF,
    .HAVE_RINT,
    .HAVE_RINTL,
    .HAVE_SINF,
    .HAVE_SINHF,
    .HAVE_SINL,
    .HAVE_SQRTF,
    .HAVE_SQRTL,
    .HAVE_TANF,
    .HAVE_TANHF,
    .HAVE_TANL,
    .INCLUDE_NEXT_AS_FIRST_DIRECTIVE,
    .NEXT_AS_FIRST_DIRECTIVE_MATH_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_ACOSF,
    .REPLACE_ASINF,
    .REPLACE_ATAN2F,
    .REPLACE_ATANF,
    .REPLACE_CBRTF,
    .REPLACE_CBRTL,
    .REPLACE_CEIL,
    .REPLACE_CEILF,
    .REPLACE_CEILL,
    .REPLACE_COSF,
    .REPLACE_COSHF,
    .REPLACE_EXP2,
    .REPLACE_EXP2L,
    .REPLACE_EXPF,
    .REPLACE_EXPL,
    .REPLACE_EXPM1,
    .REPLACE_EXPM1F,
    .REPLACE_EXPM1L,
    .REPLACE_FABSL,
    .REPLACE_FLOOR,
    .REPLACE_FLOORF,
    .REPLACE_FLOORL,
    .REPLACE_FMA,
    .REPLACE_FMAF,
    .REPLACE_FMAL,
    .REPLACE_FMOD,
    .REPLACE_FMODF,
    .REPLACE_FMODL,
    .REPLACE_FREXP,
    .REPLACE_FREXPF,
    .REPLACE_FREXPL,
    .REPLACE_HUGE_VAL,
    .REPLACE_HYPOT,
    .REPLACE_HYPOTF,
    .REPLACE_HYPOTL,
    .REPLACE_ILOGB,
    .REPLACE_ILOGBF,
    .REPLACE_ILOGBL,
    .REPLACE_ISFINITE,
    .REPLACE_ISINF,
    .REPLACE_ISNAN,
    .REPLACE_ITOLD,
    .REPLACE_LDEXPL,
    .REPLACE_LOG,
    .REPLACE_LOG10,
    .REPLACE_LOG10F,
    .REPLACE_LOG10L,
    .REPLACE_LOG1P,
    .REPLACE_LOG1PF,
    .REPLACE_LOG1PL,
    .REPLACE_LOG2,
    .REPLACE_LOG2F,
    .REPLACE_LOG2L,
    .REPLACE_LOGB,
    .REPLACE_LOGBF,
    .REPLACE_LOGBL,
    .REPLACE_LOGF,
    .REPLACE_LOGL,
    .REPLACE_MODF,
    .REPLACE_MODFF,
    .REPLACE_MODFL,
    .REPLACE_NAN,
    .REPLACE_REMAINDER,
    .REPLACE_REMAINDERF,
    .REPLACE_REMAINDERL,
    .REPLACE_RINTL,
    .REPLACE_ROUND,
    .REPLACE_ROUNDF,
    .REPLACE_ROUNDL,
    .REPLACE_SIGNBIT,
    .REPLACE_SIGNBIT_USING_BUILTINS,
    .REPLACE_SINF,
    .REPLACE_SINHF,
    .REPLACE_SQRTF,
    .REPLACE_SQRTL,
    .REPLACE_TANF,
    .REPLACE_TANHF,
    .REPLACE_TRUNC,
    .REPLACE_TRUNCF,
    .REPLACE_TRUNCL,
};

const sched_h_values = &[_]GnulibValueTag{
    .GNULIB_SCHED_YIELD,
    .GUARD_PREFIX,
    .HAVE_SCHED_H,
    .HAVE_SCHED_YIELD,
    .HAVE_STRUCT_SCHED_PARAM,
    .HAVE_SYS_CDEFS_H,
    .INCLUDE_NEXT,
    .NEXT_SCHED_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_SCHED_YIELD,
};

const signal_h_values = &[_]GnulibValueTag{
    .GNULIB_PTHREAD_SIGMASK,
    .GNULIB_RAISE,
    .GNULIB_SIGACTION,
    .GNULIB_SIGNAL_H_SIGPIPE,
    .GNULIB_SIGPROCMASK,
    .GUARD_PREFIX,
    .HAVE_POSIX_SIGNALBLOCKING,
    .HAVE_PTHREAD_SIGMASK,
    .HAVE_RAISE,
    .HAVE_SIGACTION,
    .HAVE_SIGHANDLER_T,
    .HAVE_SIGINFO_T,
    .HAVE_SIGSET_T,
    .HAVE_STRUCT_SIGACTION_SA_SIGACTION,
    .HAVE_TYPE_VOLATILE_SIG_ATOMIC_T,
    .INCLUDE_NEXT,
    .NEXT_SIGNAL_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_PTHREAD_SIGMASK,
    .REPLACE_RAISE,
};

const spawn_h_values = &[_]GnulibValueTag{
    .GNULIB_POSIX_SPAWN,
    .GNULIB_POSIX_SPAWNATTR_DESTROY,
    .GNULIB_POSIX_SPAWNATTR_GETFLAGS,
    .GNULIB_POSIX_SPAWNATTR_GETPGROUP,
    .GNULIB_POSIX_SPAWNATTR_GETSCHEDPARAM,
    .GNULIB_POSIX_SPAWNATTR_GETSCHEDPOLICY,
    .GNULIB_POSIX_SPAWNATTR_GETSIGDEFAULT,
    .GNULIB_POSIX_SPAWNATTR_GETSIGMASK,
    .GNULIB_POSIX_SPAWNATTR_INIT,
    .GNULIB_POSIX_SPAWNATTR_SETFLAGS,
    .GNULIB_POSIX_SPAWNATTR_SETPGROUP,
    .GNULIB_POSIX_SPAWNATTR_SETSCHEDPARAM,
    .GNULIB_POSIX_SPAWNATTR_SETSCHEDPOLICY,
    .GNULIB_POSIX_SPAWNATTR_SETSIGDEFAULT,
    .GNULIB_POSIX_SPAWNATTR_SETSIGMASK,
    .GNULIB_POSIX_SPAWNP,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_DESTROY,
    .GNULIB_POSIX_SPAWN_FILE_ACTIONS_INIT,
    .GUARD_PREFIX,
    .HAVE_POSIX_SPAWN,
    .HAVE_POSIX_SPAWNATTR_T,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR,
    .HAVE_POSIX_SPAWN_FILE_ACTIONS_T,
    .HAVE_SPAWN_H,
    .INCLUDE_NEXT,
    .NEXT_SPAWN_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_POSIX_SPAWN,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR,
    .REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN,
};

const stdio_h_values = &[_]GnulibValueTag{
    .ASM_SYMBOL_PREFIX,
    .GNULIB_DPRINTF,
    .GNULIB_FCLOSE,
    .GNULIB_FDOPEN,
    .GNULIB_FFLUSH,
    .GNULIB_FGETC,
    .GNULIB_FGETS,
    .GNULIB_FOPEN,
    .GNULIB_FPRINTF,
    .GNULIB_FPRINTF_POSIX,
    .GNULIB_FPURGE,
    .GNULIB_FPUTC,
    .GNULIB_FPUTS,
    .GNULIB_FREAD,
    .GNULIB_FREOPEN,
    .GNULIB_FSCANF,
    .GNULIB_FSEEK,
    .GNULIB_FSEEKO,
    .GNULIB_FTELL,
    .GNULIB_FTELLO,
    .GNULIB_FWRITE,
    .GNULIB_GETC,
    .GNULIB_GETCHAR,
    .GNULIB_GETDELIM,
    .GNULIB_GETLINE,
    .GNULIB_MDA_FCLOSEALL,
    .GNULIB_MDA_FDOPEN,
    .GNULIB_MDA_FILENO,
    .GNULIB_MDA_GETW,
    .GNULIB_MDA_PUTW,
    .GNULIB_MDA_TEMPNAM,
    .GNULIB_OBSTACK_PRINTF,
    .GNULIB_OBSTACK_PRINTF_POSIX,
    .GNULIB_PCLOSE,
    .GNULIB_PERROR,
    .GNULIB_POPEN,
    .GNULIB_PRINTF,
    .GNULIB_PRINTF_POSIX,
    .GNULIB_PUTC,
    .GNULIB_PUTCHAR,
    .GNULIB_PUTS,
    .GNULIB_REMOVE,
    .GNULIB_RENAME,
    .GNULIB_RENAMEAT,
    .GNULIB_SCANF,
    .GNULIB_SNPRINTF,
    .GNULIB_SPRINTF_POSIX,
    .GNULIB_STDIO_H_NONBLOCKING,
    .GNULIB_STDIO_H_SIGPIPE,
    .GNULIB_TMPFILE,
    .GNULIB_VASPRINTF,
    .GNULIB_VDPRINTF,
    .GNULIB_VFPRINTF,
    .GNULIB_VFPRINTF_POSIX,
    .GNULIB_VFSCANF,
    .GNULIB_VPRINTF,
    .GNULIB_VPRINTF_POSIX,
    .GNULIB_VSCANF,
    .GNULIB_VSNPRINTF,
    .GNULIB_VSPRINTF_POSIX,
    .GUARD_PREFIX,
    .HAVE_DECL_FCLOSEALL,
    .HAVE_DECL_FPURGE,
    .HAVE_DECL_FSEEKO,
    .HAVE_DECL_FTELLO,
    .HAVE_DECL_GETDELIM,
    .HAVE_DECL_GETLINE,
    .HAVE_DECL_OBSTACK_PRINTF,
    .HAVE_DECL_SNPRINTF,
    .HAVE_DECL_VSNPRINTF,
    .HAVE_DPRINTF,
    .HAVE_PCLOSE,
    .HAVE_POPEN,
    .HAVE_RENAMEAT,
    .HAVE_VASPRINTF,
    .HAVE_VDPRINTF,
    .INCLUDE_NEXT,
    .NEXT_STDIO_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_DPRINTF,
    .REPLACE_FCLOSE,
    .REPLACE_FDOPEN,
    .REPLACE_FFLUSH,
    .REPLACE_FOPEN,
    .REPLACE_FPRINTF,
    .REPLACE_FPURGE,
    .REPLACE_FREOPEN,
    .REPLACE_FSEEK,
    .REPLACE_FSEEKO,
    .REPLACE_FTELL,
    .REPLACE_FTELLO,
    .REPLACE_GETDELIM,
    .REPLACE_GETLINE,
    .REPLACE_OBSTACK_PRINTF,
    .REPLACE_PERROR,
    .REPLACE_POPEN,
    .REPLACE_PRINTF,
    .REPLACE_REMOVE,
    .REPLACE_RENAME,
    .REPLACE_RENAMEAT,
    .REPLACE_SNPRINTF,
    .REPLACE_SPRINTF,
    .REPLACE_STDIO_READ_FUNCS,
    .REPLACE_STDIO_WRITE_FUNCS,
    .REPLACE_TMPFILE,
    .REPLACE_VASPRINTF,
    .REPLACE_VDPRINTF,
    .REPLACE_VFPRINTF,
    .REPLACE_VPRINTF,
    .REPLACE_VSNPRINTF,
    .REPLACE_VSPRINTF,
};

const stdlib_h_values = &[_]GnulibValueTag{
    .GNULIB_ALIGNED_ALLOC,
    .GNULIB_ATOLL,
    .GNULIB_CALLOC_POSIX,
    .GNULIB_CANONICALIZE_FILE_NAME,
    .GNULIB_FREE_POSIX,
    .GNULIB_GETLOADAVG,
    .GNULIB_GETSUBOPT,
    .GNULIB_GRANTPT,
    .GNULIB_MALLOC_POSIX,
    .GNULIB_MBTOWC,
    .GNULIB_MDA_ECVT,
    .GNULIB_MDA_FCVT,
    .GNULIB_MDA_GCVT,
    .GNULIB_MDA_MKTEMP,
    .GNULIB_MDA_PUTENV,
    .GNULIB_MKDTEMP,
    .GNULIB_MKOSTEMP,
    .GNULIB_MKOSTEMPS,
    .GNULIB_MKSTEMP,
    .GNULIB_MKSTEMPS,
    .GNULIB_POSIX_MEMALIGN,
    .GNULIB_POSIX_OPENPT,
    .GNULIB_PTSNAME,
    .GNULIB_PTSNAME_R,
    .GNULIB_PUTENV,
    .GNULIB_QSORT_R,
    .GNULIB_RANDOM,
    .GNULIB_RANDOM_R,
    .GNULIB_REALLOCARRAY,
    .GNULIB_REALLOC_POSIX,
    .GNULIB_REALPATH,
    .GNULIB_RPMATCH,
    .GNULIB_SECURE_GETENV,
    .GNULIB_SETENV,
    .GNULIB_STRTOD,
    .GNULIB_STRTOL,
    .GNULIB_STRTOLD,
    .GNULIB_STRTOLL,
    .GNULIB_STRTOUL,
    .GNULIB_STRTOULL,
    .GNULIB_SYSTEM_POSIX,
    .GNULIB_UNLOCKPT,
    .GNULIB_UNSETENV,
    .GNULIB_WCTOMB,
    .GNULIB__EXIT,
    .GUARD_PREFIX,
    .HAVE_ALIGNED_ALLOC,
    .HAVE_ATOLL,
    .HAVE_CANONICALIZE_FILE_NAME,
    .HAVE_DECL_ECVT,
    .HAVE_DECL_FCVT,
    .HAVE_DECL_GCVT,
    .HAVE_DECL_GETLOADAVG,
    .HAVE_DECL_INITSTATE,
    .HAVE_DECL_SETENV,
    .HAVE_DECL_SETSTATE,
    .HAVE_DECL_UNSETENV,
    .HAVE_GETSUBOPT,
    .HAVE_GRANTPT,
    .HAVE_INITSTATE,
    .HAVE_MBTOWC,
    .HAVE_MKDTEMP,
    .HAVE_MKOSTEMP,
    .HAVE_MKOSTEMPS,
    .HAVE_MKSTEMP,
    .HAVE_MKSTEMPS,
    .HAVE_POSIX_MEMALIGN,
    .HAVE_POSIX_OPENPT,
    .HAVE_PTSNAME,
    .HAVE_PTSNAME_R,
    .HAVE_QSORT_R,
    .HAVE_RANDOM,
    .HAVE_RANDOM_H,
    .HAVE_RANDOM_R,
    .HAVE_REALLOCARRAY,
    .HAVE_REALPATH,
    .HAVE_RPMATCH,
    .HAVE_SECURE_GETENV,
    .HAVE_SETSTATE,
    .HAVE_STRTOD,
    .HAVE_STRTOL,
    .HAVE_STRTOLD,
    .HAVE_STRTOLL,
    .HAVE_STRTOUL,
    .HAVE_STRTOULL,
    .HAVE_STRUCT_RANDOM_DATA,
    .HAVE_SYS_LOADAVG_H,
    .HAVE_UNLOCKPT,
    .HAVE__EXIT,
    .INCLUDE_NEXT,
    .NEXT_STDLIB_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_ALIGNED_ALLOC,
    .REPLACE_CALLOC,
    .REPLACE_CANONICALIZE_FILE_NAME,
    .REPLACE_FREE,
    .REPLACE_INITSTATE,
    .REPLACE_MALLOC,
    .REPLACE_MBTOWC,
    .REPLACE_MKSTEMP,
    .REPLACE_POSIX_MEMALIGN,
    .REPLACE_PTSNAME,
    .REPLACE_PTSNAME_R,
    .REPLACE_PUTENV,
    .REPLACE_QSORT_R,
    .REPLACE_RANDOM,
    .REPLACE_RANDOM_R,
    .REPLACE_REALLOC,
    .REPLACE_REALLOCARRAY,
    .REPLACE_REALPATH,
    .REPLACE_SETENV,
    .REPLACE_SETSTATE,
    .REPLACE_STRTOD,
    .REPLACE_STRTOL,
    .REPLACE_STRTOLD,
    .REPLACE_STRTOLL,
    .REPLACE_STRTOUL,
    .REPLACE_STRTOULL,
    .REPLACE_UNSETENV,
    .REPLACE_WCTOMB,
};

const string_h_values = &[_]GnulibValueTag{
    .GNULIB_EXPLICIT_BZERO,
    .GNULIB_FFSL,
    .GNULIB_FFSLL,
    .GNULIB_MBSCASECMP,
    .GNULIB_MBSCASESTR,
    .GNULIB_MBSCHR,
    .GNULIB_MBSCSPN,
    .GNULIB_MBSLEN,
    .GNULIB_MBSNCASECMP,
    .GNULIB_MBSNLEN,
    .GNULIB_MBSPBRK,
    .GNULIB_MBSPCASECMP,
    .GNULIB_MBSRCHR,
    .GNULIB_MBSSEP,
    .GNULIB_MBSSPN,
    .GNULIB_MBSSTR,
    .GNULIB_MBSTOK_R,
    .GNULIB_MDA_MEMCCPY,
    .GNULIB_MDA_STRDUP,
    .GNULIB_MEMCHR,
    .GNULIB_MEMMEM,
    .GNULIB_MEMPCPY,
    .GNULIB_MEMRCHR,
    .GNULIB_RAWMEMCHR,
    .GNULIB_SIGABBREV_NP,
    .GNULIB_SIGDESCR_NP,
    .GNULIB_STPCPY,
    .GNULIB_STPNCPY,
    .GNULIB_STRCASESTR,
    .GNULIB_STRCHRNUL,
    .GNULIB_STRDUP,
    .GNULIB_STRERROR,
    .GNULIB_STRERRORNAME_NP,
    .GNULIB_STRERROR_R,
    .GNULIB_STRNCAT,
    .GNULIB_STRNDUP,
    .GNULIB_STRNLEN,
    .GNULIB_STRPBRK,
    .GNULIB_STRSEP,
    .GNULIB_STRSIGNAL,
    .GNULIB_STRSTR,
    .GNULIB_STRTOK_R,
    .GNULIB_STRVERSCMP,
    .GUARD_PREFIX,
    .HAVE_DECL_MEMMEM,
    .HAVE_DECL_MEMRCHR,
    .HAVE_DECL_STRDUP,
    .HAVE_DECL_STRERROR_R,
    .HAVE_DECL_STRNDUP,
    .HAVE_DECL_STRNLEN,
    .HAVE_DECL_STRSIGNAL,
    .HAVE_DECL_STRTOK_R,
    .HAVE_EXPLICIT_BZERO,
    .HAVE_FFSL,
    .HAVE_FFSLL,
    .HAVE_MBSLEN,
    .HAVE_MEMPCPY,
    .HAVE_RAWMEMCHR,
    .HAVE_SIGABBREV_NP,
    .HAVE_SIGDESCR_NP,
    .HAVE_STPCPY,
    .HAVE_STPNCPY,
    .HAVE_STRCASESTR,
    .HAVE_STRCHRNUL,
    .HAVE_STRERRORNAME_NP,
    .HAVE_STRPBRK,
    .HAVE_STRSEP,
    .HAVE_STRVERSCMP,
    .INCLUDE_NEXT,
    .NEXT_STRING_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_FFSLL,
    .REPLACE_MEMCHR,
    .REPLACE_MEMMEM,
    .REPLACE_STPNCPY,
    .REPLACE_STRCASESTR,
    .REPLACE_STRCHRNUL,
    .REPLACE_STRDUP,
    .REPLACE_STRERROR,
    .REPLACE_STRERRORNAME_NP,
    .REPLACE_STRERROR_R,
    .REPLACE_STRNCAT,
    .REPLACE_STRNDUP,
    .REPLACE_STRNLEN,
    .REPLACE_STRSIGNAL,
    .REPLACE_STRSTR,
    .REPLACE_STRTOK_R,
    .UNDEFINE_STRTOK_R,
};

const sys_random_h_values = &[_]GnulibValueTag{
    .GNULIB_GETRANDOM,
    .GUARD_PREFIX,
    .HAVE_GETRANDOM,
    .HAVE_SYS_RANDOM_H,
    .INCLUDE_NEXT,
    .NEXT_SYS_RANDOM_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_GETRANDOM,
};

const sys_stat_h_values = &[_]GnulibValueTag{
    .GNULIB_FCHMODAT,
    .GNULIB_FSTAT,
    .GNULIB_FSTATAT,
    .GNULIB_FUTIMENS,
    .GNULIB_GETUMASK,
    .GNULIB_LCHMOD,
    .GNULIB_LSTAT,
    .GNULIB_MDA_CHMOD,
    .GNULIB_MDA_MKDIR,
    .GNULIB_MDA_UMASK,
    .GNULIB_MKDIR,
    .GNULIB_MKDIRAT,
    .GNULIB_MKFIFO,
    .GNULIB_MKFIFOAT,
    .GNULIB_MKNOD,
    .GNULIB_MKNODAT,
    .GNULIB_OVERRIDES_STRUCT_STAT,
    .GNULIB_STAT,
    .GNULIB_UTIMENSAT,
    .GUARD_PREFIX,
    .HAVE_FCHMODAT,
    .HAVE_FSTATAT,
    .HAVE_FUTIMENS,
    .HAVE_GETUMASK,
    .HAVE_LCHMOD,
    .HAVE_LSTAT,
    .HAVE_MKDIRAT,
    .HAVE_MKFIFO,
    .HAVE_MKFIFOAT,
    .HAVE_MKNOD,
    .HAVE_MKNODAT,
    .HAVE_UTIMENSAT,
    .INCLUDE_NEXT,
    .NEXT_SYS_STAT_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_FCHMODAT,
    .REPLACE_FSTAT,
    .REPLACE_FSTATAT,
    .REPLACE_FUTIMENS,
    .REPLACE_LSTAT,
    .REPLACE_MKDIR,
    .REPLACE_MKFIFO,
    .REPLACE_MKFIFOAT,
    .REPLACE_MKNOD,
    .REPLACE_MKNODAT,
    .REPLACE_STAT,
    .REPLACE_UTIMENSAT,
    .WINDOWS_64_BIT_ST_SIZE,
    .WINDOWS_STAT_TIMESPEC,
};

const sys_types_h_values = &[_]GnulibValueTag{
    .GUARD_PREFIX,
    .INCLUDE_NEXT,
    .NEXT_SYS_TYPES_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .WINDOWS_64_BIT_OFF_T,
    .WINDOWS_STAT_INODES,
};

const sys_wait_h_values = &[_]GnulibValueTag{
    .GNULIB_WAITPID,
    .GUARD_PREFIX,
    .INCLUDE_NEXT,
    .NEXT_SYS_WAIT_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
};

const time_h_values = &[_]GnulibValueTag{
    .GNULIB_CTIME,
    .GNULIB_LOCALTIME,
    .GNULIB_MDA_TZSET,
    .GNULIB_MKTIME,
    .GNULIB_NANOSLEEP,
    .GNULIB_STRFTIME,
    .GNULIB_STRPTIME,
    .GNULIB_TIMEGM,
    .GNULIB_TIMESPEC_GET,
    .GNULIB_TIME_R,
    .GNULIB_TIME_RZ,
    .GNULIB_TZSET,
    .GUARD_PREFIX,
    .HAVE_DECL_LOCALTIME_R,
    .HAVE_NANOSLEEP,
    .HAVE_STRPTIME,
    .HAVE_TIMEGM,
    .HAVE_TIMESPEC_GET,
    .HAVE_TIMEZONE_T,
    .INCLUDE_NEXT,
    .NEXT_TIME_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .PTHREAD_H_DEFINES_STRUCT_TIMESPEC,
    .REPLACE_CTIME,
    .REPLACE_GMTIME,
    .REPLACE_LOCALTIME,
    .REPLACE_LOCALTIME_R,
    .REPLACE_MKTIME,
    .REPLACE_NANOSLEEP,
    .REPLACE_STRFTIME,
    .REPLACE_TIMEGM,
    .REPLACE_TZSET,
    .SYS_TIME_H_DEFINES_STRUCT_TIMESPEC,
    .TIME_H_DEFINES_STRUCT_TIMESPEC,
    .TIME_H_DEFINES_TIME_UTC,
    .UNISTD_H_DEFINES_STRUCT_TIMESPEC,
};

const unistd_h_values = &[_]GnulibValueTag{
    .GNULIB_ACCESS,
    .GNULIB_CHDIR,
    .GNULIB_CHOWN,
    .GNULIB_CLOSE,
    .GNULIB_COPY_FILE_RANGE,
    .GNULIB_DUP,
    .GNULIB_DUP2,
    .GNULIB_DUP3,
    .GNULIB_ENVIRON,
    .GNULIB_EUIDACCESS,
    .GNULIB_EXECL,
    .GNULIB_EXECLE,
    .GNULIB_EXECLP,
    .GNULIB_EXECV,
    .GNULIB_EXECVE,
    .GNULIB_EXECVP,
    .GNULIB_EXECVPE,
    .GNULIB_FACCESSAT,
    .GNULIB_FCHDIR,
    .GNULIB_FCHOWNAT,
    .GNULIB_FDATASYNC,
    .GNULIB_FSYNC,
    .GNULIB_FTRUNCATE,
    .GNULIB_GETCWD,
    .GNULIB_GETDOMAINNAME,
    .GNULIB_GETDTABLESIZE,
    .GNULIB_GETENTROPY,
    .GNULIB_GETGROUPS,
    .GNULIB_GETHOSTNAME,
    .GNULIB_GETLOGIN,
    .GNULIB_GETLOGIN_R,
    .GNULIB_GETOPT_POSIX,
    .GNULIB_GETPAGESIZE,
    .GNULIB_GETPASS,
    .GNULIB_GETUSERSHELL,
    .GNULIB_GROUP_MEMBER,
    .GNULIB_ISATTY,
    .GNULIB_LCHOWN,
    .GNULIB_LINK,
    .GNULIB_LINKAT,
    .GNULIB_LSEEK,
    .GNULIB_MDA_ACCESS,
    .GNULIB_MDA_CHDIR,
    .GNULIB_MDA_CLOSE,
    .GNULIB_MDA_DUP,
    .GNULIB_MDA_DUP2,
    .GNULIB_MDA_EXECL,
    .GNULIB_MDA_EXECLE,
    .GNULIB_MDA_EXECLP,
    .GNULIB_MDA_EXECV,
    .GNULIB_MDA_EXECVE,
    .GNULIB_MDA_EXECVP,
    .GNULIB_MDA_EXECVPE,
    .GNULIB_MDA_GETCWD,
    .GNULIB_MDA_GETPID,
    .GNULIB_MDA_ISATTY,
    .GNULIB_MDA_LSEEK,
    .GNULIB_MDA_READ,
    .GNULIB_MDA_RMDIR,
    .GNULIB_MDA_SWAB,
    .GNULIB_MDA_UNLINK,
    .GNULIB_MDA_WRITE,
    .GNULIB_PIPE,
    .GNULIB_PIPE2,
    .GNULIB_PREAD,
    .GNULIB_PWRITE,
    .GNULIB_READ,
    .GNULIB_READLINK,
    .GNULIB_READLINKAT,
    .GNULIB_RMDIR,
    .GNULIB_SETHOSTNAME,
    .GNULIB_SLEEP,
    .GNULIB_SYMLINK,
    .GNULIB_SYMLINKAT,
    .GNULIB_TRUNCATE,
    .GNULIB_TTYNAME_R,
    .GNULIB_UNISTD_H_GETOPT,
    .GNULIB_UNLINK,
    .GNULIB_UNLINKAT,
    .GNULIB_USLEEP,
    .GNULIB_WRITE,
    .GUARD_PREFIX,
    .HAVE_CHOWN,
    .HAVE_COPY_FILE_RANGE,
    .HAVE_DECL_ENVIRON,
    .HAVE_DECL_EXECVPE,
    .HAVE_DECL_FCHDIR,
    .HAVE_DECL_FDATASYNC,
    .HAVE_DECL_GETDOMAINNAME,
    .HAVE_DECL_GETLOGIN,
    .HAVE_DECL_GETLOGIN_R,
    .HAVE_DECL_GETPAGESIZE,
    .HAVE_DECL_GETUSERSHELL,
    .HAVE_DECL_SETHOSTNAME,
    .HAVE_DECL_TRUNCATE,
    .HAVE_DECL_TTYNAME_R,
    .HAVE_DUP3,
    .HAVE_EUIDACCESS,
    .HAVE_EXECVPE,
    .HAVE_FACCESSAT,
    .HAVE_FCHDIR,
    .HAVE_FCHOWNAT,
    .HAVE_FDATASYNC,
    .HAVE_FSYNC,
    .HAVE_FTRUNCATE,
    .HAVE_GETDTABLESIZE,
    .HAVE_GETENTROPY,
    .HAVE_GETGROUPS,
    .HAVE_GETHOSTNAME,
    .HAVE_GETPAGESIZE,
    .HAVE_GETPASS,
    .HAVE_GROUP_MEMBER,
    .HAVE_LCHOWN,
    .HAVE_LINK,
    .HAVE_LINKAT,
    .HAVE_OS_H,
    .HAVE_PIPE,
    .HAVE_PIPE2,
    .HAVE_PREAD,
    .HAVE_PWRITE,
    .HAVE_READLINK,
    .HAVE_READLINKAT,
    .HAVE_SETHOSTNAME,
    .HAVE_SLEEP,
    .HAVE_SYMLINK,
    .HAVE_SYMLINKAT,
    .HAVE_SYS_PARAM_H,
    .HAVE_UNISTD_H,
    .HAVE_UNLINKAT,
    .HAVE_USLEEP,
    .INCLUDE_NEXT,
    .NEXT_UNISTD_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_ACCESS,
    .REPLACE_CHOWN,
    .REPLACE_CLOSE,
    .REPLACE_DUP,
    .REPLACE_DUP2,
    .REPLACE_EXECL,
    .REPLACE_EXECLE,
    .REPLACE_EXECLP,
    .REPLACE_EXECV,
    .REPLACE_EXECVE,
    .REPLACE_EXECVP,
    .REPLACE_EXECVPE,
    .REPLACE_FACCESSAT,
    .REPLACE_FCHOWNAT,
    .REPLACE_FTRUNCATE,
    .REPLACE_GETCWD,
    .REPLACE_GETDOMAINNAME,
    .REPLACE_GETDTABLESIZE,
    .REPLACE_GETGROUPS,
    .REPLACE_GETLOGIN_R,
    .REPLACE_GETPAGESIZE,
    .REPLACE_GETPASS,
    .REPLACE_ISATTY,
    .REPLACE_LCHOWN,
    .REPLACE_LINK,
    .REPLACE_LINKAT,
    .REPLACE_LSEEK,
    .REPLACE_PREAD,
    .REPLACE_PWRITE,
    .REPLACE_READ,
    .REPLACE_READLINK,
    .REPLACE_READLINKAT,
    .REPLACE_RMDIR,
    .REPLACE_SLEEP,
    .REPLACE_SYMLINK,
    .REPLACE_SYMLINKAT,
    .REPLACE_TRUNCATE,
    .REPLACE_TTYNAME_R,
    .REPLACE_UNLINK,
    .REPLACE_UNLINKAT,
    .REPLACE_USLEEP,
    .REPLACE_WRITE,
    .UNISTD_H_HAVE_SYS_RANDOM_H,
    .UNISTD_H_HAVE_WINSOCK2_H,
    .UNISTD_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS,
};

const wchar_h_values = &[_]GnulibValueTag{
    .GNULIBHEADERS_OVERRIDE_WINT_T,
    .GNULIB_BTOWC,
    .GNULIB_MBRLEN,
    .GNULIB_MBRTOWC,
    .GNULIB_MBSINIT,
    .GNULIB_MBSNRTOWCS,
    .GNULIB_MBSRTOWCS,
    .GNULIB_MDA_WCSDUP,
    .GNULIB_WCPCPY,
    .GNULIB_WCPNCPY,
    .GNULIB_WCRTOMB,
    .GNULIB_WCSCASECMP,
    .GNULIB_WCSCAT,
    .GNULIB_WCSCHR,
    .GNULIB_WCSCMP,
    .GNULIB_WCSCOLL,
    .GNULIB_WCSCPY,
    .GNULIB_WCSCSPN,
    .GNULIB_WCSDUP,
    .GNULIB_WCSFTIME,
    .GNULIB_WCSLEN,
    .GNULIB_WCSNCASECMP,
    .GNULIB_WCSNCAT,
    .GNULIB_WCSNCMP,
    .GNULIB_WCSNCPY,
    .GNULIB_WCSNLEN,
    .GNULIB_WCSNRTOMBS,
    .GNULIB_WCSPBRK,
    .GNULIB_WCSRCHR,
    .GNULIB_WCSRTOMBS,
    .GNULIB_WCSSPN,
    .GNULIB_WCSSTR,
    .GNULIB_WCSTOK,
    .GNULIB_WCSWIDTH,
    .GNULIB_WCSXFRM,
    .GNULIB_WCTOB,
    .GNULIB_WCWIDTH,
    .GNULIB_WMEMCHR,
    .GNULIB_WMEMCMP,
    .GNULIB_WMEMCPY,
    .GNULIB_WMEMMOVE,
    .GNULIB_WMEMPCPY,
    .GNULIB_WMEMSET,
    .GUARD_PREFIX,
    .HAVE_BTOWC,
    .HAVE_CRTDEFS_H,
    .HAVE_DECL_WCSDUP,
    .HAVE_DECL_WCTOB,
    .HAVE_DECL_WCWIDTH,
    .HAVE_FEATURES_H,
    .HAVE_MBRLEN,
    .HAVE_MBRTOWC,
    .HAVE_MBSINIT,
    .HAVE_MBSNRTOWCS,
    .HAVE_MBSRTOWCS,
    .HAVE_WCHAR_H,
    .HAVE_WCPCPY,
    .HAVE_WCPNCPY,
    .HAVE_WCRTOMB,
    .HAVE_WCSCASECMP,
    .HAVE_WCSCAT,
    .HAVE_WCSCHR,
    .HAVE_WCSCMP,
    .HAVE_WCSCOLL,
    .HAVE_WCSCPY,
    .HAVE_WCSCSPN,
    .HAVE_WCSDUP,
    .HAVE_WCSFTIME,
    .HAVE_WCSLEN,
    .HAVE_WCSNCASECMP,
    .HAVE_WCSNCAT,
    .HAVE_WCSNCMP,
    .HAVE_WCSNCPY,
    .HAVE_WCSNLEN,
    .HAVE_WCSNRTOMBS,
    .HAVE_WCSPBRK,
    .HAVE_WCSRCHR,
    .HAVE_WCSRTOMBS,
    .HAVE_WCSSPN,
    .HAVE_WCSSTR,
    .HAVE_WCSTOK,
    .HAVE_WCSWIDTH,
    .HAVE_WCSXFRM,
    .HAVE_WINT_T,
    .HAVE_WMEMCHR,
    .HAVE_WMEMCMP,
    .HAVE_WMEMCPY,
    .HAVE_WMEMMOVE,
    .HAVE_WMEMPCPY,
    .HAVE_WMEMSET,
    .INCLUDE_NEXT,
    .NEXT_WCHAR_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_BTOWC,
    .REPLACE_MBRLEN,
    .REPLACE_MBRTOWC,
    .REPLACE_MBSINIT,
    .REPLACE_MBSNRTOWCS,
    .REPLACE_MBSRTOWCS,
    .REPLACE_MBSTATE_T,
    .REPLACE_WCRTOMB,
    .REPLACE_WCSFTIME,
    .REPLACE_WCSNRTOMBS,
    .REPLACE_WCSRTOMBS,
    .REPLACE_WCSTOK,
    .REPLACE_WCSWIDTH,
    .REPLACE_WCTOB,
    .REPLACE_WCWIDTH,
};

const wctype_h_values = &[_]GnulibValueTag{
    .GNULIBHEADERS_OVERRIDE_WINT_T,
    .GNULIB_ISWBLANK,
    .GNULIB_ISWCTYPE,
    .GNULIB_ISWDIGIT,
    .GNULIB_ISWXDIGIT,
    .GNULIB_TOWCTRANS,
    .GNULIB_WCTRANS,
    .GNULIB_WCTYPE,
    .GUARD_PREFIX,
    .HAVE_CRTDEFS_H,
    .HAVE_ISWBLANK,
    .HAVE_ISWCNTRL,
    .HAVE_WCTRANS_T,
    .HAVE_WCTYPE_H,
    .HAVE_WCTYPE_T,
    .HAVE_WINT_T,
    .INCLUDE_NEXT,
    .NEXT_WCTYPE_H,
    .PRAGMA_COLUMNS,
    .PRAGMA_SYSTEM_HEADER,
    .REPLACE_ISWBLANK,
    .REPLACE_ISWCNTRL,
    .REPLACE_ISWDIGIT,
    .REPLACE_ISWXDIGIT,
    .REPLACE_TOWLOWER,
};
